/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.CsiLogAudit;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CsiLogAuditRecord extends UpdatableRecordImpl<CsiLogAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.csi_log_audit.audit_id</code>.
     */
    public void setAuditId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.audit_id</code>.
     */
    public Long getAuditId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reea.csi_log_audit.data_ora</code>.
     */
    public void setDataOra(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.data_ora</code>.
     */
    public LocalDateTime getDataOra() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>reea.csi_log_audit.id_app</code>.
     */
    public void setIdApp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.id_app</code>.
     */
    public String getIdApp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.csi_log_audit.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.csi_log_audit.utente</code>.
     */
    public void setUtente(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.utente</code>.
     */
    public String getUtente() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reea.csi_log_audit.operazione</code>.
     */
    public void setOperazione(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.operazione</code>.
     */
    public String getOperazione() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reea.csi_log_audit.ogg_oper</code>.
     */
    public void setOggOper(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.ogg_oper</code>.
     */
    public String getOggOper() {
        return (String) get(6);
    }

    /**
     * Setter for <code>reea.csi_log_audit.key_oper</code>.
     */
    public void setKeyOper(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.key_oper</code>.
     */
    public String getKeyOper() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reea.csi_log_audit.uuid</code>.
     */
    public void setUuid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.uuid</code>.
     */
    public String getUuid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.csi_log_audit.request_payload</code>.
     */
    public void setRequestPayload(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.request_payload</code>.
     */
    public byte[] getRequestPayload() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>reea.csi_log_audit.response_payload</code>.
     */
    public void setResponsePayload(byte[] value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.response_payload</code>.
     */
    public byte[] getResponsePayload() {
        return (byte[]) get(10);
    }

    /**
     * Setter for <code>reea.csi_log_audit.esito_chiamata</code>.
     */
    public void setEsitoChiamata(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.csi_log_audit.esito_chiamata</code>.
     */
    public Integer getEsitoChiamata() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CsiLogAuditRecord
     */
    public CsiLogAuditRecord() {
        super(CsiLogAudit.CSI_LOG_AUDIT);
    }

    /**
     * Create a detached, initialised CsiLogAuditRecord
     */
    public CsiLogAuditRecord(Long auditId, LocalDateTime dataOra, String idApp, String ipAddress, String utente, String operazione, String oggOper, String keyOper, String uuid, byte[] requestPayload, byte[] responsePayload, Integer esitoChiamata) {
        super(CsiLogAudit.CSI_LOG_AUDIT);

        setAuditId(auditId);
        setDataOra(dataOra);
        setIdApp(idApp);
        setIpAddress(ipAddress);
        setUtente(utente);
        setOperazione(operazione);
        setOggOper(oggOper);
        setKeyOper(keyOper);
        setUuid(uuid);
        setRequestPayload(requestPayload);
        setResponsePayload(responsePayload);
        setEsitoChiamata(esitoChiamata);
        resetChangedOnNotNull();
    }
}
