/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDFonte;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Segnalazione MMG, altro Pre-adesione INAIL SPRESAL PIANI DI LAVORO AMIANTO  
 * --ex valori PREADESIONE INAIL SPRESAL-ANMNESI SPRESAL-ESITI PIANI DI LAVORO
 * AMIANTO REGISTRO CANCEROGENI MANUALE(MMG)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDFonteRecord extends UpdatableRecordImpl<ReeaDFonteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_fonte.fonte_id</code>.
     */
    public void setFonteId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.fonte_id</code>.
     */
    public Integer getFonteId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.fonte_cod</code>.
     */
    public void setFonteCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.fonte_cod</code>.
     */
    public String getFonteCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.fonte_desc</code>.
     */
    public void setFonteDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.fonte_desc</code>.
     */
    public String getFonteDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_fonte.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_fonte.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDFonteRecord
     */
    public ReeaDFonteRecord() {
        super(ReeaDFonte.REEA_D_FONTE);
    }

    /**
     * Create a detached, initialised ReeaDFonteRecord
     */
    public ReeaDFonteRecord(Integer fonteId, String fonteCod, String fonteDesc, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDFonte.REEA_D_FONTE);

        setFonteId(fonteId);
        setFonteCod(fonteCod);
        setFonteDesc(fonteDesc);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
