/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTFile;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Registro dei file caricati a sistema. Rappresenta il file fisico su disco.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTFileRecord extends UpdatableRecordImpl<ReeaTFileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_file.file_id</code>.
     */
    public void setFileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_id</code>.
     */
    public Integer getFileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_name</code>. Nome del file
     * compresa estensione
     */
    public void setFileName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_name</code>. Nome del file
     * compresa estensione
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_path</code>. Percorso del file sul
     * file system (es./reea/fonti/preadesione)
     */
    public void setFilePath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_path</code>. Percorso del file sul
     * file system (es./reea/fonti/preadesione)
     */
    public String getFilePath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_hash_checksum</code>. È la stringa
     * hash che rappresenta l’impronta digitale del file.
     */
    public void setFileHashChecksum(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_hash_checksum</code>. È la stringa
     * hash che rappresenta l’impronta digitale del file.
     */
    public String getFileHashChecksum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_mime_type</code>. Tipo/sottotipo
     * del file (es. per CSV file è txt/csv)
     */
    public void setFileMimeType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_mime_type</code>. Tipo/sottotipo
     * del file (es. per CSV file è txt/csv)
     */
    public String getFileMimeType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_dimensione_bytes</code>.
     * Dimensione del file in byte
     */
    public void setFileDimensioneBytes(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_dimensione_bytes</code>.
     * Dimensione del file in byte
     */
    public Long getFileDimensioneBytes() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_file.file_stato_id</code>. Stato del file
     * (FK)
     */
    public void setFileStatoId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.file_stato_id</code>. Stato del file
     * (FK)
     */
    public Integer getFileStatoId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_file.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_file.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_file.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_file.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_file.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>reea.reea_t_file.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_file.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(13);
    }

    /**
     * Setter for <code>reea.reea_t_file.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_t_file.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTFileRecord
     */
    public ReeaTFileRecord() {
        super(ReeaTFile.REEA_T_FILE);
    }

    /**
     * Create a detached, initialised ReeaTFileRecord
     */
    public ReeaTFileRecord(Integer fileId, String fileName, String filePath, String fileHashChecksum, String fileMimeType, Long fileDimensioneBytes, Integer fileStatoId, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaTFile.REEA_T_FILE);

        setFileId(fileId);
        setFileName(fileName);
        setFilePath(filePath);
        setFileHashChecksum(fileHashChecksum);
        setFileMimeType(fileMimeType);
        setFileDimensioneBytes(fileDimensioneBytes);
        setFileStatoId(fileStatoId);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
