/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTFunzionalita;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Elenco puntuale delle funzionalità/azioni eseguibili nel sistema.  Fonte: PDF
 * Specifica Database, Sezione 2.1 (Pag. 4), Tabella RREA_T_FUNZIONE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTFunzionalitaRecord extends UpdatableRecordImpl<ReeaTFunzionalitaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_funzionalita.funzionalita_id</code>.
     */
    public void setFunzionalitaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.funzionalita_id</code>.
     */
    public Integer getFunzionalitaId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.gruppo_funzionalita_id</code>.
     */
    public void setGruppoFunzionalitaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.gruppo_funzionalita_id</code>.
     */
    public Integer getGruppoFunzionalitaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.funzionalita_cod</code>.
     */
    public void setFunzionalitaCod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.funzionalita_cod</code>.
     */
    public String getFunzionalitaCod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.funzionalita_desc</code>.
     */
    public void setFunzionalitaDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.funzionalita_desc</code>.
     */
    public String getFunzionalitaDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.funzionalita_padre_cod</code>.
     */
    public void setFunzionalitaPadreCod(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.funzionalita_padre_cod</code>.
     */
    public String getFunzionalitaPadreCod() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.funzionalita_padre_desc</code>.
     */
    public void setFunzionalitaPadreDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.funzionalita_padre_desc</code>.
     */
    public String getFunzionalitaPadreDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(11);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_funzionalita.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_funzionalita.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTFunzionalitaRecord
     */
    public ReeaTFunzionalitaRecord() {
        super(ReeaTFunzionalita.REEA_T_FUNZIONALITA);
    }

    /**
     * Create a detached, initialised ReeaTFunzionalitaRecord
     */
    public ReeaTFunzionalitaRecord(Integer funzionalitaId, Integer gruppoFunzionalitaId, String funzionalitaCod, String funzionalitaDesc, String funzionalitaPadreCod, String funzionalitaPadreDesc, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaTFunzionalita.REEA_T_FUNZIONALITA);

        setFunzionalitaId(funzionalitaId);
        setGruppoFunzionalitaId(gruppoFunzionalitaId);
        setFunzionalitaCod(funzionalitaCod);
        setFunzionalitaDesc(funzionalitaDesc);
        setFunzionalitaPadreCod(funzionalitaPadreCod);
        setFunzionalitaPadreDesc(funzionalitaPadreDesc);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
