/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiRagionesociale;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * valorizza di default
 * reea_d_registro_spresal_anamnesi.occupazione_ragione_sociale_ditta_crpt
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRegistroSpresalAnamnesiRagionesocialeRecord extends UpdatableRecordImpl<ReeaDRegistroSpresalAnamnesiRagionesocialeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ragionesociale_id</code>.
     */
    public void setRagionesocialeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ragionesociale_id</code>.
     */
    public Integer getRagionesocialeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ragionesociale</code>.
     * codice
     */
    public void setRagionesociale(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ragionesociale</code>.
     * codice
     */
    public String getRagionesociale() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.piva</code>.
     * descrizione
     */
    public void setPiva(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.piva</code>.
     * descrizione
     */
    public String getPiva() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.validita_inizio</code>.
     * inizio validità record
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.validita_inizio</code>.
     * inizio validità record
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.validita_fine</code>.
     * fine validità record
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.validita_fine</code>.
     * fine validità record
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_creazione</code>.
     * data creazione record
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_creazione</code>.
     * data creazione record
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_modifica</code>.
     * data modifica record
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_modifica</code>.
     * data modifica record
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_cancellazione</code>.
     * data cancellazione record
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.data_cancellazione</code>.
     * data cancellazione record
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_creazione</code>.
     * utente creazione
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_creazione</code>.
     * utente creazione
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_modifica</code>.
     * utente modifica
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_modifica</code>.
     * utente modifica
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_cancellazione</code>.
     * utente cancellazione
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.utente_cancellazione</code>.
     * utente cancellazione
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ditta_codice_fiscale</code>.
     */
    public void setDittaCodiceFiscale(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_registro_spresal_anamnesi_ragionesociale.ditta_codice_fiscale</code>.
     */
    public String getDittaCodiceFiscale() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDRegistroSpresalAnamnesiRagionesocialeRecord
     */
    public ReeaDRegistroSpresalAnamnesiRagionesocialeRecord() {
        super(ReeaDRegistroSpresalAnamnesiRagionesociale.REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE);
    }

    /**
     * Create a detached, initialised
     * ReeaDRegistroSpresalAnamnesiRagionesocialeRecord
     */
    public ReeaDRegistroSpresalAnamnesiRagionesocialeRecord(Integer ragionesocialeId, String ragionesociale, String piva, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, String dittaCodiceFiscale) {
        super(ReeaDRegistroSpresalAnamnesiRagionesociale.REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE);

        setRagionesocialeId(ragionesocialeId);
        setRagionesociale(ragionesociale);
        setPiva(piva);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setDittaCodiceFiscale(dittaCodiceFiscale);
        resetChangedOnNotNull();
    }
}
