/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaLFileElaborazione;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Storico dei tentativi di elaborazione batch. Permette di gestire i retry
 * mantenendo traccia degli errori passati.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaLFileElaborazioneRecord extends UpdatableRecordImpl<ReeaLFileElaborazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.elaborazione_id</code>.
     */
    public void setElaborazioneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.elaborazione_id</code>.
     */
    public Integer getElaborazioneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.file_id</code>. Id del
     * file
     */
    public void setFileId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.file_id</code>. Id del
     * file
     */
    public Integer getFileId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.numero_tentativo</code>.
     * Numero tentativo di elaborazione del file
     */
    public void setNumeroTentativo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.numero_tentativo</code>.
     * Numero tentativo di elaborazione del file
     */
    public Integer getNumeroTentativo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.file_stato_id</code>.
     * Stato del file
     */
    public void setFileStatoId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.file_stato_id</code>.
     * Stato del file
     */
    public Integer getFileStatoId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.data_inizio</code>. Data
     * inizio elaborazione
     */
    public void setDataInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.data_inizio</code>. Data
     * inizio elaborazione
     */
    public LocalDateTime getDataInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.data_fine</code>. Data
     * fine elaborazione
     */
    public void setDataFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.data_fine</code>. Data
     * fine elaborazione
     */
    public LocalDateTime getDataFine() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.righe_totali</code>.
     * Numero righe totali del file
     */
    public void setRigheTotali(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.righe_totali</code>.
     * Numero righe totali del file
     */
    public Integer getRigheTotali() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.righe_elaborate</code>.
     * Numero righe elaborate
     */
    public void setRigheElaborate(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.righe_elaborate</code>.
     * Numero righe elaborate
     */
    public Integer getRigheElaborate() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.righe_scartate</code>.
     * Numero righe scartate
     */
    public void setRigheScartate(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.righe_scartate</code>.
     * Numero righe scartate
     */
    public Integer getRigheScartate() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.righe_modificanti</code>.
     * Numero righe che hanno modificato una riga di una tabella
     */
    public void setRigheModificanti(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.righe_modificanti</code>.
     * Numero righe che hanno modificato una riga di una tabella
     */
    public Integer getRigheModificanti() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.messaggio_sistema</code>.
     * Messaggio del sistema
     */
    public void setMessaggioSistema(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.messaggio_sistema</code>.
     * Messaggio del sistema
     */
    public String getMessaggioSistema() {
        return (String) get(10);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(16);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(17);
    }

    /**
     * Setter for
     * <code>reea.reea_l_file_elaborazione.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(18, value);
    }

    /**
     * Getter for
     * <code>reea.reea_l_file_elaborazione.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(18);
    }

    /**
     * Setter for <code>reea.reea_l_file_elaborazione.righe_errate</code>.
     * Numero righe errate
     */
    public void setRigheErrate(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>reea.reea_l_file_elaborazione.righe_errate</code>.
     * Numero righe errate
     */
    public Integer getRigheErrate() {
        return (Integer) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaLFileElaborazioneRecord
     */
    public ReeaLFileElaborazioneRecord() {
        super(ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE);
    }

    /**
     * Create a detached, initialised ReeaLFileElaborazioneRecord
     */
    public ReeaLFileElaborazioneRecord(Integer elaborazioneId, Integer fileId, Integer numeroTentativo, Integer fileStatoId, LocalDateTime dataInizio, LocalDateTime dataFine, Integer righeTotali, Integer righeElaborate, Integer righeScartate, Integer righeModificanti, String messaggioSistema, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, Integer righeErrate) {
        super(ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE);

        setElaborazioneId(elaborazioneId);
        setFileId(fileId);
        setNumeroTentativo(numeroTentativo);
        setFileStatoId(fileStatoId);
        setDataInizio(dataInizio);
        setDataFine(dataFine);
        setRigheTotali(righeTotali);
        setRigheElaborate(righeElaborate);
        setRigheScartate(righeScartate);
        setRigheModificanti(righeModificanti);
        setMessaggioSistema(messaggioSistema);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setRigheErrate(righeErrate);
        resetChangedOnNotNull();
    }
}
