/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaCParametroTipo;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * tipo di parametri di configurazione Es.  ERRORE MESSAGGIO_PUSH
 * MESSAGGIO_EMAIL MESSAGGIO_SMS PARAMETRO
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaCParametroTipoRecord extends UpdatableRecordImpl<ReeaCParametroTipoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.parametro_tipo_id</code>.
     */
    public void setParametroTipoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.parametro_tipo_id</code>.
     */
    public Integer getParametroTipoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.parametro_tipo_cod</code>.
     * codice
     */
    public void setParametroTipoCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.parametro_tipo_cod</code>.
     * codice
     */
    public String getParametroTipoCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.parametro_tipo_desc</code>.
     * descrizione
     */
    public void setParametroTipoDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.parametro_tipo_desc</code>.
     * descrizione
     */
    public String getParametroTipoDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.validita_inizio</code>.
     * inizio validità record
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.validita_inizio</code>.
     * inizio validità record
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.validita_fine</code>. fine
     * validità record
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.validita_fine</code>. fine
     * validità record
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.data_creazione</code>. data
     * creazione record
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.data_creazione</code>. data
     * creazione record
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.data_modifica</code>. data
     * modifica record
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.data_modifica</code>. data
     * modifica record
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.data_cancellazione</code>.
     * data cancellazione record
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.data_cancellazione</code>.
     * data cancellazione record
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.utente_creazione</code>.
     * utente creazione
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.utente_creazione</code>.
     * utente creazione
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.utente_modifica</code>.
     * utente modifica
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.utente_modifica</code>.
     * utente modifica
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_c_parametro_tipo.utente_cancellazione</code>.
     * utente cancellazione
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_c_parametro_tipo.utente_cancellazione</code>.
     * utente cancellazione
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaCParametroTipoRecord
     */
    public ReeaCParametroTipoRecord() {
        super(ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO);
    }

    /**
     * Create a detached, initialised ReeaCParametroTipoRecord
     */
    public ReeaCParametroTipoRecord(Integer parametroTipoId, String parametroTipoCod, String parametroTipoDesc, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO);

        setParametroTipoId(parametroTipoId);
        setParametroTipoCod(parametroTipoCod);
        setParametroTipoDesc(parametroTipoDesc);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
