/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDCampoMascherato;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDCampoMascheratoRecord extends UpdatableRecordImpl<ReeaDCampoMascheratoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.campo_mascherato_id</code>.
     */
    public void setCampoMascheratoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.campo_mascherato_id</code>.
     */
    public Integer getCampoMascheratoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_cod</code>.
     */
    public void setCampoMascheratoCod(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_cod</code>.
     */
    public String getCampoMascheratoCod() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_desc</code>.
     */
    public void setCampoMascheratoDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_desc</code>.
     */
    public String getCampoMascheratoDesc() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_valore</code>.
     */
    public void setCampoMascheratoValore(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_campo_mascherato.campo_mascherato_valore</code>.
     */
    public String getCampoMascheratoValore() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_campo_mascherato.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_campo_mascherato.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>reea.reea_d_campo_mascherato.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>reea.reea_d_campo_mascherato.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDCampoMascheratoRecord
     */
    public ReeaDCampoMascheratoRecord() {
        super(ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO);
    }

    /**
     * Create a detached, initialised ReeaDCampoMascheratoRecord
     */
    public ReeaDCampoMascheratoRecord(Integer campoMascheratoId, String campoMascheratoCod, String campoMascheratoDesc, String campoMascheratoValore, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO);

        setCampoMascheratoId(campoMascheratoId);
        setCampoMascheratoCod(campoMascheratoCod);
        setCampoMascheratoDesc(campoMascheratoDesc);
        setCampoMascheratoValore(campoMascheratoValore);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
