/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTCollocazione;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Sedi operative (ospedali, distretti) associate alle aziende.  Fonte: PDF
 * Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_T_COLLOCAZIONE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTCollocazioneRecord extends UpdatableRecordImpl<ReeaTCollocazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_collocazione.collocazione_id</code>.
     */
    public void setCollocazioneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.collocazione_id</code>.
     */
    public Integer getCollocazioneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.collocazione_cod</code>.
     */
    public void setCollocazioneCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.collocazione_cod</code>.
     */
    public String getCollocazioneCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.collocazione_desc</code>.
     */
    public void setCollocazioneDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.collocazione_desc</code>.
     */
    public String getCollocazioneDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.azienda_id</code>.
     */
    public void setAziendaId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.azienda_id</code>.
     */
    public Integer getAziendaId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_collocazione.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_collocazione.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTCollocazioneRecord
     */
    public ReeaTCollocazioneRecord() {
        super(ReeaTCollocazione.REEA_T_COLLOCAZIONE);
    }

    /**
     * Create a detached, initialised ReeaTCollocazioneRecord
     */
    public ReeaTCollocazioneRecord(Integer collocazioneId, String collocazioneCod, String collocazioneDesc, Integer aziendaId, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaTCollocazione.REEA_T_COLLOCAZIONE);

        setCollocazioneId(collocazioneId);
        setCollocazioneCod(collocazioneCod);
        setCollocazioneDesc(collocazioneDesc);
        setAziendaId(aziendaId);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
