/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTRegistroPdlAmianto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Registro PDL Amianto - piani di lavoro per cantieri di rimozione amianto
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTRegistroPdlAmiantoRecord extends UpdatableRecordImpl<ReeaTRegistroPdlAmiantoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.reg_pdl_amianto_id</code>.
     */
    public void setRegPdlAmiantoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.reg_pdl_amianto_id</code>.
     */
    public Integer getRegPdlAmiantoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.registro_id</code>.
     */
    public void setRegistroId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.registro_id</code>.
     */
    public Integer getRegistroId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.codice_fiscale</code>.
     * E.1 - Codice Fiscale assistito
     */
    public void setCodiceFiscale(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.codice_fiscale</code>.
     * E.1 - Codice Fiscale assistito
     */
    public String getCodiceFiscale() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.periodo</code>. E.3 -
     * Durata del cantiere in giorni
     */
    public void setPeriodo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.periodo</code>. E.3 -
     * Durata del cantiere in giorni
     */
    public Integer getPeriodo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.id_cantiere</code>. E.4
     * - Identificativo cantiere di rimozione amianto
     */
    public void setIdCantiere(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.id_cantiere</code>. E.4
     * - Identificativo cantiere di rimozione amianto
     */
    public Integer getIdCantiere() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.azienda_piva</code>.
     * E.5 - P. IVA azienda che ha allestito il cantiere
     */
    public void setAziendaPiva(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.azienda_piva</code>.
     * E.5 - P. IVA azienda che ha allestito il cantiere
     */
    public String getAziendaPiva() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.azienda_nome</code>.
     * E.6 - Nome azienda che ha allestito il cantiere
     */
    public void setAziendaNome(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.azienda_nome</code>.
     * E.6 - Nome azienda che ha allestito il cantiere
     */
    public String getAziendaNome() {
        return (String) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.asl_cantiere</code>.
     * E.7 - Azienda del cantiere
     */
    public void setAslCantiere(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.asl_cantiere</code>.
     * E.7 - Azienda del cantiere
     */
    public String getAslCantiere() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.comune_cantiere</code>.
     * E.8 - Codice ISTAT del comune del cantiere
     */
    public void setComuneCantiere(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.comune_cantiere</code>.
     * E.8 - Codice ISTAT del comune del cantiere
     */
    public String getComuneCantiere() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.anno</code>. E.9 - Anno
     * del cantiere
     */
    public void setAnno(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.anno</code>. E.9 - Anno
     * del cantiere
     */
    public Integer getAnno() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.tipologia_piano</code>.
     * E.10 - Tipologia piano (es. art. 250 compatto, art. 250 friabile)
     */
    public void setTipologiaPiano(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.tipologia_piano</code>.
     * E.10 - Tipologia piano (es. art. 250 compatto, art. 250 friabile)
     */
    public String getTipologiaPiano() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.quantita_da_rimuovere</code>. E.11
     * - Quantità di amianto da rimuovere in Kg
     */
    public void setQuantitaDaRimuovere(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.quantita_da_rimuovere</code>. E.11
     * - Quantità di amianto da rimuovere in Kg
     */
    public BigDecimal getQuantitaDaRimuovere() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.quantita_rimossa</code>. E.12 -
     * Quantità di amianto rimossa in kg
     */
    public void setQuantitaRimossa(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.quantita_rimossa</code>. E.12 -
     * Quantità di amianto rimossa in kg
     */
    public BigDecimal getQuantitaRimossa() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(18, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(18);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(19);
    }

    /**
     * Setter for
     * <code>reea.reea_t_registro_pdl_amianto.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_registro_pdl_amianto.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(20);
    }

    /**
     * Setter for <code>reea.reea_t_registro_pdl_amianto.file_id</code>.
     */
    public void setFileId(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro_pdl_amianto.file_id</code>.
     */
    public Integer getFileId() {
        return (Integer) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTRegistroPdlAmiantoRecord
     */
    public ReeaTRegistroPdlAmiantoRecord() {
        super(ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO);
    }

    /**
     * Create a detached, initialised ReeaTRegistroPdlAmiantoRecord
     */
    public ReeaTRegistroPdlAmiantoRecord(Integer regPdlAmiantoId, Integer registroId, String codiceFiscale, Integer periodo, Integer idCantiere, String aziendaPiva, String aziendaNome, String aslCantiere, String comuneCantiere, Integer anno, String tipologiaPiano, BigDecimal quantitaDaRimuovere, BigDecimal quantitaRimossa, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, Integer fileId) {
        super(ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO);

        setRegPdlAmiantoId(regPdlAmiantoId);
        setRegistroId(registroId);
        setCodiceFiscale(codiceFiscale);
        setPeriodo(periodo);
        setIdCantiere(idCantiere);
        setAziendaPiva(aziendaPiva);
        setAziendaNome(aziendaNome);
        setAslCantiere(aslCantiere);
        setComuneCantiere(comuneCantiere);
        setAnno(anno);
        setTipologiaPiano(tipologiaPiano);
        setQuantitaDaRimuovere(quantitaDaRimuovere);
        setQuantitaRimossa(quantitaRimossa);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setFileId(fileId);
        resetChangedOnNotNull();
    }
}
