/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDRegione;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * REGIONE PIEMONTE FUORI REGIONE PIEMONTE SASN AIRE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRegioneRecord extends UpdatableRecordImpl<ReeaDRegioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_regione.regione_id</code>.
     */
    public void setRegioneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.regione_id</code>.
     */
    public Integer getRegioneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_regione.regione_cod</code>.
     */
    public void setRegioneCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.regione_cod</code>.
     */
    public String getRegioneCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_regione.regione_desc</code>.
     */
    public void setRegioneDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.regione_desc</code>.
     */
    public String getRegioneDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_regione.nazione_id</code>.
     */
    public void setNazioneId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.nazione_id</code>.
     */
    public Integer getNazioneId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_regione.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_regione.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_regione.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_regione.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_regione.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_regione.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_regione.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(10);
    }

    /**
     * Setter for <code>reea.reea_d_regione.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_d_regione.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDRegioneRecord
     */
    public ReeaDRegioneRecord() {
        super(ReeaDRegione.REEA_D_REGIONE);
    }

    /**
     * Create a detached, initialised ReeaDRegioneRecord
     */
    public ReeaDRegioneRecord(Integer regioneId, String regioneCod, String regioneDesc, Integer nazioneId, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDRegione.REEA_D_REGIONE);

        setRegioneId(regioneId);
        setRegioneCod(regioneCod);
        setRegioneDesc(regioneDesc);
        setNazioneId(nazioneId);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
