/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDComune;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDComuneRecord extends UpdatableRecordImpl<ReeaDComuneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_comune.comune_id</code>.
     */
    public void setComuneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.comune_id</code>.
     */
    public Integer getComuneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_comune.comune_cod</code>.
     */
    public void setComuneCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.comune_cod</code>.
     */
    public String getComuneCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_comune.comune_desc</code>.
     */
    public void setComuneDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.comune_desc</code>.
     */
    public String getComuneDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_comune.provincia_id</code>.
     */
    public void setProvinciaId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.provincia_id</code>.
     */
    public Integer getProvinciaId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_comune.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_comune.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_comune.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_comune.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_comune.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_comune.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_comune.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(10);
    }

    /**
     * Setter for <code>reea.reea_d_comune.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(11);
    }

    /**
     * Setter for <code>reea.reea_d_comune.provincia_sigla</code>.
     */
    public void setProvinciaSigla(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_d_comune.provincia_sigla</code>.
     */
    public String getProvinciaSigla() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDComuneRecord
     */
    public ReeaDComuneRecord() {
        super(ReeaDComune.REEA_D_COMUNE);
    }

    /**
     * Create a detached, initialised ReeaDComuneRecord
     */
    public ReeaDComuneRecord(Integer comuneId, String comuneCod, String comuneDesc, Integer provinciaId, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, String provinciaSigla) {
        super(ReeaDComune.REEA_D_COMUNE);

        setComuneId(comuneId);
        setComuneCod(comuneCod);
        setComuneDesc(comuneDesc);
        setProvinciaId(provinciaId);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setProvinciaSigla(provinciaSigla);
        resetChangedOnNotNull();
    }
}
