/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTUtente;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Anagrafica degli operatori che accedono al backoffice (RUPAR/SPID).  Fonte:
 * PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella RREA_T_UTENTE (e
 * Sezione 1.1 Profilazione PDF 1).
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTUtenteRecord extends UpdatableRecordImpl<ReeaTUtenteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_utente.utente_id</code>.
     */
    public void setUtenteId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_id</code>.
     */
    public Integer getUtenteId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_utente.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_utente.cognome</code>.
     */
    public void setCognome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.cognome</code>.
     */
    public String getCognome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_utente.codice_fiscale</code>.
     */
    public void setCodiceFiscale(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.codice_fiscale</code>.
     */
    public String getCodiceFiscale() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_utente.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_utente.attivo</code>.
     */
    public void setAttivo(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.attivo</code>.
     */
    public Boolean getAttivo() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_utente.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_utente.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_utente.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_utente.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_utente.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_utente.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(11);
    }

    /**
     * Setter for <code>reea.reea_t_utente.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_utente.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(13);
    }

    /**
     * Setter for <code>reea.reea_t_utente.utente_user</code>.
     */
    public void setUtenteUser(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_user</code>.
     */
    public String getUtenteUser() {
        return (String) get(14);
    }

    /**
     * Setter for <code>reea.reea_t_utente.utente_pwd</code>.
     */
    public void setUtentePwd(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_t_utente.utente_pwd</code>.
     */
    public String getUtentePwd() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTUtenteRecord
     */
    public ReeaTUtenteRecord() {
        super(ReeaTUtente.REEA_T_UTENTE);
    }

    /**
     * Create a detached, initialised ReeaTUtenteRecord
     */
    public ReeaTUtenteRecord(Integer utenteId, String nome, String cognome, String codiceFiscale, String email, Boolean attivo, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, String utenteUser, String utentePwd) {
        super(ReeaTUtente.REEA_T_UTENTE);

        setUtenteId(utenteId);
        setNome(nome);
        setCognome(cognome);
        setCodiceFiscale(codiceFiscale);
        setEmail(email);
        setAttivo(attivo);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setUtenteUser(utenteUser);
        setUtentePwd(utentePwd);
        resetChangedOnNotNull();
    }
}
