/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDSoggettoStato;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Dizionario degli stati di avanzamento della pratica (es. Da Validare,
 * Monitoraggio).  Fonte: PDF Specifica Database, Sezione 2.3.3 (Pag. 8),
 * Tabella REEA_D_ASSISTITO_STATO.  -    DA VALIDARE -    VALIDATO -    NON
 * VALIDATO -    INVIATO AL MONITORAGGIO -    ESCLUSO DAL MONITORAGGIO -   
 * MONITORAGGIO CONCLUSO
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDSoggettoStatoRecord extends UpdatableRecordImpl<ReeaDSoggettoStatoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.soggetto_stato_id</code>.
     */
    public void setSoggettoStatoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.soggetto_stato_id</code>.
     */
    public Integer getSoggettoStatoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.soggetto_stato_cod</code>.
     */
    public void setSoggettoStatoCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.soggetto_stato_cod</code>.
     */
    public String getSoggettoStatoCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.soggetto_stato_desc</code>.
     */
    public void setSoggettoStatoDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.soggetto_stato_desc</code>.
     */
    public String getSoggettoStatoDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_soggetto_stato.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_soggetto_stato.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDSoggettoStatoRecord
     */
    public ReeaDSoggettoStatoRecord() {
        super(ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO);
    }

    /**
     * Create a detached, initialised ReeaDSoggettoStatoRecord
     */
    public ReeaDSoggettoStatoRecord(Integer soggettoStatoId, String soggettoStatoCod, String soggettoStatoDesc, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO);

        setSoggettoStatoId(soggettoStatoId);
        setSoggettoStatoCod(soggettoStatoCod);
        setSoggettoStatoDesc(soggettoStatoDesc);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
