/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTEsposizione;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTEsposizioneRecord extends UpdatableRecordImpl<ReeaTEsposizioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_id</code>.
     */
    public void setEsposizioneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_id</code>.
     */
    public Integer getEsposizioneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.soggetto_id_hmac</code>. collate
     * C
     */
    public void setSoggettoIdHmac(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.soggetto_id_hmac</code>. collate
     * C
     */
    public String getSoggettoIdHmac() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.soggetto_id_cifrato</code>.
     */
    public void setSoggettoIdCifrato(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.soggetto_id_cifrato</code>.
     */
    public byte[] getSoggettoIdCifrato() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_azienda</code>.
     */
    public void setEsposizioneAzienda(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_azienda</code>.
     */
    public String getEsposizioneAzienda() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_comune_cod</code>.
     */
    public void setEsposizioneAziendaComuneCod(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_comune_cod</code>.
     */
    public String getEsposizioneAziendaComuneCod() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_comune_desc</code>.
     */
    public void setEsposizioneAziendaComuneDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_comune_desc</code>.
     */
    public String getEsposizioneAziendaComuneDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_azienda_cap</code>.
     */
    public void setEsposizioneAziendaCap(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_azienda_cap</code>.
     */
    public String getEsposizioneAziendaCap() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_provincia</code>.
     */
    public void setEsposizioneAziendaProvincia(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>reea.reea_t_esposizione.esposizione_azienda_provincia</code>.
     */
    public String getEsposizioneAziendaProvincia() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_mansione</code>.
     */
    public void setEsposizioneMansione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_mansione</code>.
     */
    public String getEsposizioneMansione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_inizio</code>.
     */
    public void setEsposizioneInizio(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_inizio</code>.
     */
    public LocalDateTime getEsposizioneInizio() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.esposizione_fine</code>.
     */
    public void setEsposizioneFine(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.esposizione_fine</code>.
     */
    public LocalDateTime getEsposizioneFine() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.fonte_id</code>.
     */
    public void setFonteId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.fonte_id</code>.
     */
    public Integer getFonteId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(15);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(16);
    }

    /**
     * Setter for <code>reea.reea_t_esposizione.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>reea.reea_t_esposizione.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTEsposizioneRecord
     */
    public ReeaTEsposizioneRecord() {
        super(ReeaTEsposizione.REEA_T_ESPOSIZIONE);
    }

    /**
     * Create a detached, initialised ReeaTEsposizioneRecord
     */
    public ReeaTEsposizioneRecord(Integer esposizioneId, String soggettoIdHmac, byte[] soggettoIdCifrato, String esposizioneAzienda, String esposizioneAziendaComuneCod, String esposizioneAziendaComuneDesc, String esposizioneAziendaCap, String esposizioneAziendaProvincia, String esposizioneMansione, LocalDateTime esposizioneInizio, LocalDateTime esposizioneFine, Integer fonteId, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaTEsposizione.REEA_T_ESPOSIZIONE);

        setEsposizioneId(esposizioneId);
        setSoggettoIdHmac(soggettoIdHmac);
        setSoggettoIdCifrato(soggettoIdCifrato);
        setEsposizioneAzienda(esposizioneAzienda);
        setEsposizioneAziendaComuneCod(esposizioneAziendaComuneCod);
        setEsposizioneAziendaComuneDesc(esposizioneAziendaComuneDesc);
        setEsposizioneAziendaCap(esposizioneAziendaCap);
        setEsposizioneAziendaProvincia(esposizioneAziendaProvincia);
        setEsposizioneMansione(esposizioneMansione);
        setEsposizioneInizio(esposizioneInizio);
        setEsposizioneFine(esposizioneFine);
        setFonteId(fonteId);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
