/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTNota;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Note testuali libere associate alla pratica del registro.  Fonte: PDF
 * Specifica Database, citata in Pagina 6 ("Note") e diagramma Pagina 11
 * ("Nota_registro").
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTNotaRecord extends UpdatableRecordImpl<ReeaTNotaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_nota.nota_id</code>.
     */
    public void setNotaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.nota_id</code>.
     */
    public Integer getNotaId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_nota.registro_id</code>.
     */
    public void setRegistroId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.registro_id</code>.
     */
    public Integer getRegistroId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_nota.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_nota.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_nota.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_nota.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_nota.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_nota.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_nota.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_nota.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_nota.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_nota.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTNotaRecord
     */
    public ReeaTNotaRecord() {
        super(ReeaTNota.REEA_T_NOTA);
    }

    /**
     * Create a detached, initialised ReeaTNotaRecord
     */
    public ReeaTNotaRecord(Integer notaId, Integer registroId, String descrizione, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaTNota.REEA_T_NOTA);

        setNotaId(notaId);
        setRegistroId(registroId);
        setDescrizione(descrizione);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
