/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDNazione;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDNazioneRecord extends UpdatableRecordImpl<ReeaDNazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_id</code>.
     */
    public void setNazioneId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_id</code>.
     */
    public Integer getNazioneId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_istat_cod</code>.
     */
    public void setNazioneIstatCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_istat_cod</code>.
     */
    public String getNazioneIstatCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_min_cod</code>.
     */
    public void setNazioneMinCod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_min_cod</code>.
     */
    public String getNazioneMinCod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_at_cod</code>.
     */
    public void setNazioneAtCod(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_at_cod</code>.
     */
    public String getNazioneAtCod() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_unsd_m49_cod</code>.
     */
    public void setNazioneUnsdM49Cod(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_unsd_m49_cod</code>.
     */
    public String getNazioneUnsdM49Cod() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_iso3661_alpha2_cod</code>.
     */
    public void setNazioneIso3661Alpha2Cod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_iso3661_alpha2_cod</code>.
     */
    public String getNazioneIso3661Alpha2Cod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_iso3661_alpha3_cod</code>.
     */
    public void setNazioneIso3661Alpha3Cod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_iso3661_alpha3_cod</code>.
     */
    public String getNazioneIso3661Alpha3Cod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_desc</code>.
     */
    public void setNazioneDesc(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_desc</code>.
     */
    public String getNazioneDesc() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_desc_en</code>.
     */
    public void setNazioneDescEn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_desc_en</code>.
     */
    public String getNazioneDescEn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.nazione_desc_it</code>.
     */
    public void setNazioneDescIt(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.nazione_desc_it</code>.
     */
    public String getNazioneDescIt() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.area_cod</code>.
     */
    public void setAreaCod(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.area_cod</code>.
     */
    public String getAreaCod() {
        return (String) get(10);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.area_desc_it</code>.
     */
    public void setAreaDescIt(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.area_desc_it</code>.
     */
    public String getAreaDescIt() {
        return (String) get(11);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.continente_cod</code>.
     */
    public void setContinenteCod(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.continente_cod</code>.
     */
    public String getContinenteCod() {
        return (String) get(12);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.continente_desc_it</code>.
     */
    public void setContinenteDescIt(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.continente_desc_it</code>.
     */
    public String getContinenteDescIt() {
        return (String) get(13);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(19);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(20);
    }

    /**
     * Setter for <code>reea.reea_d_nazione.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>reea.reea_d_nazione.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDNazioneRecord
     */
    public ReeaDNazioneRecord() {
        super(ReeaDNazione.REEA_D_NAZIONE);
    }

    /**
     * Create a detached, initialised ReeaDNazioneRecord
     */
    public ReeaDNazioneRecord(Integer nazioneId, String nazioneIstatCod, String nazioneMinCod, String nazioneAtCod, String nazioneUnsdM49Cod, String nazioneIso3661Alpha2Cod, String nazioneIso3661Alpha3Cod, String nazioneDesc, String nazioneDescEn, String nazioneDescIt, String areaCod, String areaDescIt, String continenteCod, String continenteDescIt, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDNazione.REEA_D_NAZIONE);

        setNazioneId(nazioneId);
        setNazioneIstatCod(nazioneIstatCod);
        setNazioneMinCod(nazioneMinCod);
        setNazioneAtCod(nazioneAtCod);
        setNazioneUnsdM49Cod(nazioneUnsdM49Cod);
        setNazioneIso3661Alpha2Cod(nazioneIso3661Alpha2Cod);
        setNazioneIso3661Alpha3Cod(nazioneIso3661Alpha3Cod);
        setNazioneDesc(nazioneDesc);
        setNazioneDescEn(nazioneDescEn);
        setNazioneDescIt(nazioneDescIt);
        setAreaCod(areaCod);
        setAreaDescIt(areaDescIt);
        setContinenteCod(continenteCod);
        setContinenteDescIt(continenteDescIt);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
