/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaTRegistro;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
 * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
 * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica Database,
 * Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTRegistroRecord extends UpdatableRecordImpl<ReeaTRegistroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_t_registro.registro_id</code>.
     */
    public void setRegistroId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.registro_id</code>.
     */
    public Integer getRegistroId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_t_registro.soggetto_id_hmac</code>. COLLATE
     * "C"
     */
    public void setSoggettoIdHmac(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.soggetto_id_hmac</code>. COLLATE
     * "C"
     */
    public String getSoggettoIdHmac() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_t_registro.soggetto_id_cifrato</code>.
     */
    public void setSoggettoIdCifrato(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.soggetto_id_cifrato</code>.
     */
    public byte[] getSoggettoIdCifrato() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>reea.reea_t_registro.att_sanitaria_stato</code>.
     */
    public void setAttSanitariaStato(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.att_sanitaria_stato</code>.
     */
    public Boolean getAttSanitariaStato() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>reea.reea_t_registro.att_sanitaria_spresal</code>.
     */
    public void setAttSanitariaSpresal(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.att_sanitaria_spresal</code>.
     */
    public Boolean getAttSanitariaSpresal() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>reea.reea_t_registro.att_sanitaria_spresal_data</code>.
     */
    public void setAttSanitariaSpresalData(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.att_sanitaria_spresal_data</code>.
     */
    public LocalDate getAttSanitariaSpresalData() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>reea.reea_t_registro.att_sanitaria_inail</code>.
     */
    public void setAttSanitariaInail(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.att_sanitaria_inail</code>.
     */
    public Boolean getAttSanitariaInail() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>reea.reea_t_registro.att_sanitaria_inail_data</code>.
     */
    public void setAttSanitariaInailData(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.att_sanitaria_inail_data</code>.
     */
    public LocalDate getAttSanitariaInailData() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>reea.reea_t_registro.sezione</code>. Prima, Seconda,
     * Terza
     */
    public void setSezione(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.sezione</code>. Prima, Seconda,
     * Terza
     */
    public Integer getSezione() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>reea.reea_t_registro.inserito_in_sorveglianza</code>.
     */
    public void setInseritoInSorveglianza(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.inserito_in_sorveglianza</code>.
     */
    public Boolean getInseritoInSorveglianza() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>reea.reea_t_registro.versione_numero</code>. versione
     * corrente
     */
    public void setVersioneNumero(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.versione_numero</code>. versione
     * corrente
     */
    public Integer getVersioneNumero() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>reea.reea_t_registro.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>reea.reea_t_registro.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>reea.reea_t_registro.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>reea.reea_t_registro.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>reea.reea_t_registro.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>reea.reea_t_registro.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(16);
    }

    /**
     * Setter for <code>reea.reea_t_registro.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(17);
    }

    /**
     * Setter for <code>reea.reea_t_registro.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(18);
    }

    /**
     * Setter for <code>reea.reea_t_registro.tipo_elenco_inail</code>. A o B
     */
    public void setTipoElencoInail(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>reea.reea_t_registro.tipo_elenco_inail</code>. A o B
     */
    public String getTipoElencoInail() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaTRegistroRecord
     */
    public ReeaTRegistroRecord() {
        super(ReeaTRegistro.REEA_T_REGISTRO);
    }

    /**
     * Create a detached, initialised ReeaTRegistroRecord
     */
    public ReeaTRegistroRecord(Integer registroId, String soggettoIdHmac, byte[] soggettoIdCifrato, Boolean attSanitariaStato, Boolean attSanitariaSpresal, LocalDate attSanitariaSpresalData, Boolean attSanitariaInail, LocalDate attSanitariaInailData, Integer sezione, Boolean inseritoInSorveglianza, Integer versioneNumero, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione, String tipoElencoInail) {
        super(ReeaTRegistro.REEA_T_REGISTRO);

        setRegistroId(registroId);
        setSoggettoIdHmac(soggettoIdHmac);
        setSoggettoIdCifrato(soggettoIdCifrato);
        setAttSanitariaStato(attSanitariaStato);
        setAttSanitariaSpresal(attSanitariaSpresal);
        setAttSanitariaSpresalData(attSanitariaSpresalData);
        setAttSanitariaInail(attSanitariaInail);
        setAttSanitariaInailData(attSanitariaInailData);
        setSezione(sezione);
        setInseritoInSorveglianza(inseritoInSorveglianza);
        setVersioneNumero(versioneNumero);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        setTipoElencoInail(tipoElencoInail);
        resetChangedOnNotNull();
    }
}
