/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables.records;


import it.csi.registry.jooq.tables.ReeaDRuolo;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Ruoli assegnabili agli utenti (es. Medico competente, Amministrativo). 
 * Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_RUOLO.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRuoloRecord extends UpdatableRecordImpl<ReeaDRuoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reea.reea_d_ruolo.ruolo_id</code>.
     */
    public void setRuoloId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.ruolo_id</code>.
     */
    public Integer getRuoloId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.ruolo_cod</code>.
     */
    public void setRuoloCod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.ruolo_cod</code>.
     */
    public String getRuoloCod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.ruolo_desc</code>.
     */
    public void setRuoloDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.ruolo_desc</code>.
     */
    public String getRuoloDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.validita_inizio</code>.
     */
    public void setValiditaInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.validita_inizio</code>.
     */
    public LocalDateTime getValiditaInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.validita_fine</code>.
     */
    public void setValiditaFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.validita_fine</code>.
     */
    public LocalDateTime getValiditaFine() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.data_creazione</code>.
     */
    public void setDataCreazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.data_creazione</code>.
     */
    public LocalDateTime getDataCreazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.data_modifica</code>.
     */
    public void setDataModifica(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.data_modifica</code>.
     */
    public LocalDateTime getDataModifica() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.data_cancellazione</code>.
     */
    public void setDataCancellazione(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.data_cancellazione</code>.
     */
    public LocalDateTime getDataCancellazione() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.utente_creazione</code>.
     */
    public void setUtenteCreazione(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.utente_creazione</code>.
     */
    public String getUtenteCreazione() {
        return (String) get(8);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.utente_modifica</code>.
     */
    public void setUtenteModifica(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.utente_modifica</code>.
     */
    public String getUtenteModifica() {
        return (String) get(9);
    }

    /**
     * Setter for <code>reea.reea_d_ruolo.utente_cancellazione</code>.
     */
    public void setUtenteCancellazione(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>reea.reea_d_ruolo.utente_cancellazione</code>.
     */
    public String getUtenteCancellazione() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReeaDRuoloRecord
     */
    public ReeaDRuoloRecord() {
        super(ReeaDRuolo.REEA_D_RUOLO);
    }

    /**
     * Create a detached, initialised ReeaDRuoloRecord
     */
    public ReeaDRuoloRecord(Integer ruoloId, String ruoloCod, String ruoloDesc, LocalDateTime validitaInizio, LocalDateTime validitaFine, LocalDateTime dataCreazione, LocalDateTime dataModifica, LocalDateTime dataCancellazione, String utenteCreazione, String utenteModifica, String utenteCancellazione) {
        super(ReeaDRuolo.REEA_D_RUOLO);

        setRuoloId(ruoloId);
        setRuoloCod(ruoloCod);
        setRuoloDesc(ruoloDesc);
        setValiditaInizio(validitaInizio);
        setValiditaFine(validitaFine);
        setDataCreazione(dataCreazione);
        setDataModifica(dataModifica);
        setDataCancellazione(dataCancellazione);
        setUtenteCreazione(utenteCreazione);
        setUtenteModifica(utenteModifica);
        setUtenteCancellazione(utenteCancellazione);
        resetChangedOnNotNull();
    }
}
