/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.routines;


import it.csi.registry.jooq.Reea;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HmacSoggettoId extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>reea.hmac_soggetto_id.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>reea.hmac_soggetto_id.p_soggetto_id</code>.
     */
    public static final Parameter<Integer> P_SOGGETTO_ID = Internal.createParameter("p_soggetto_id", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>reea.hmac_soggetto_id.p_key</code>.
     */
    public static final Parameter<String> P_KEY = Internal.createParameter("p_key", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public HmacSoggettoId() {
        super("hmac_soggetto_id", Reea.REEA, SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_SOGGETTO_ID);
        addInParameter(P_KEY);
    }

    /**
     * Set the <code>p_soggetto_id</code> parameter IN value to the routine
     */
    public void setPSoggettoId(Integer value) {
        setValue(P_SOGGETTO_ID, value);
    }

    /**
     * Set the <code>p_soggetto_id</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setPSoggettoId(Field<Integer> field) {
        setField(P_SOGGETTO_ID, field);
    }

    /**
     * Set the <code>p_key</code> parameter IN value to the routine
     */
    public void setPKey(String value) {
        setValue(P_KEY, value);
    }

    /**
     * Set the <code>p_key</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setPKey(Field<String> field) {
        setField(P_KEY, field);
    }
}
