/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.routines;


import it.csi.registry.jooq.Reea;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TextToHmac extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>reea.text_to_hmac.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>reea.text_to_hmac.text_to_hmac</code>.
     */
    public static final Parameter<String> TEXT_TO_HMAC = Internal.createParameter("text_to_hmac", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>reea.text_to_hmac.hmac_text</code>.
     */
    public static final Parameter<String> HMAC_TEXT = Internal.createParameter("hmac_text", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public TextToHmac() {
        super("text_to_hmac", Reea.REEA, SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TEXT_TO_HMAC);
        addInParameter(HMAC_TEXT);
    }

    /**
     * Set the <code>text_to_hmac</code> parameter IN value to the routine
     */
    public void setTextToHmac(String value) {
        setValue(TEXT_TO_HMAC, value);
    }

    /**
     * Set the <code>text_to_hmac</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setTextToHmac(Field<String> field) {
        setField(TEXT_TO_HMAC, field);
    }

    /**
     * Set the <code>hmac_text</code> parameter IN value to the routine
     */
    public void setHmacText(String value) {
        setValue(HMAC_TEXT, value);
    }

    /**
     * Set the <code>hmac_text</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setHmacText(Field<String> field) {
        setField(HMAC_TEXT, field);
    }
}
