/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq;


import it.csi.registry.jooq.tables.CsiLogAudit;
import it.csi.registry.jooq.tables.ReaTSoggettoPoc;
import it.csi.registry.jooq.tables.ReeaCParametro;
import it.csi.registry.jooq.tables.ReeaCParametroTipo;
import it.csi.registry.jooq.tables.ReeaDAsl;
import it.csi.registry.jooq.tables.ReeaDAttestazioneSanitariaStato;
import it.csi.registry.jooq.tables.ReeaDAzienda;
import it.csi.registry.jooq.tables.ReeaDCampoMascherato;
import it.csi.registry.jooq.tables.ReeaDComune;
import it.csi.registry.jooq.tables.ReeaDEsenzione;
import it.csi.registry.jooq.tables.ReeaDFileOperazioneTipo;
import it.csi.registry.jooq.tables.ReeaDFileStato;
import it.csi.registry.jooq.tables.ReeaDFonte;
import it.csi.registry.jooq.tables.ReeaDGruppoFunzionalita;
import it.csi.registry.jooq.tables.ReeaDInserimentoTipo;
import it.csi.registry.jooq.tables.ReeaDNazione;
import it.csi.registry.jooq.tables.ReeaDProfilo;
import it.csi.registry.jooq.tables.ReeaDProfiloTipo;
import it.csi.registry.jooq.tables.ReeaDProvincia;
import it.csi.registry.jooq.tables.ReeaDRegione;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiMansione;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiRagionesociale;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiSettore;
import it.csi.registry.jooq.tables.ReeaDRuolo;
import it.csi.registry.jooq.tables.ReeaDSoggettoStato;
import it.csi.registry.jooq.tables.ReeaLFileElaborazione;
import it.csi.registry.jooq.tables.ReeaLFileElaborazioneErrore;
import it.csi.registry.jooq.tables.ReeaLFileScaricoErrore;
import it.csi.registry.jooq.tables.ReeaRProfiloCampoMascherato;
import it.csi.registry.jooq.tables.ReeaRProfiloFunzionalita;
import it.csi.registry.jooq.tables.ReeaRRuoloProfilo;
import it.csi.registry.jooq.tables.ReeaRSoggettoEsenzione;
import it.csi.registry.jooq.tables.ReeaRUtenteCollocazione;
import it.csi.registry.jooq.tables.ReeaRUtenteProfilo;
import it.csi.registry.jooq.tables.ReeaRUtenteRuolo;
import it.csi.registry.jooq.tables.ReeaSSoggetto;
import it.csi.registry.jooq.tables.ReeaTAdesione;
import it.csi.registry.jooq.tables.ReeaTCollocazione;
import it.csi.registry.jooq.tables.ReeaTEsposizione;
import it.csi.registry.jooq.tables.ReeaTFile;
import it.csi.registry.jooq.tables.ReeaTFileImpatto;
import it.csi.registry.jooq.tables.ReeaTFunzionalita;
import it.csi.registry.jooq.tables.ReeaTNota;
import it.csi.registry.jooq.tables.ReeaTRegistro;
import it.csi.registry.jooq.tables.ReeaTRegistroInail;
import it.csi.registry.jooq.tables.ReeaTRegistroPdlAmianto;
import it.csi.registry.jooq.tables.ReeaTRegistroSnapshot;
import it.csi.registry.jooq.tables.ReeaTRegistroSpresalAnamnesi;
import it.csi.registry.jooq.tables.ReeaTRegistroSpresalEsiti;
import it.csi.registry.jooq.tables.ReeaTSoggetto;
import it.csi.registry.jooq.tables.ReeaTUtente;
import it.csi.registry.jooq.tables.records.CsiLogAuditRecord;
import it.csi.registry.jooq.tables.records.ReaTSoggettoPocRecord;
import it.csi.registry.jooq.tables.records.ReeaCParametroRecord;
import it.csi.registry.jooq.tables.records.ReeaCParametroTipoRecord;
import it.csi.registry.jooq.tables.records.ReeaDAslRecord;
import it.csi.registry.jooq.tables.records.ReeaDAttestazioneSanitariaStatoRecord;
import it.csi.registry.jooq.tables.records.ReeaDAziendaRecord;
import it.csi.registry.jooq.tables.records.ReeaDCampoMascheratoRecord;
import it.csi.registry.jooq.tables.records.ReeaDComuneRecord;
import it.csi.registry.jooq.tables.records.ReeaDEsenzioneRecord;
import it.csi.registry.jooq.tables.records.ReeaDFileOperazioneTipoRecord;
import it.csi.registry.jooq.tables.records.ReeaDFileStatoRecord;
import it.csi.registry.jooq.tables.records.ReeaDFonteRecord;
import it.csi.registry.jooq.tables.records.ReeaDGruppoFunzionalitaRecord;
import it.csi.registry.jooq.tables.records.ReeaDInserimentoTipoRecord;
import it.csi.registry.jooq.tables.records.ReeaDNazioneRecord;
import it.csi.registry.jooq.tables.records.ReeaDProfiloRecord;
import it.csi.registry.jooq.tables.records.ReeaDProfiloTipoRecord;
import it.csi.registry.jooq.tables.records.ReeaDProvinciaRecord;
import it.csi.registry.jooq.tables.records.ReeaDRegioneRecord;
import it.csi.registry.jooq.tables.records.ReeaDRegistroSpresalAnamnesiMansioneRecord;
import it.csi.registry.jooq.tables.records.ReeaDRegistroSpresalAnamnesiRagionesocialeRecord;
import it.csi.registry.jooq.tables.records.ReeaDRegistroSpresalAnamnesiSettoreRecord;
import it.csi.registry.jooq.tables.records.ReeaDRuoloRecord;
import it.csi.registry.jooq.tables.records.ReeaDSoggettoStatoRecord;
import it.csi.registry.jooq.tables.records.ReeaLFileElaborazioneErroreRecord;
import it.csi.registry.jooq.tables.records.ReeaLFileElaborazioneRecord;
import it.csi.registry.jooq.tables.records.ReeaLFileScaricoErroreRecord;
import it.csi.registry.jooq.tables.records.ReeaRProfiloCampoMascheratoRecord;
import it.csi.registry.jooq.tables.records.ReeaRProfiloFunzionalitaRecord;
import it.csi.registry.jooq.tables.records.ReeaRRuoloProfiloRecord;
import it.csi.registry.jooq.tables.records.ReeaRSoggettoEsenzioneRecord;
import it.csi.registry.jooq.tables.records.ReeaRUtenteCollocazioneRecord;
import it.csi.registry.jooq.tables.records.ReeaRUtenteProfiloRecord;
import it.csi.registry.jooq.tables.records.ReeaRUtenteRuoloRecord;
import it.csi.registry.jooq.tables.records.ReeaSSoggettoRecord;
import it.csi.registry.jooq.tables.records.ReeaTAdesioneRecord;
import it.csi.registry.jooq.tables.records.ReeaTCollocazioneRecord;
import it.csi.registry.jooq.tables.records.ReeaTEsposizioneRecord;
import it.csi.registry.jooq.tables.records.ReeaTFileImpattoRecord;
import it.csi.registry.jooq.tables.records.ReeaTFileRecord;
import it.csi.registry.jooq.tables.records.ReeaTFunzionalitaRecord;
import it.csi.registry.jooq.tables.records.ReeaTNotaRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroInailRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroPdlAmiantoRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroSnapshotRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroSpresalAnamnesiRecord;
import it.csi.registry.jooq.tables.records.ReeaTRegistroSpresalEsitiRecord;
import it.csi.registry.jooq.tables.records.ReeaTSoggettoRecord;
import it.csi.registry.jooq.tables.records.ReeaTUtenteRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * reea.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CsiLogAuditRecord> CSI_LOG_AUDIT_PKEY = Internal.createUniqueKey(CsiLogAudit.CSI_LOG_AUDIT, DSL.name("csi_log_audit_pkey"), new TableField[] { CsiLogAudit.CSI_LOG_AUDIT.AUDIT_ID }, true);
    public static final UniqueKey<ReaTSoggettoPocRecord> REA_T_SOGGETTO_POC_PKEY = Internal.createUniqueKey(ReaTSoggettoPoc.REA_T_SOGGETTO_POC, DSL.name("rea_t_soggetto_poc_pkey"), new TableField[] { ReaTSoggettoPoc.REA_T_SOGGETTO_POC.SOGGETTO_ID }, true);
    public static final UniqueKey<ReeaCParametroRecord> REEA_C_PARAMETRO_PKEY = Internal.createUniqueKey(ReeaCParametro.REEA_C_PARAMETRO, DSL.name("reea_c_parametro_pkey"), new TableField[] { ReeaCParametro.REEA_C_PARAMETRO.PARAMETRO_ID }, true);
    public static final UniqueKey<ReeaCParametroTipoRecord> REEA_C_PARAMETRO_TIPO_PKEY = Internal.createUniqueKey(ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO, DSL.name("reea_c_parametro_tipo_pkey"), new TableField[] { ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO.PARAMETRO_TIPO_ID }, true);
    public static final UniqueKey<ReeaDAslRecord> REEA_D_ASL_PKEY = Internal.createUniqueKey(ReeaDAsl.REEA_D_ASL, DSL.name("reea_d_asl_pkey"), new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final UniqueKey<ReeaDAttestazioneSanitariaStatoRecord> REEA_D_ATTESTAZIONE_SANITARIA_STATO_PKEY = Internal.createUniqueKey(ReeaDAttestazioneSanitariaStato.REEA_D_ATTESTAZIONE_SANITARIA_STATO, DSL.name("reea_d_attestazione_sanitaria_stato_pkey"), new TableField[] { ReeaDAttestazioneSanitariaStato.REEA_D_ATTESTAZIONE_SANITARIA_STATO.ATT_SANITARIA_STATO_ID }, true);
    public static final UniqueKey<ReeaDAziendaRecord> REEA_D_AZIENDA_PKEY = Internal.createUniqueKey(ReeaDAzienda.REEA_D_AZIENDA, DSL.name("reea_d_azienda_pkey"), new TableField[] { ReeaDAzienda.REEA_D_AZIENDA.AZIENDA_ID }, true);
    public static final UniqueKey<ReeaDCampoMascheratoRecord> REEA_D_CAMPO_MASCHERATO_PKEY = Internal.createUniqueKey(ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO, DSL.name("reea_d_campo_mascherato_pkey"), new TableField[] { ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO.CAMPO_MASCHERATO_ID }, true);
    public static final UniqueKey<ReeaDComuneRecord> REEA_D_COMUNE_PKEY = Internal.createUniqueKey(ReeaDComune.REEA_D_COMUNE, DSL.name("reea_d_comune_pkey"), new TableField[] { ReeaDComune.REEA_D_COMUNE.COMUNE_ID }, true);
    public static final UniqueKey<ReeaDEsenzioneRecord> REEA_D_ESENZIONE_PKEY = Internal.createUniqueKey(ReeaDEsenzione.REEA_D_ESENZIONE, DSL.name("reea_d_esenzione_pkey"), new TableField[] { ReeaDEsenzione.REEA_D_ESENZIONE.ESENZIONE_ID }, true);
    public static final UniqueKey<ReeaDFileOperazioneTipoRecord> REEA_D_FILE_OPERAZIONE_TIPO_PKEY = Internal.createUniqueKey(ReeaDFileOperazioneTipo.REEA_D_FILE_OPERAZIONE_TIPO, DSL.name("reea_d_file_operazione_tipo_pkey"), new TableField[] { ReeaDFileOperazioneTipo.REEA_D_FILE_OPERAZIONE_TIPO.OPERAZIONE_TIPO_ID }, true);
    public static final UniqueKey<ReeaDFileStatoRecord> REEA_D_FILE_STATO_PKEY = Internal.createUniqueKey(ReeaDFileStato.REEA_D_FILE_STATO, DSL.name("reea_d_file_stato_pkey"), new TableField[] { ReeaDFileStato.REEA_D_FILE_STATO.FILE_STATO_ID }, true);
    public static final UniqueKey<ReeaDFonteRecord> REEA_D_FONTE_PKEY = Internal.createUniqueKey(ReeaDFonte.REEA_D_FONTE, DSL.name("reea_d_fonte_pkey"), new TableField[] { ReeaDFonte.REEA_D_FONTE.FONTE_ID }, true);
    public static final UniqueKey<ReeaDGruppoFunzionalitaRecord> REEA_D_GRUPPO_FUNZIONALITA_PKEY = Internal.createUniqueKey(ReeaDGruppoFunzionalita.REEA_D_GRUPPO_FUNZIONALITA, DSL.name("reea_d_gruppo_funzionalita_pkey"), new TableField[] { ReeaDGruppoFunzionalita.REEA_D_GRUPPO_FUNZIONALITA.GRUPPO_FUNZIONALITA_ID }, true);
    public static final UniqueKey<ReeaDInserimentoTipoRecord> REEA_D_INSERIMENTO_TIPO_PKEY = Internal.createUniqueKey(ReeaDInserimentoTipo.REEA_D_INSERIMENTO_TIPO, DSL.name("reea_d_inserimento_tipo_pkey"), new TableField[] { ReeaDInserimentoTipo.REEA_D_INSERIMENTO_TIPO.INSERIMENTO_TIPO_ID }, true);
    public static final UniqueKey<ReeaDNazioneRecord> REEA_D_NAZIONE_PKEY = Internal.createUniqueKey(ReeaDNazione.REEA_D_NAZIONE, DSL.name("reea_d_nazione_pkey"), new TableField[] { ReeaDNazione.REEA_D_NAZIONE.NAZIONE_ID }, true);
    public static final UniqueKey<ReeaDProfiloRecord> REEA_D_PROFILO_PKEY = Internal.createUniqueKey(ReeaDProfilo.REEA_D_PROFILO, DSL.name("reea_d_profilo_pkey"), new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_ID }, true);
    public static final UniqueKey<ReeaDProfiloTipoRecord> REEA_D_PROFILO_TIPO_PKEY = Internal.createUniqueKey(ReeaDProfiloTipo.REEA_D_PROFILO_TIPO, DSL.name("reea_d_profilo_tipo_pkey"), new TableField[] { ReeaDProfiloTipo.REEA_D_PROFILO_TIPO.PROFILO_TIPO_ID }, true);
    public static final UniqueKey<ReeaDProvinciaRecord> REEA_D_PROVINCIA_PKEY = Internal.createUniqueKey(ReeaDProvincia.REEA_D_PROVINCIA, DSL.name("reea_d_provincia_pkey"), new TableField[] { ReeaDProvincia.REEA_D_PROVINCIA.PROVINCIA_ID }, true);
    public static final UniqueKey<ReeaDRegioneRecord> REEA_D_REGIONE_PKEY = Internal.createUniqueKey(ReeaDRegione.REEA_D_REGIONE, DSL.name("reea_d_regione_pkey"), new TableField[] { ReeaDRegione.REEA_D_REGIONE.REGIONE_ID }, true);
    public static final UniqueKey<ReeaDRegistroSpresalAnamnesiMansioneRecord> REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE_PKEY = Internal.createUniqueKey(ReeaDRegistroSpresalAnamnesiMansione.REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE, DSL.name("reea_d_registro_spresal_anamnesi_mansione_pkey"), new TableField[] { ReeaDRegistroSpresalAnamnesiMansione.REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE.MANSIONE_ID }, true);
    public static final UniqueKey<ReeaDRegistroSpresalAnamnesiRagionesocialeRecord> REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE_PKEY = Internal.createUniqueKey(ReeaDRegistroSpresalAnamnesiRagionesociale.REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE, DSL.name("reea_d_registro_spresal_anamnesi_ragionesociale_pkey"), new TableField[] { ReeaDRegistroSpresalAnamnesiRagionesociale.REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE.RAGIONESOCIALE_ID }, true);
    public static final UniqueKey<ReeaDRegistroSpresalAnamnesiSettoreRecord> REEA_D_REGISTRO_SPRESAL_ANAMNESI_SETTORE_PKEY = Internal.createUniqueKey(ReeaDRegistroSpresalAnamnesiSettore.REEA_D_REGISTRO_SPRESAL_ANAMNESI_SETTORE, DSL.name("reea_d_registro_spresal_anamnesi_settore_pkey"), new TableField[] { ReeaDRegistroSpresalAnamnesiSettore.REEA_D_REGISTRO_SPRESAL_ANAMNESI_SETTORE.SETTORE_ID }, true);
    public static final UniqueKey<ReeaDRuoloRecord> REEA_D_RUOLO_PKEY = Internal.createUniqueKey(ReeaDRuolo.REEA_D_RUOLO, DSL.name("reea_d_ruolo_pkey"), new TableField[] { ReeaDRuolo.REEA_D_RUOLO.RUOLO_ID }, true);
    public static final UniqueKey<ReeaDSoggettoStatoRecord> REEA_D_SOGGETTO_STATO_PKEY = Internal.createUniqueKey(ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO, DSL.name("reea_d_soggetto_stato_pkey"), new TableField[] { ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO.SOGGETTO_STATO_ID }, true);
    public static final UniqueKey<ReeaLFileElaborazioneRecord> REEA_L_FILE_ELABORAZIONE_PKEY = Internal.createUniqueKey(ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE, DSL.name("reea_l_file_elaborazione_pkey"), new TableField[] { ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE.ELABORAZIONE_ID }, true);
    public static final UniqueKey<ReeaLFileElaborazioneErroreRecord> REEA_L_FILE_ELABORAZIONE_ERRORE_PKEY = Internal.createUniqueKey(ReeaLFileElaborazioneErrore.REEA_L_FILE_ELABORAZIONE_ERRORE, DSL.name("reea_l_file_elaborazione_errore_pkey"), new TableField[] { ReeaLFileElaborazioneErrore.REEA_L_FILE_ELABORAZIONE_ERRORE.ELABORAZIONE_ERRORE_ID }, true);
    public static final UniqueKey<ReeaLFileScaricoErroreRecord> REEA_L_FILE_SCARICO_ERRORE_PKEY = Internal.createUniqueKey(ReeaLFileScaricoErrore.REEA_L_FILE_SCARICO_ERRORE, DSL.name("reea_l_file_scarico_errore_pkey"), new TableField[] { ReeaLFileScaricoErrore.REEA_L_FILE_SCARICO_ERRORE.FILE_ERRORE_ID }, true);
    public static final UniqueKey<ReeaRProfiloCampoMascheratoRecord> REEA_R_PROFILO_CAMPO_MASCHERATO_PKEY_1 = Internal.createUniqueKey(ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO, DSL.name("reea_r_profilo_campo_mascherato_pkey_1"), new TableField[] { ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO.PROFILO_CAMPO_MASCHERATO_ID }, true);
    public static final UniqueKey<ReeaRProfiloFunzionalitaRecord> REEA_R_PROFILO_FUNZIONALITA_PKEY = Internal.createUniqueKey(ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA, DSL.name("reea_r_profilo_funzionalita_pkey"), new TableField[] { ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA.PROFILO_FUNZIONALITA_ID }, true);
    public static final UniqueKey<ReeaRRuoloProfiloRecord> REEA_R_RUOLO_PROFILO_PKEY = Internal.createUniqueKey(ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO, DSL.name("reea_r_ruolo_profilo_pkey"), new TableField[] { ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO.RUOLO_PROFILO_ID }, true);
    public static final UniqueKey<ReeaRSoggettoEsenzioneRecord> REEA_R_SOGGETTO_ESENZIONE_PKEY = Internal.createUniqueKey(ReeaRSoggettoEsenzione.REEA_R_SOGGETTO_ESENZIONE, DSL.name("reea_r_soggetto_esenzione_pkey"), new TableField[] { ReeaRSoggettoEsenzione.REEA_R_SOGGETTO_ESENZIONE.SOGGETTO_ESENZIONE_ID }, true);
    public static final UniqueKey<ReeaRUtenteCollocazioneRecord> REEA_R_UTENTE_COLLOCAZIONE_PKEY = Internal.createUniqueKey(ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE, DSL.name("reea_r_utente_collocazione_pkey"), new TableField[] { ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE.UTENTE_RUOLO_ID }, true);
    public static final UniqueKey<ReeaRUtenteProfiloRecord> REEA_R_UTENTE_PROFILO_PKEY = Internal.createUniqueKey(ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO, DSL.name("reea_r_utente_profilo_pkey"), new TableField[] { ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO.UTENTE_PROFILO_ID }, true);
    public static final UniqueKey<ReeaRUtenteRuoloRecord> REEA_R_UTENTE_RUOLO_PKEY = Internal.createUniqueKey(ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO, DSL.name("reea_r_utente_ruolo_pkey"), new TableField[] { ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO.UTENTE_RUOLO_ID }, true);
    public static final UniqueKey<ReeaSSoggettoRecord> REEA_S_SOGGETTO_PKEY = Internal.createUniqueKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_s_soggetto_pkey"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.S_SOGGETTO_ID }, true);
    public static final UniqueKey<ReeaTAdesioneRecord> REEA_T_ADESIONE_PKEY = Internal.createUniqueKey(ReeaTAdesione.REEA_T_ADESIONE, DSL.name("reea_t_adesione_pkey"), new TableField[] { ReeaTAdesione.REEA_T_ADESIONE.ADESIONE_ID }, true);
    public static final UniqueKey<ReeaTCollocazioneRecord> REEA_T_COLLOCAZIONE_PKEY = Internal.createUniqueKey(ReeaTCollocazione.REEA_T_COLLOCAZIONE, DSL.name("reea_t_collocazione_pkey"), new TableField[] { ReeaTCollocazione.REEA_T_COLLOCAZIONE.COLLOCAZIONE_ID }, true);
    public static final UniqueKey<ReeaTEsposizioneRecord> REEA_T_ESPOSIZIONE_PKEY = Internal.createUniqueKey(ReeaTEsposizione.REEA_T_ESPOSIZIONE, DSL.name("reea_t_esposizione_pkey"), new TableField[] { ReeaTEsposizione.REEA_T_ESPOSIZIONE.ESPOSIZIONE_ID }, true);
    public static final UniqueKey<ReeaTFileRecord> REEA_T_FILE_PKEY = Internal.createUniqueKey(ReeaTFile.REEA_T_FILE, DSL.name("reea_t_file_pkey"), new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final UniqueKey<ReeaTFileImpattoRecord> REEA_T_FILE_IMPATTO_PKEY = Internal.createUniqueKey(ReeaTFileImpatto.REEA_T_FILE_IMPATTO, DSL.name("reea_t_file_impatto_pkey"), new TableField[] { ReeaTFileImpatto.REEA_T_FILE_IMPATTO.FILE_IMPATTO_ID }, true);
    public static final UniqueKey<ReeaTFunzionalitaRecord> REEA_T_FUNZIONALITA_PKEY = Internal.createUniqueKey(ReeaTFunzionalita.REEA_T_FUNZIONALITA, DSL.name("reea_t_funzionalita_pkey"), new TableField[] { ReeaTFunzionalita.REEA_T_FUNZIONALITA.FUNZIONALITA_ID }, true);
    public static final UniqueKey<ReeaTNotaRecord> REEA_T_NOTA_PKEY = Internal.createUniqueKey(ReeaTNota.REEA_T_NOTA, DSL.name("reea_t_nota_pkey"), new TableField[] { ReeaTNota.REEA_T_NOTA.NOTA_ID }, true);
    public static final UniqueKey<ReeaTRegistroRecord> REEA_T_REGISTRO_PKEY = Internal.createUniqueKey(ReeaTRegistro.REEA_T_REGISTRO, DSL.name("reea_t_registro_pkey"), new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final UniqueKey<ReeaTRegistroInailRecord> REEA_T_REGISTRO_INAIL_PKEY = Internal.createUniqueKey(ReeaTRegistroInail.REEA_T_REGISTRO_INAIL, DSL.name("reea_t_registro_inail_pkey"), new TableField[] { ReeaTRegistroInail.REEA_T_REGISTRO_INAIL.REG_INAIL_ID }, true);
    public static final UniqueKey<ReeaTRegistroPdlAmiantoRecord> REEA_T_REGISTRO_PDL_AMIANTO_PKEY = Internal.createUniqueKey(ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO, DSL.name("reea_t_registro_pdl_amianto_pkey"), new TableField[] { ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO.REG_PDL_AMIANTO_ID }, true);
    public static final UniqueKey<ReeaTRegistroSnapshotRecord> REEA_T_REGISTRO_SNAPSHOT_PKEY = Internal.createUniqueKey(ReeaTRegistroSnapshot.REEA_T_REGISTRO_SNAPSHOT, DSL.name("reea_t_registro_snapshot_pkey"), new TableField[] { ReeaTRegistroSnapshot.REEA_T_REGISTRO_SNAPSHOT.REGISTRO_SNAPSHOT_ID }, true);
    public static final UniqueKey<ReeaTRegistroSpresalAnamnesiRecord> REEA_T_REGISTRO_SPRESAL_ANAMNES_PKEY = Internal.createUniqueKey(ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI, DSL.name("reea_t_registro_spresal_anamnes_pkey"), new TableField[] { ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.REG_SPRESAL_ANAMNESI_ID }, true);
    public static final UniqueKey<ReeaTRegistroSpresalAnamnesiRecord> UQ_SPRESAL_ANAMNESI_ID_SPRESAL_OCC = Internal.createUniqueKey(ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI, DSL.name("uq_spresal_anamnesi_id_spresal_occ"), new TableField[] { ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.ID_SPRESAL, ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.OCCUPAZIONE_NUM, ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.VALIDITA_FINE }, true);
    public static final UniqueKey<ReeaTRegistroSpresalEsitiRecord> REEA_T_REGISTRO_SPRESAL_ESITI_PKEY = Internal.createUniqueKey(ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI, DSL.name("reea_t_registro_spresal_esiti_pkey"), new TableField[] { ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.REG_SPRESAL_ESITI_ID }, true);
    public static final UniqueKey<ReeaTRegistroSpresalEsitiRecord> UQ_SPRESAL_ESITI_CF_DATA_VISITA = Internal.createUniqueKey(ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI, DSL.name("uq_spresal_esiti_cf_data_visita"), new TableField[] { ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.CODICE_FISCALE, ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.DATA_VISITA, ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.VALIDITA_FINE }, true);
    public static final UniqueKey<ReeaTSoggettoRecord> REEA_T_SOGGETTO_PKEY = Internal.createUniqueKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_t_soggetto_pkey"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.SOGGETTO_ID }, true);
    public static final UniqueKey<ReeaTUtenteRecord> REEA_T_UTENTE_PKEY = Internal.createUniqueKey(ReeaTUtente.REEA_T_UTENTE, DSL.name("reea_t_utente_pkey"), new TableField[] { ReeaTUtente.REEA_T_UTENTE.UTENTE_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ReeaCParametroRecord, ReeaCParametroTipoRecord> REEA_C_PARAMETRO__REEA_C_PARAMETRO_TIPO_REEA_C_PARAMETRO = Internal.createForeignKey(ReeaCParametro.REEA_C_PARAMETRO, DSL.name("reea_c_parametro_tipo_reea_c_parametro"), new TableField[] { ReeaCParametro.REEA_C_PARAMETRO.PARAMETRO_TIPO_ID }, Keys.REEA_C_PARAMETRO_TIPO_PKEY, new TableField[] { ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO.PARAMETRO_TIPO_ID }, true);
    public static final ForeignKey<ReeaDComuneRecord, ReeaDProvinciaRecord> REEA_D_COMUNE__REEA_D_PROVINCIA_REEA_D_COMUNE = Internal.createForeignKey(ReeaDComune.REEA_D_COMUNE, DSL.name("reea_d_provincia_reea_d_comune"), new TableField[] { ReeaDComune.REEA_D_COMUNE.PROVINCIA_ID }, Keys.REEA_D_PROVINCIA_PKEY, new TableField[] { ReeaDProvincia.REEA_D_PROVINCIA.PROVINCIA_ID }, true);
    public static final ForeignKey<ReeaDProfiloRecord, ReeaDProfiloTipoRecord> REEA_D_PROFILO__REEA_D_PROFILO_TIPO_REEA_C_PARAMETRO = Internal.createForeignKey(ReeaDProfilo.REEA_D_PROFILO, DSL.name("reea_d_profilo_tipo_reea_c_parametro"), new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_TIPO_ID }, Keys.REEA_D_PROFILO_TIPO_PKEY, new TableField[] { ReeaDProfiloTipo.REEA_D_PROFILO_TIPO.PROFILO_TIPO_ID }, true);
    public static final ForeignKey<ReeaDProvinciaRecord, ReeaDRegioneRecord> REEA_D_PROVINCIA__REEA_D_REGIONE_REEA_D_PROVINCIA = Internal.createForeignKey(ReeaDProvincia.REEA_D_PROVINCIA, DSL.name("reea_d_regione_reea_d_provincia"), new TableField[] { ReeaDProvincia.REEA_D_PROVINCIA.REGIONE_ID }, Keys.REEA_D_REGIONE_PKEY, new TableField[] { ReeaDRegione.REEA_D_REGIONE.REGIONE_ID }, true);
    public static final ForeignKey<ReeaDRegioneRecord, ReeaDNazioneRecord> REEA_D_REGIONE__REEA_D_NAZIONE_REEA_D_REGIONE = Internal.createForeignKey(ReeaDRegione.REEA_D_REGIONE, DSL.name("reea_d_nazione_reea_d_regione"), new TableField[] { ReeaDRegione.REEA_D_REGIONE.NAZIONE_ID }, Keys.REEA_D_NAZIONE_PKEY, new TableField[] { ReeaDNazione.REEA_D_NAZIONE.NAZIONE_ID }, true);
    public static final ForeignKey<ReeaLFileElaborazioneRecord, ReeaTFileRecord> REEA_L_FILE_ELABORAZIONE__FK_REEA_L_FILE_ELABORAZIONE_FILE = Internal.createForeignKey(ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE, DSL.name("fk_reea_l_file_elaborazione_file"), new TableField[] { ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaLFileElaborazioneRecord, ReeaDFileStatoRecord> REEA_L_FILE_ELABORAZIONE__FK_REEA_L_FILE_ELABORAZIONE_STATO = Internal.createForeignKey(ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE, DSL.name("fk_reea_l_file_elaborazione_stato"), new TableField[] { ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE.FILE_STATO_ID }, Keys.REEA_D_FILE_STATO_PKEY, new TableField[] { ReeaDFileStato.REEA_D_FILE_STATO.FILE_STATO_ID }, true);
    public static final ForeignKey<ReeaLFileElaborazioneErroreRecord, ReeaLFileElaborazioneRecord> REEA_L_FILE_ELABORAZIONE_ERRORE__FK_REEA_L_IMPORT_ERRORE_ELAB = Internal.createForeignKey(ReeaLFileElaborazioneErrore.REEA_L_FILE_ELABORAZIONE_ERRORE, DSL.name("fk_reea_l_import_errore_elab"), new TableField[] { ReeaLFileElaborazioneErrore.REEA_L_FILE_ELABORAZIONE_ERRORE.ELABORAZIONE_ID }, Keys.REEA_L_FILE_ELABORAZIONE_PKEY, new TableField[] { ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE.ELABORAZIONE_ID }, true);
    public static final ForeignKey<ReeaRProfiloCampoMascheratoRecord, ReeaDCampoMascheratoRecord> REEA_R_PROFILO_CAMPO_MASCHERATO__REEA_R_PROFILO_CAMPO_MASCHERATO_REEA_D_CAMPO_MASCHERATO_ID_FKEY = Internal.createForeignKey(ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO, DSL.name("reea_r_profilo_campo_mascherato_reea_d_campo_mascherato_id_fkey"), new TableField[] { ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO.CAMPO_MASCHERATO_ID }, Keys.REEA_D_CAMPO_MASCHERATO_PKEY, new TableField[] { ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO.CAMPO_MASCHERATO_ID }, true);
    public static final ForeignKey<ReeaRProfiloCampoMascheratoRecord, ReeaDProfiloRecord> REEA_R_PROFILO_CAMPO_MASCHERATO__REEA_R_PROFILO_CAMPO_MASCHERATO_REEA_D_PROFILO_ID_FKEY = Internal.createForeignKey(ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO, DSL.name("reea_r_profilo_campo_mascherato_reea_d_profilo_id_fkey"), new TableField[] { ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO.PROFILO_ID }, Keys.REEA_D_PROFILO_PKEY, new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_ID }, true);
    public static final ForeignKey<ReeaRProfiloFunzionalitaRecord, ReeaDProfiloRecord> REEA_R_PROFILO_FUNZIONALITA__REEA_R_PROFILO_FUNZIONE_REEA_D_PROFILO_ID_FKEY = Internal.createForeignKey(ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA, DSL.name("reea_r_profilo_funzione_reea_d_profilo_id_fkey"), new TableField[] { ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA.PROFILO_ID }, Keys.REEA_D_PROFILO_PKEY, new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_ID }, true);
    public static final ForeignKey<ReeaRProfiloFunzionalitaRecord, ReeaTFunzionalitaRecord> REEA_R_PROFILO_FUNZIONALITA__REEA_R_PROFILO_FUNZIONE_REEA_T_FUNZIONE_ID_FKEY = Internal.createForeignKey(ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA, DSL.name("reea_r_profilo_funzione_reea_t_funzione_id_fkey"), new TableField[] { ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA.FUNZIONALITA_ID }, Keys.REEA_T_FUNZIONALITA_PKEY, new TableField[] { ReeaTFunzionalita.REEA_T_FUNZIONALITA.FUNZIONALITA_ID }, true);
    public static final ForeignKey<ReeaRRuoloProfiloRecord, ReeaDProfiloRecord> REEA_R_RUOLO_PROFILO__REEA_R_RUOLO_PROFILO_REEA_D_PROFILO_ID_FKEY = Internal.createForeignKey(ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO, DSL.name("reea_r_ruolo_profilo_reea_d_profilo_id_fkey"), new TableField[] { ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO.PROFILO_ID }, Keys.REEA_D_PROFILO_PKEY, new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_ID }, true);
    public static final ForeignKey<ReeaRRuoloProfiloRecord, ReeaDRuoloRecord> REEA_R_RUOLO_PROFILO__REEA_R_RUOLO_PROFILO_REEA_D_RUOLO_ID_FKEY = Internal.createForeignKey(ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO, DSL.name("reea_r_ruolo_profilo_reea_d_ruolo_id_fkey"), new TableField[] { ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO.RUOLO_ID }, Keys.REEA_D_RUOLO_PKEY, new TableField[] { ReeaDRuolo.REEA_D_RUOLO.RUOLO_ID }, true);
    public static final ForeignKey<ReeaRUtenteCollocazioneRecord, ReeaTCollocazioneRecord> REEA_R_UTENTE_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_R_UTENTE_COLLOCAZIONE = Internal.createForeignKey(ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE, DSL.name("reea_t_collocazione_reea_r_utente_collocazione"), new TableField[] { ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE.COLLOCAZIONE_ID }, Keys.REEA_T_COLLOCAZIONE_PKEY, new TableField[] { ReeaTCollocazione.REEA_T_COLLOCAZIONE.COLLOCAZIONE_ID }, true);
    public static final ForeignKey<ReeaRUtenteCollocazioneRecord, ReeaTUtenteRecord> REEA_R_UTENTE_COLLOCAZIONE__REEA_T_UTENTE_REEA_R_UTENTE_COLLOCAZIONE = Internal.createForeignKey(ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE, DSL.name("reea_t_utente_reea_r_utente_collocazione"), new TableField[] { ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE.UTENTE_ID }, Keys.REEA_T_UTENTE_PKEY, new TableField[] { ReeaTUtente.REEA_T_UTENTE.UTENTE_ID }, true);
    public static final ForeignKey<ReeaRUtenteProfiloRecord, ReeaDProfiloRecord> REEA_R_UTENTE_PROFILO__REEA_R_UTENTE_PROFILO_REEA_D_PROFILO_ID_FKEY = Internal.createForeignKey(ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO, DSL.name("reea_r_utente_profilo_reea_d_profilo_id_fkey"), new TableField[] { ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO.PROFILO_ID }, Keys.REEA_D_PROFILO_PKEY, new TableField[] { ReeaDProfilo.REEA_D_PROFILO.PROFILO_ID }, true);
    public static final ForeignKey<ReeaRUtenteProfiloRecord, ReeaTUtenteRecord> REEA_R_UTENTE_PROFILO__REEA_R_UTENTE_PROFILO_REEA_T_UTENTE_ID_FKEY = Internal.createForeignKey(ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO, DSL.name("reea_r_utente_profilo_reea_t_utente_id_fkey"), new TableField[] { ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO.UTENTE_ID }, Keys.REEA_T_UTENTE_PKEY, new TableField[] { ReeaTUtente.REEA_T_UTENTE.UTENTE_ID }, true);
    public static final ForeignKey<ReeaRUtenteRuoloRecord, ReeaDRuoloRecord> REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_D_RUOLO_ID_FKEY = Internal.createForeignKey(ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO, DSL.name("reea_r_utente_ruolo_reea_d_ruolo_id_fkey"), new TableField[] { ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO.RUOLO_ID }, Keys.REEA_D_RUOLO_PKEY, new TableField[] { ReeaDRuolo.REEA_D_RUOLO.RUOLO_ID }, true);
    public static final ForeignKey<ReeaRUtenteRuoloRecord, ReeaTUtenteRecord> REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_T_UTENTE_ID_FKEY = Internal.createForeignKey(ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO, DSL.name("reea_r_utente_ruolo_reea_t_utente_id_fkey"), new TableField[] { ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO.UTENTE_ID }, Keys.REEA_T_UTENTE_PKEY, new TableField[] { ReeaTUtente.REEA_T_UTENTE.UTENTE_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDAslRecord> REEA_S_SOGGETTO__REEA_D_ASL_REEA_S_SOGGETTO = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_asl_reea_s_soggetto"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.DOMICILIO_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDAslRecord> REEA_S_SOGGETTO__REEA_D_ASL_REEA_S_SOGGETTO22 = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_asl_reea_s_soggetto22"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.RESIDENZA_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDAslRecord> REEA_S_SOGGETTO__REEA_D_ASL_REEA_S_SOGGETTO33 = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_asl_reea_s_soggetto33"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.ASSISTENZA_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDFonteRecord> REEA_S_SOGGETTO__REEA_D_FONTE_REEA_S_SOGGETTO = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_fonte_reea_s_soggetto"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.FONTE_ID }, Keys.REEA_D_FONTE_PKEY, new TableField[] { ReeaDFonte.REEA_D_FONTE.FONTE_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDInserimentoTipoRecord> REEA_S_SOGGETTO__REEA_D_INSERIMENTO_TIPO_REEA_S_SOGGETTO = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_inserimento_tipo_reea_s_soggetto"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.INSERIMENTO_TIPO_ID }, Keys.REEA_D_INSERIMENTO_TIPO_PKEY, new TableField[] { ReeaDInserimentoTipo.REEA_D_INSERIMENTO_TIPO.INSERIMENTO_TIPO_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaDSoggettoStatoRecord> REEA_S_SOGGETTO__REEA_D_SOGGETTO_STATO_REEA_S_SOGGETTO = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_d_soggetto_stato_reea_s_soggetto"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.SOGGETTO_STATO_ID }, Keys.REEA_D_SOGGETTO_STATO_PKEY, new TableField[] { ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO.SOGGETTO_STATO_ID }, true);
    public static final ForeignKey<ReeaSSoggettoRecord, ReeaTSoggettoRecord> REEA_S_SOGGETTO__REEA_T_SOGGETTO_REEA_S_SOGGETTO = Internal.createForeignKey(ReeaSSoggetto.REEA_S_SOGGETTO, DSL.name("reea_t_soggetto_reea_s_soggetto"), new TableField[] { ReeaSSoggetto.REEA_S_SOGGETTO.SOGGETTO_ID }, Keys.REEA_T_SOGGETTO_PKEY, new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.SOGGETTO_ID }, true);
    public static final ForeignKey<ReeaTAdesioneRecord, ReeaTFileRecord> REEA_T_ADESIONE__FK_REEA_T_ADESIONE_FILE = Internal.createForeignKey(ReeaTAdesione.REEA_T_ADESIONE, DSL.name("fk_reea_t_adesione_file"), new TableField[] { ReeaTAdesione.REEA_T_ADESIONE.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaTAdesioneRecord, ReeaTSoggettoRecord> REEA_T_ADESIONE__REEA_T_SOGGETTO_REEA_T_ADESIONE = Internal.createForeignKey(ReeaTAdesione.REEA_T_ADESIONE, DSL.name("reea_t_soggetto_reea_t_adesione"), new TableField[] { ReeaTAdesione.REEA_T_ADESIONE.SOGGETTO_ID }, Keys.REEA_T_SOGGETTO_PKEY, new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.SOGGETTO_ID }, true);
    public static final ForeignKey<ReeaTCollocazioneRecord, ReeaDAslRecord> REEA_T_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_D_ASL_ID_FKEY = Internal.createForeignKey(ReeaTCollocazione.REEA_T_COLLOCAZIONE, DSL.name("reea_t_collocazione_reea_d_asl_id_fkey"), new TableField[] { ReeaTCollocazione.REEA_T_COLLOCAZIONE.AZIENDA_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaTEsposizioneRecord, ReeaDFonteRecord> REEA_T_ESPOSIZIONE__REEA_D_FONTE_REEA_T_ESPOSIZIONE = Internal.createForeignKey(ReeaTEsposizione.REEA_T_ESPOSIZIONE, DSL.name("reea_d_fonte_reea_t_esposizione"), new TableField[] { ReeaTEsposizione.REEA_T_ESPOSIZIONE.FONTE_ID }, Keys.REEA_D_FONTE_PKEY, new TableField[] { ReeaDFonte.REEA_D_FONTE.FONTE_ID }, true);
    public static final ForeignKey<ReeaTFileRecord, ReeaDFileStatoRecord> REEA_T_FILE__FK_REEA_T_FILE_ULTIMO_STATO = Internal.createForeignKey(ReeaTFile.REEA_T_FILE, DSL.name("fk_reea_t_file_ultimo_stato"), new TableField[] { ReeaTFile.REEA_T_FILE.FILE_STATO_ID }, Keys.REEA_D_FILE_STATO_PKEY, new TableField[] { ReeaDFileStato.REEA_D_FILE_STATO.FILE_STATO_ID }, true);
    public static final ForeignKey<ReeaTFileImpattoRecord, ReeaLFileElaborazioneRecord> REEA_T_FILE_IMPATTO__FK_REEA_T_FILE_IMPATTO_ELAB = Internal.createForeignKey(ReeaTFileImpatto.REEA_T_FILE_IMPATTO, DSL.name("fk_reea_t_file_impatto_elab"), new TableField[] { ReeaTFileImpatto.REEA_T_FILE_IMPATTO.ELABORAZIONE_ID }, Keys.REEA_L_FILE_ELABORAZIONE_PKEY, new TableField[] { ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE.ELABORAZIONE_ID }, true);
    public static final ForeignKey<ReeaTFileImpattoRecord, ReeaDFileOperazioneTipoRecord> REEA_T_FILE_IMPATTO__FK_REEA_T_FILE_IMPATTO_TIPO = Internal.createForeignKey(ReeaTFileImpatto.REEA_T_FILE_IMPATTO, DSL.name("fk_reea_t_file_impatto_tipo"), new TableField[] { ReeaTFileImpatto.REEA_T_FILE_IMPATTO.OPERAZIONE_TIPO_ID }, Keys.REEA_D_FILE_OPERAZIONE_TIPO_PKEY, new TableField[] { ReeaDFileOperazioneTipo.REEA_D_FILE_OPERAZIONE_TIPO.OPERAZIONE_TIPO_ID }, true);
    public static final ForeignKey<ReeaTFunzionalitaRecord, ReeaDGruppoFunzionalitaRecord> REEA_T_FUNZIONALITA__REEA_T_FUNZIONE_REEA_D_GRUPPO_FUNZIONE_ID_FKEY = Internal.createForeignKey(ReeaTFunzionalita.REEA_T_FUNZIONALITA, DSL.name("reea_t_funzione_reea_d_gruppo_funzione_id_fkey"), new TableField[] { ReeaTFunzionalita.REEA_T_FUNZIONALITA.GRUPPO_FUNZIONALITA_ID }, Keys.REEA_D_GRUPPO_FUNZIONALITA_PKEY, new TableField[] { ReeaDGruppoFunzionalita.REEA_D_GRUPPO_FUNZIONALITA.GRUPPO_FUNZIONALITA_ID }, true);
    public static final ForeignKey<ReeaTNotaRecord, ReeaTRegistroRecord> REEA_T_NOTA__REEA_T_NOTA_REEA_T_REGISTRO_ID_FKEY = Internal.createForeignKey(ReeaTNota.REEA_T_NOTA, DSL.name("reea_t_nota_reea_t_registro_id_fkey"), new TableField[] { ReeaTNota.REEA_T_NOTA.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTRegistroInailRecord, ReeaTFileRecord> REEA_T_REGISTRO_INAIL__FK_REEA_T_REGISTRO_INAIL_FILE = Internal.createForeignKey(ReeaTRegistroInail.REEA_T_REGISTRO_INAIL, DSL.name("fk_reea_t_registro_inail_file"), new TableField[] { ReeaTRegistroInail.REEA_T_REGISTRO_INAIL.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaTRegistroInailRecord, ReeaTRegistroRecord> REEA_T_REGISTRO_INAIL__REEA_T_REGISTRO_REEA_T_REGISTRO_INAIL = Internal.createForeignKey(ReeaTRegistroInail.REEA_T_REGISTRO_INAIL, DSL.name("reea_t_registro_reea_t_registro_inail"), new TableField[] { ReeaTRegistroInail.REEA_T_REGISTRO_INAIL.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTRegistroPdlAmiantoRecord, ReeaTFileRecord> REEA_T_REGISTRO_PDL_AMIANTO__FK_REEA_T_REGISTRO_PDL_AMIANTO_FILE = Internal.createForeignKey(ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO, DSL.name("fk_reea_t_registro_pdl_amianto_file"), new TableField[] { ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaTRegistroPdlAmiantoRecord, ReeaTRegistroRecord> REEA_T_REGISTRO_PDL_AMIANTO__REEA_T_REGISTRO_REEA_T_REGISTRO_PDL_AMIANTO = Internal.createForeignKey(ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO, DSL.name("reea_t_registro_reea_t_registro_pdl_amianto"), new TableField[] { ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTRegistroSnapshotRecord, ReeaTRegistroRecord> REEA_T_REGISTRO_SNAPSHOT__REEA_T_REGISTRO_REEA_T_REGISTRO_SNAPSHOT = Internal.createForeignKey(ReeaTRegistroSnapshot.REEA_T_REGISTRO_SNAPSHOT, DSL.name("reea_t_registro_reea_t_registro_snapshot"), new TableField[] { ReeaTRegistroSnapshot.REEA_T_REGISTRO_SNAPSHOT.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTRegistroSpresalAnamnesiRecord, ReeaTFileRecord> REEA_T_REGISTRO_SPRESAL_ANAMNESI__FK_REEA_T_REGISTRO_SPRESAL_ANAMNESI_FILE = Internal.createForeignKey(ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI, DSL.name("fk_reea_t_registro_spresal_anamnesi_file"), new TableField[] { ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaTRegistroSpresalAnamnesiRecord, ReeaTRegistroRecord> REEA_T_REGISTRO_SPRESAL_ANAMNESI__REEA_T_REGISTRO_REEA_T_REGISTRO_SPRESAL_ANAMNESI = Internal.createForeignKey(ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI, DSL.name("reea_t_registro_reea_t_registro_spresal_anamnesi"), new TableField[] { ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTRegistroSpresalEsitiRecord, ReeaTFileRecord> REEA_T_REGISTRO_SPRESAL_ESITI__FK_REEA_T_REGISTRO_SPRESAL_ESITI_FILE = Internal.createForeignKey(ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI, DSL.name("fk_reea_t_registro_spresal_esiti_file"), new TableField[] { ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.FILE_ID }, Keys.REEA_T_FILE_PKEY, new TableField[] { ReeaTFile.REEA_T_FILE.FILE_ID }, true);
    public static final ForeignKey<ReeaTRegistroSpresalEsitiRecord, ReeaTRegistroRecord> REEA_T_REGISTRO_SPRESAL_ESITI__REEA_T_REGISTRO_REEA_T_REGISTRO_SPRESAL_ESITI = Internal.createForeignKey(ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI, DSL.name("reea_t_registro_reea_t_registro_spresal_esiti"), new TableField[] { ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI.REGISTRO_ID }, Keys.REEA_T_REGISTRO_PKEY, new TableField[] { ReeaTRegistro.REEA_T_REGISTRO.REGISTRO_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDAslRecord> REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO33 = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_asl_reea_t_soggetto33"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.ASSISTENZA_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDAslRecord> REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_DOMICILIO_DOMICILIO = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_asl_reea_t_soggetto_domicilio_domicilio"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.DOMICILIO_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDAslRecord> REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_RESIDENZA_RESIDENZA = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_asl_reea_t_soggetto_residenza_residenza"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.RESIDENZA_ASL_ID }, Keys.REEA_D_ASL_PKEY, new TableField[] { ReeaDAsl.REEA_D_ASL.ASL_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDFonteRecord> REEA_T_SOGGETTO__REEA_D_FONTE_REEA_T_SOGGETTO = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_fonte_reea_t_soggetto"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.FONTE_ID }, Keys.REEA_D_FONTE_PKEY, new TableField[] { ReeaDFonte.REEA_D_FONTE.FONTE_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDInserimentoTipoRecord> REEA_T_SOGGETTO__REEA_D_INSERIMENTO_TIPO_REEA_T_SOGGETTO = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_inserimento_tipo_reea_t_soggetto"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.INSERIMENTO_TIPO_ID }, Keys.REEA_D_INSERIMENTO_TIPO_PKEY, new TableField[] { ReeaDInserimentoTipo.REEA_D_INSERIMENTO_TIPO.INSERIMENTO_TIPO_ID }, true);
    public static final ForeignKey<ReeaTSoggettoRecord, ReeaDSoggettoStatoRecord> REEA_T_SOGGETTO__REEA_D_SOGGETTO_STATO_REEA_T_SOGGETTO = Internal.createForeignKey(ReeaTSoggetto.REEA_T_SOGGETTO, DSL.name("reea_d_soggetto_stato_reea_t_soggetto"), new TableField[] { ReeaTSoggetto.REEA_T_SOGGETTO.SOGGETTO_STATO_ID }, Keys.REEA_D_SOGGETTO_STATO_PKEY, new TableField[] { ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO.SOGGETTO_STATO_ID }, true);
}
