/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq;


import it.csi.registry.jooq.routines.HmacSoggettoId;
import it.csi.registry.jooq.routines.TextToHmac;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in reea.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>reea.hmac_soggetto_id</code>
     */
    public static String hmacSoggettoId(
          Configuration configuration
        , Integer pSoggettoId
        , String pKey
    ) {
        HmacSoggettoId f = new HmacSoggettoId();
        f.setPSoggettoId(pSoggettoId);
        f.setPKey(pKey);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>reea.hmac_soggetto_id</code> as a field.
     */
    public static Field<String> hmacSoggettoId(
          Integer pSoggettoId
        , String pKey
    ) {
        HmacSoggettoId f = new HmacSoggettoId();
        f.setPSoggettoId(pSoggettoId);
        f.setPKey(pKey);

        return f.asField();
    }

    /**
     * Get <code>reea.hmac_soggetto_id</code> as a field.
     */
    public static Field<String> hmacSoggettoId(
          Field<Integer> pSoggettoId
        , Field<String> pKey
    ) {
        HmacSoggettoId f = new HmacSoggettoId();
        f.setPSoggettoId(pSoggettoId);
        f.setPKey(pKey);

        return f.asField();
    }

    /**
     * Call <code>reea.text_to_hmac</code>
     */
    public static String textToHmac(
          Configuration configuration
        , String textToHmac
        , String hmacText
    ) {
        TextToHmac f = new TextToHmac();
        f.setTextToHmac(textToHmac);
        f.setHmacText(hmacText);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>reea.text_to_hmac</code> as a field.
     */
    public static Field<String> textToHmac(
          String textToHmac
        , String hmacText
    ) {
        TextToHmac f = new TextToHmac();
        f.setTextToHmac(textToHmac);
        f.setHmacText(hmacText);

        return f.asField();
    }

    /**
     * Get <code>reea.text_to_hmac</code> as a field.
     */
    public static Field<String> textToHmac(
          Field<String> textToHmac
        , Field<String> hmacText
    ) {
        TextToHmac f = new TextToHmac();
        f.setTextToHmac(textToHmac);
        f.setHmacText(hmacText);

        return f.asField();
    }
}
