/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq;


import it.csi.registry.jooq.tables.CsiLogAudit;
import it.csi.registry.jooq.tables.ReaTSoggettoPoc;
import it.csi.registry.jooq.tables.ReeaCParametro;
import it.csi.registry.jooq.tables.ReeaCParametroTipo;
import it.csi.registry.jooq.tables.ReeaDAsl;
import it.csi.registry.jooq.tables.ReeaDAttestazioneSanitariaStato;
import it.csi.registry.jooq.tables.ReeaDAzienda;
import it.csi.registry.jooq.tables.ReeaDCampoMascherato;
import it.csi.registry.jooq.tables.ReeaDComune;
import it.csi.registry.jooq.tables.ReeaDEsenzione;
import it.csi.registry.jooq.tables.ReeaDFileOperazioneTipo;
import it.csi.registry.jooq.tables.ReeaDFileStato;
import it.csi.registry.jooq.tables.ReeaDFonte;
import it.csi.registry.jooq.tables.ReeaDGruppoFunzionalita;
import it.csi.registry.jooq.tables.ReeaDInserimentoTipo;
import it.csi.registry.jooq.tables.ReeaDNazione;
import it.csi.registry.jooq.tables.ReeaDProfilo;
import it.csi.registry.jooq.tables.ReeaDProfiloTipo;
import it.csi.registry.jooq.tables.ReeaDProvincia;
import it.csi.registry.jooq.tables.ReeaDRegione;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiMansione;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiRagionesociale;
import it.csi.registry.jooq.tables.ReeaDRegistroSpresalAnamnesiSettore;
import it.csi.registry.jooq.tables.ReeaDRuolo;
import it.csi.registry.jooq.tables.ReeaDSoggettoStato;
import it.csi.registry.jooq.tables.ReeaLFileElaborazione;
import it.csi.registry.jooq.tables.ReeaLFileElaborazioneErrore;
import it.csi.registry.jooq.tables.ReeaLFileScaricoErrore;
import it.csi.registry.jooq.tables.ReeaRProfiloCampoMascherato;
import it.csi.registry.jooq.tables.ReeaRProfiloFunzionalita;
import it.csi.registry.jooq.tables.ReeaRRuoloProfilo;
import it.csi.registry.jooq.tables.ReeaRSoggettoEsenzione;
import it.csi.registry.jooq.tables.ReeaRSoggettoEsenzioneBkp;
import it.csi.registry.jooq.tables.ReeaRUtenteCollocazione;
import it.csi.registry.jooq.tables.ReeaRUtenteProfilo;
import it.csi.registry.jooq.tables.ReeaRUtenteRuolo;
import it.csi.registry.jooq.tables.ReeaSSoggetto;
import it.csi.registry.jooq.tables.ReeaTAdesione;
import it.csi.registry.jooq.tables.ReeaTCollocazione;
import it.csi.registry.jooq.tables.ReeaTEsposizione;
import it.csi.registry.jooq.tables.ReeaTFile;
import it.csi.registry.jooq.tables.ReeaTFileImpatto;
import it.csi.registry.jooq.tables.ReeaTFunzionalita;
import it.csi.registry.jooq.tables.ReeaTNota;
import it.csi.registry.jooq.tables.ReeaTRegistro;
import it.csi.registry.jooq.tables.ReeaTRegistroInail;
import it.csi.registry.jooq.tables.ReeaTRegistroPdlAmianto;
import it.csi.registry.jooq.tables.ReeaTRegistroSnapshot;
import it.csi.registry.jooq.tables.ReeaTRegistroSpresalAnamnesi;
import it.csi.registry.jooq.tables.ReeaTRegistroSpresalEsiti;
import it.csi.registry.jooq.tables.ReeaTSoggetto;
import it.csi.registry.jooq.tables.ReeaTUtente;
import it.csi.registry.jooq.tables.TmpComuni;


/**
 * Convenience access to all tables in reea.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>reea.csi_log_audit</code>.
     */
    public static final CsiLogAudit CSI_LOG_AUDIT = CsiLogAudit.CSI_LOG_AUDIT;

    /**
     * The table <code>reea.rea_t_soggetto_poc</code>.
     */
    public static final ReaTSoggettoPoc REA_T_SOGGETTO_POC = ReaTSoggettoPoc.REA_T_SOGGETTO_POC;

    /**
     * parametri di configurazione
     */
    public static final ReeaCParametro REEA_C_PARAMETRO = ReeaCParametro.REEA_C_PARAMETRO;

    /**
     * tipo di parametri di configurazione Es.  ERRORE MESSAGGIO_PUSH
     * MESSAGGIO_EMAIL MESSAGGIO_SMS PARAMETRO
     */
    public static final ReeaCParametroTipo REEA_C_PARAMETRO_TIPO = ReeaCParametroTipo.REEA_C_PARAMETRO_TIPO;

    /**
     * ASL:  203,ASL TO3 (Distretti Pinerolo, Val Susa-Val Sangone, Area
     * Metropolitana Nord-Centro-Sud)   204,ASL TO4 (Distretti di Ciriè,
     * Chivasso-San Mauro, Settimo Torinese, Ivrea, Cuorgnè)   205,ASL TO5
     * (Chieri, Carmagnola, Moncalieri, Nichelino)   206,ASL VC (Vercelli)  
     * 207,ASL BI (Biella)   208,ASL NO (Novara)   209,ASL VCO (Verbano Cusio
     * Ossola)   210,ASL CN1 (Cuneo, Borgo S.Dalmazzo-Dronero, Mondovì, Ceva,
     * Savigliano-Fossano, Saluzzo)   211,ASL CN2 (Alba e Bra)   212,ASL AT
     * (Asti Centro, Asti Nord, Asti Sud)   213,ASL AL (Alessandria)   301,ASL
     * Città di TORINO
     */
    public static final ReeaDAsl REEA_D_ASL = ReeaDAsl.REEA_D_ASL;

    /**
     * può valere SI/NO/IN CORSO
     */
    public static final ReeaDAttestazioneSanitariaStato REEA_D_ATTESTAZIONE_SANITARIA_STATO = ReeaDAttestazioneSanitariaStato.REEA_D_ATTESTAZIONE_SANITARIA_STATO;

    /**
     * Dizionario delle Aziende Sanitarie o Enti.  Fonte: PDF Specifica
     * Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_AZIENDA.
     */
    public static final ReeaDAzienda REEA_D_AZIENDA = ReeaDAzienda.REEA_D_AZIENDA;

    /**
     * The table <code>reea.reea_d_campo_mascherato</code>.
     */
    public static final ReeaDCampoMascherato REEA_D_CAMPO_MASCHERATO = ReeaDCampoMascherato.REEA_D_CAMPO_MASCHERATO;

    /**
     * The table <code>reea.reea_d_comune</code>.
     */
    public static final ReeaDComune REEA_D_COMUNE = ReeaDComune.REEA_D_COMUNE;

    /**
     * contiene l'elenco delle sole esenzioni di interesse per gli operatori
     */
    public static final ReeaDEsenzione REEA_D_ESENZIONE = ReeaDEsenzione.REEA_D_ESENZIONE;

    /**
     * INSERT, UPDATE, DELETE (LOGICA)
     */
    public static final ReeaDFileOperazioneTipo REEA_D_FILE_OPERAZIONE_TIPO = ReeaDFileOperazioneTipo.REEA_D_FILE_OPERAZIONE_TIPO;

    /**
     * The table <code>reea.reea_d_file_stato</code>.
     */
    public static final ReeaDFileStato REEA_D_FILE_STATO = ReeaDFileStato.REEA_D_FILE_STATO;

    /**
     * Segnalazione MMG, altro Pre-adesione INAIL SPRESAL PIANI DI LAVORO
     * AMIANTO   --ex valori PREADESIONE INAIL SPRESAL-ANMNESI SPRESAL-ESITI
     * PIANI DI LAVORO AMIANTO REGISTRO CANCEROGENI MANUALE(MMG)
     */
    public static final ReeaDFonte REEA_D_FONTE = ReeaDFonte.REEA_D_FONTE;

    /**
     * Macro-gruppi per categorizzare le funzionalità del sistema.  Fonte: PDF
     * Specifica Database, Sezione 2.1 (Pag. 4), Tabella RREA_D_GRUPPO_FUNZIONE.
     */
    public static final ReeaDGruppoFunzionalita REEA_D_GRUPPO_FUNZIONALITA = ReeaDGruppoFunzionalita.REEA_D_GRUPPO_FUNZIONALITA;

    /**
     * The table <code>reea.reea_d_inserimento_tipo</code>.
     */
    public static final ReeaDInserimentoTipo REEA_D_INSERIMENTO_TIPO = ReeaDInserimentoTipo.REEA_D_INSERIMENTO_TIPO;

    /**
     * The table <code>reea.reea_d_nazione</code>.
     */
    public static final ReeaDNazione REEA_D_NAZIONE = ReeaDNazione.REEA_D_NAZIONE;

    /**
     * Profili funzionali (raggruppamenti logici di permessi).  Fonte: PDF
     * Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_PROFILO.
     */
    public static final ReeaDProfilo REEA_D_PROFILO = ReeaDProfilo.REEA_D_PROFILO;

    /**
     * The table <code>reea.reea_d_profilo_tipo</code>.
     */
    public static final ReeaDProfiloTipo REEA_D_PROFILO_TIPO = ReeaDProfiloTipo.REEA_D_PROFILO_TIPO;

    /**
     * The table <code>reea.reea_d_provincia</code>.
     */
    public static final ReeaDProvincia REEA_D_PROVINCIA = ReeaDProvincia.REEA_D_PROVINCIA;

    /**
     * REGIONE PIEMONTE FUORI REGIONE PIEMONTE SASN AIRE
     */
    public static final ReeaDRegione REEA_D_REGIONE = ReeaDRegione.REEA_D_REGIONE;

    /**
     * valorizza di default
     * reea_d_registro_spresal_anamnesi.occupazione_mansione_crpt
     */
    public static final ReeaDRegistroSpresalAnamnesiMansione REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE = ReeaDRegistroSpresalAnamnesiMansione.REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE;

    /**
     * valorizza di default
     * reea_d_registro_spresal_anamnesi.occupazione_ragione_sociale_ditta_crpt
     */
    public static final ReeaDRegistroSpresalAnamnesiRagionesociale REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE = ReeaDRegistroSpresalAnamnesiRagionesociale.REEA_D_REGISTRO_SPRESAL_ANAMNESI_RAGIONESOCIALE;

    /**
     * valorizza di default
     * reea_d_registro_spresal_anamnesi.occupazione_settore_ditta_crpt
     */
    public static final ReeaDRegistroSpresalAnamnesiSettore REEA_D_REGISTRO_SPRESAL_ANAMNESI_SETTORE = ReeaDRegistroSpresalAnamnesiSettore.REEA_D_REGISTRO_SPRESAL_ANAMNESI_SETTORE;

    /**
     * Ruoli assegnabili agli utenti (es. Medico competente, Amministrativo). 
     * Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella
     * REEA_D_RUOLO.
     */
    public static final ReeaDRuolo REEA_D_RUOLO = ReeaDRuolo.REEA_D_RUOLO;

    /**
     * Dizionario degli stati di avanzamento della pratica (es. Da Validare,
     * Monitoraggio).  Fonte: PDF Specifica Database, Sezione 2.3.3 (Pag. 8),
     * Tabella REEA_D_ASSISTITO_STATO.  -    DA VALIDARE -    VALIDATO -    NON
     * VALIDATO -    INVIATO AL MONITORAGGIO -    ESCLUSO DAL MONITORAGGIO -   
     * MONITORAGGIO CONCLUSO
     */
    public static final ReeaDSoggettoStato REEA_D_SOGGETTO_STATO = ReeaDSoggettoStato.REEA_D_SOGGETTO_STATO;

    /**
     * Storico dei tentativi di elaborazione batch. Permette di gestire i retry
     * mantenendo traccia degli errori passati.
     */
    public static final ReeaLFileElaborazione REEA_L_FILE_ELABORAZIONE = ReeaLFileElaborazione.REEA_L_FILE_ELABORAZIONE;

    /**
     * The table <code>reea.reea_l_file_elaborazione_errore</code>.
     */
    public static final ReeaLFileElaborazioneErrore REEA_L_FILE_ELABORAZIONE_ERRORE = ReeaLFileElaborazioneErrore.REEA_L_FILE_ELABORAZIONE_ERRORE;

    /**
     * The table <code>reea.reea_l_file_scarico_errore</code>.
     */
    public static final ReeaLFileScaricoErrore REEA_L_FILE_SCARICO_ERRORE = ReeaLFileScaricoErrore.REEA_L_FILE_SCARICO_ERRORE;

    /**
     * The table <code>reea.reea_r_profilo_campo_mascherato</code>.
     */
    public static final ReeaRProfiloCampoMascherato REEA_R_PROFILO_CAMPO_MASCHERATO = ReeaRProfiloCampoMascherato.REEA_R_PROFILO_CAMPO_MASCHERATO;

    /**
     * Associazione N:M tra Profili e Funzionalità abilitate.  Fonte: PDF
     * Specifica Database, Sezione 2.1 (Pag. 4), Tabella
     * REEA_R_PROFILO_FUNZIONE.
     */
    public static final ReeaRProfiloFunzionalita REEA_R_PROFILO_FUNZIONALITA = ReeaRProfiloFunzionalita.REEA_R_PROFILO_FUNZIONALITA;

    /**
     * Associazione N:M tra Ruoli e Profili.  Fonte: PDF Specifica Database,
     * Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_PROFILO.
     */
    public static final ReeaRRuoloProfilo REEA_R_RUOLO_PROFILO = ReeaRRuoloProfilo.REEA_R_RUOLO_PROFILO;

    /**
     * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
     * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
     * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica
     * Database, Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
     */
    public static final ReeaRSoggettoEsenzione REEA_R_SOGGETTO_ESENZIONE = ReeaRSoggettoEsenzione.REEA_R_SOGGETTO_ESENZIONE;

    /**
     * The table <code>reea.reea_r_soggetto_esenzione_bkp</code>.
     */
    public static final ReeaRSoggettoEsenzioneBkp REEA_R_SOGGETTO_ESENZIONE_BKP = ReeaRSoggettoEsenzioneBkp.REEA_R_SOGGETTO_ESENZIONE_BKP;

    /**
     * Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica
     * Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE.
     */
    public static final ReeaRUtenteCollocazione REEA_R_UTENTE_COLLOCAZIONE = ReeaRUtenteCollocazione.REEA_R_UTENTE_COLLOCAZIONE;

    /**
     * The table <code>reea.reea_r_utente_profilo</code>.
     */
    public static final ReeaRUtenteProfilo REEA_R_UTENTE_PROFILO = ReeaRUtenteProfilo.REEA_R_UTENTE_PROFILO;

    /**
     * Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica
     * Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE.
     */
    public static final ReeaRUtenteRuolo REEA_R_UTENTE_RUOLO = ReeaRUtenteRuolo.REEA_R_UTENTE_RUOLO;

    /**
     * Contiene le PII (Dati Identificativi Personali) cifrate: Nome, Cognome,
     * Indirizzi.  Fonte: PDF Specifica Database, Sezione 2.3.1 (Pag. 6),
     * Tabella REEA_T_ASSISTITO.  Nota tecnica: I campi sono cifrati (BYTEA) e
     * separati dal Soggetto base.
     */
    public static final ReeaSSoggetto REEA_S_SOGGETTO = ReeaSSoggetto.REEA_S_SOGGETTO;

    /**
     * The table <code>reea.reea_t_adesione</code>.
     */
    public static final ReeaTAdesione REEA_T_ADESIONE = ReeaTAdesione.REEA_T_ADESIONE;

    /**
     * Sedi operative (ospedali, distretti) associate alle aziende.  Fonte: PDF
     * Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_T_COLLOCAZIONE.
     */
    public static final ReeaTCollocazione REEA_T_COLLOCAZIONE = ReeaTCollocazione.REEA_T_COLLOCAZIONE;

    /**
     * The table <code>reea.reea_t_esposizione</code>.
     */
    public static final ReeaTEsposizione REEA_T_ESPOSIZIONE = ReeaTEsposizione.REEA_T_ESPOSIZIONE;

    /**
     * Registro dei file caricati a sistema. Rappresenta il file fisico su
     * disco.
     */
    public static final ReeaTFile REEA_T_FILE = ReeaTFile.REEA_T_FILE;

    /**
     * The table <code>reea.reea_t_file_impatto</code>.
     */
    public static final ReeaTFileImpatto REEA_T_FILE_IMPATTO = ReeaTFileImpatto.REEA_T_FILE_IMPATTO;

    /**
     * Elenco puntuale delle funzionalità/azioni eseguibili nel sistema.  Fonte:
     * PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella RREA_T_FUNZIONE.
     */
    public static final ReeaTFunzionalita REEA_T_FUNZIONALITA = ReeaTFunzionalita.REEA_T_FUNZIONALITA;

    /**
     * Note testuali libere associate alla pratica del registro.  Fonte: PDF
     * Specifica Database, citata in Pagina 6 ("Note") e diagramma Pagina 11
     * ("Nota_registro").
     */
    public static final ReeaTNota REEA_T_NOTA = ReeaTNota.REEA_T_NOTA;

    /**
     * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
     * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
     * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica
     * Database, Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
     */
    public static final ReeaTRegistro REEA_T_REGISTRO = ReeaTRegistro.REEA_T_REGISTRO;

    /**
     * Registro INAIL - dati anagrafici e domanda assistito
     */
    public static final ReeaTRegistroInail REEA_T_REGISTRO_INAIL = ReeaTRegistroInail.REEA_T_REGISTRO_INAIL;

    /**
     * Registro PDL Amianto - piani di lavoro per cantieri di rimozione amianto
     */
    public static final ReeaTRegistroPdlAmianto REEA_T_REGISTRO_PDL_AMIANTO = ReeaTRegistroPdlAmianto.REEA_T_REGISTRO_PDL_AMIANTO;

    /**
     * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
     * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
     * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica
     * Database, Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
     */
    public static final ReeaTRegistroSnapshot REEA_T_REGISTRO_SNAPSHOT = ReeaTRegistroSnapshot.REEA_T_REGISTRO_SNAPSHOT;

    /**
     * Registro SPRESAL - anamnesi (scheda S02)
     */
    public static final ReeaTRegistroSpresalAnamnesi REEA_T_REGISTRO_SPRESAL_ANAMNESI = ReeaTRegistroSpresalAnamnesi.REEA_T_REGISTRO_SPRESAL_ANAMNESI;

    /**
     * Registro SPRESAL - esiti delle visite (schede S07 e S08)
     */
    public static final ReeaTRegistroSpresalEsiti REEA_T_REGISTRO_SPRESAL_ESITI = ReeaTRegistroSpresalEsiti.REEA_T_REGISTRO_SPRESAL_ESITI;

    /**
     * Contiene le PII (Dati Identificativi Personali) cifrate: Nome, Cognome,
     * Indirizzi.  Fonte: PDF Specifica Database, Sezione 2.3.1 (Pag. 6),
     * Tabella REEA_T_ASSISTITO.  Nota tecnica: I campi sono cifrati (BYTEA) e
     * separati dal Soggetto base.
     */
    public static final ReeaTSoggetto REEA_T_SOGGETTO = ReeaTSoggetto.REEA_T_SOGGETTO;

    /**
     * Anagrafica degli operatori che accedono al backoffice (RUPAR/SPID). 
     * Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella
     * RREA_T_UTENTE (e Sezione 1.1 Profilazione PDF 1).
     */
    public static final ReeaTUtente REEA_T_UTENTE = ReeaTUtente.REEA_T_UTENTE;

    /**
     * The table <code>reea.tmp_comuni</code>.
     */
    public static final TmpComuni TMP_COMUNI = TmpComuni.TMP_COMUNI;
}
