sonar.projectKey=reeabe
sonar.projectName=reeabe
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=common-registry/src/main/java,amianto-registry/src/main/java
sonar.java.binaries=target/classes
sonar.exclusions=amianto-registry/src/main/resources/application-local.yaml, common-registry/src/main/resources/openapi-docs/index.html, amianto-registry/src/main/java/it/csi/registry/jooq/**, amianto-registry/src/main/resources/application.yaml, amianto-registry/src/main/resources/application-tst.yaml