/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaDAsl.ReeaDAslPath;
import it.csi.registry.jooq.tables.ReeaDFonte.ReeaDFontePath;
import it.csi.registry.jooq.tables.ReeaDInserimentoTipo.ReeaDInserimentoTipoPath;
import it.csi.registry.jooq.tables.ReeaDSoggettoStato.ReeaDSoggettoStatoPath;
import it.csi.registry.jooq.tables.ReeaSSoggetto.ReeaSSoggettoPath;
import it.csi.registry.jooq.tables.ReeaTAdesione.ReeaTAdesionePath;
import it.csi.registry.jooq.tables.records.ReeaTSoggettoRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Contiene le PII (Dati Identificativi Personali) cifrate: Nome, Cognome,
 * Indirizzi.  Fonte: PDF Specifica Database, Sezione 2.3.1 (Pag. 6), Tabella
 * REEA_T_ASSISTITO.  Nota tecnica: I campi sono cifrati (BYTEA) e separati dal
 * Soggetto base.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTSoggetto extends TableImpl<ReeaTSoggettoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_t_soggetto</code>
     */
    public static final ReeaTSoggetto REEA_T_SOGGETTO = new ReeaTSoggetto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaTSoggettoRecord> getRecordType() {
        return ReeaTSoggettoRecord.class;
    }

    /**
     * The column <code>reea.reea_t_soggetto.soggetto_id</code>.
     */
    public final TableField<ReeaTSoggettoRecord, Integer> SOGGETTO_ID = createField(DSL.name("soggetto_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.codice_fiscale</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> CODICE_FISCALE = createField(DSL.name("codice_fiscale"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_asl_id</code>. filtro
     * visibilità dati
     */
    public final TableField<ReeaTSoggettoRecord, Integer> DOMICILIO_ASL_ID = createField(DSL.name("domicilio_asl_id"), SQLDataType.INTEGER.nullable(false), this, "filtro visibilità dati");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_asl_id</code>. filtro
     * visibilità dati
     */
    public final TableField<ReeaTSoggettoRecord, Integer> RESIDENZA_ASL_ID = createField(DSL.name("residenza_asl_id"), SQLDataType.INTEGER.nullable(false), this, "filtro visibilità dati");

    /**
     * The column <code>reea.reea_t_soggetto.assistenza_asl_id</code>. filtro
     * visibilità dati
     */
    public final TableField<ReeaTSoggettoRecord, Integer> ASSISTENZA_ASL_ID = createField(DSL.name("assistenza_asl_id"), SQLDataType.INTEGER.nullable(false), this, "filtro visibilità dati");

    /**
     * The column <code>reea.reea_t_soggetto.nome_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> NOME_CIFRATO = createField(DSL.name("nome_cifrato"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cognome_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> COGNOME_CIFRATO = createField(DSL.name("cognome_cifrato"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.sesso</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> SESSO = createField(DSL.name("sesso"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_data</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDate> NASCITA_DATA = createField(DSL.name("nascita_data"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_comune_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_COMUNE_COD = createField(DSL.name("nascita_comune_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_comune_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_COMUNE_DESC = createField(DSL.name("nascita_comune_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_provincia_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_PROVINCIA_COD = createField(DSL.name("nascita_provincia_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_provincia_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_PROVINCIA_DESC = createField(DSL.name("nascita_provincia_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_stato_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_STATO_COD = createField(DSL.name("nascita_stato_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nascita_stato_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> NASCITA_STATO_DESC = createField(DSL.name("nascita_stato_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cittadinanza_stato_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> CITTADINANZA_STATO_COD = createField(DSL.name("cittadinanza_stato_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cittadinanza_stato_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> CITTADINANZA_STATO_DESC = createField(DSL.name("cittadinanza_stato_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_comune_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_COMUNE_COD = createField(DSL.name("domicilio_comune_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_comune_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_COMUNE_DESC = createField(DSL.name("domicilio_comune_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_provincia_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_PROVINCIA_COD = createField(DSL.name("domicilio_provincia_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_provincia_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_PROVINCIA_DESC = createField(DSL.name("domicilio_provincia_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_stato_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_STATO_COD = createField(DSL.name("domicilio_stato_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_stato_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_STATO_DESC = createField(DSL.name("domicilio_stato_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_cap</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_CAP = createField(DSL.name("domicilio_cap"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_indirizzo_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> DOMICILIO_INDIRIZZO_CIFRATO = createField(DSL.name("domicilio_indirizzo_cifrato"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_comune_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_COMUNE_COD = createField(DSL.name("residenza_comune_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_comune_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_COMUNE_DESC = createField(DSL.name("residenza_comune_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_provincia_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_PROVINCIA_COD = createField(DSL.name("residenza_provincia_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_provincia_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_PROVINCIA_DESC = createField(DSL.name("residenza_provincia_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_stato_cod</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_STATO_COD = createField(DSL.name("residenza_stato_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_stato_desc</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_STATO_DESC = createField(DSL.name("residenza_stato_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_cap</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_CAP = createField(DSL.name("residenza_cap"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.email_cifrata</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> EMAIL_CIFRATA = createField(DSL.name("email_cifrata"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.telefono_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> TELEFONO_CIFRATO = createField(DSL.name("telefono_cifrato"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.tessera_team_cifrata</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> TESSERA_TEAM_CIFRATA = createField(DSL.name("tessera_team_cifrata"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.id_aura_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> ID_AURA_CIFRATO = createField(DSL.name("id_aura_cifrato"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.email_aura_cifrata</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> EMAIL_AURA_CIFRATA = createField(DSL.name("email_aura_cifrata"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.telefono_aura_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> TELEFONO_AURA_CIFRATO = createField(DSL.name("telefono_aura_cifrato"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.data_aggiornamento_aura</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> DATA_AGGIORNAMENTO_AURA = createField(DSL.name("data_aggiornamento_aura"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.data_decesso</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> DATA_DECESSO = createField(DSL.name("data_decesso"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.assistenza_asl_fine</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> ASSISTENZA_ASL_FINE = createField(DSL.name("assistenza_asl_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.inserimento_tipo_id</code>.
     */
    public final TableField<ReeaTSoggettoRecord, Integer> INSERIMENTO_TIPO_ID = createField(DSL.name("inserimento_tipo_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.validita_inizio</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.validita_fine</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.data_creazione</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.data_modifica</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.data_cancellazione</code>.
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_soggetto.utente_creazione</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.utente_modifica</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.utente_cancellazione</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.fonte_id</code>.
     */
    public final TableField<ReeaTSoggettoRecord, Integer> FONTE_ID = createField(DSL.name("fonte_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.soggetto_stato_id</code>.
     */
    public final TableField<ReeaTSoggettoRecord, Integer> SOGGETTO_STATO_ID = createField(DSL.name("soggetto_stato_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.versione_numero</code>. ordine
     * inserimento modifica
     */
    public final TableField<ReeaTSoggettoRecord, Integer> VERSIONE_NUMERO = createField(DSL.name("versione_numero"), SQLDataType.INTEGER, this, "ordine inserimento modifica");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_indirizzo_cifrato</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> RESIDENZA_INDIRIZZO_CIFRATO = createField(DSL.name("residenza_indirizzo_cifrato"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.domicilio_numero_civico</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> DOMICILIO_NUMERO_CIVICO = createField(DSL.name("domicilio_numero_civico"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.residenza_numero_civico</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> RESIDENZA_NUMERO_CIVICO = createField(DSL.name("residenza_numero_civico"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.presentazione_istanza_data</code>.
     * Data di presentazione dell'istanza nel caso di inserimento da
     * segnalazione MMG
     */
    public final TableField<ReeaTSoggettoRecord, LocalDateTime> PRESENTAZIONE_ISTANZA_DATA = createField(DSL.name("presentazione_istanza_data"), SQLDataType.LOCALDATETIME(6), this, "Data di presentazione dell'istanza nel caso di inserimento da segnalazione MMG");

    /**
     * The column <code>reea.reea_t_soggetto.soggetto_stato_note</code>.
     */
    public final TableField<ReeaTSoggettoRecord, String> SOGGETTO_STATO_NOTE = createField(DSL.name("soggetto_stato_note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cognome_hash</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> COGNOME_HASH = createField(DSL.name("cognome_hash"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nome_hash</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> NOME_HASH = createField(DSL.name("nome_hash"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cognome_hash_2char</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> COGNOME_HASH_2CHAR = createField(DSL.name("cognome_hash_2char"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.cognome_hash_1char</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> COGNOME_HASH_1CHAR = createField(DSL.name("cognome_hash_1char"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nome_hash_2char</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> NOME_HASH_2CHAR = createField(DSL.name("nome_hash_2char"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>reea.reea_t_soggetto.nome_hash_1char</code>.
     */
    public final TableField<ReeaTSoggettoRecord, byte[]> NOME_HASH_1CHAR = createField(DSL.name("nome_hash_1char"), SQLDataType.BLOB, this, "");

    private ReeaTSoggetto(Name alias, Table<ReeaTSoggettoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaTSoggetto(Name alias, Table<ReeaTSoggettoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Contiene le PII (Dati Identificativi Personali) cifrate: Nome, Cognome, Indirizzi.  Fonte: PDF Specifica Database, Sezione 2.3.1 (Pag. 6), Tabella REEA_T_ASSISTITO.  Nota tecnica: I campi sono cifrati (BYTEA) e separati dal Soggetto base."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_t_soggetto</code> table reference
     */
    public ReeaTSoggetto(String alias) {
        this(DSL.name(alias), REEA_T_SOGGETTO);
    }

    /**
     * Create an aliased <code>reea.reea_t_soggetto</code> table reference
     */
    public ReeaTSoggetto(Name alias) {
        this(alias, REEA_T_SOGGETTO);
    }

    /**
     * Create a <code>reea.reea_t_soggetto</code> table reference
     */
    public ReeaTSoggetto() {
        this(DSL.name("reea_t_soggetto"), null);
    }

    public <O extends Record> ReeaTSoggetto(Table<O> path, ForeignKey<O, ReeaTSoggettoRecord> childPath, InverseForeignKey<O, ReeaTSoggettoRecord> parentPath) {
        super(path, childPath, parentPath, REEA_T_SOGGETTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaTSoggettoPath extends ReeaTSoggetto implements Path<ReeaTSoggettoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaTSoggettoPath(Table<O> path, ForeignKey<O, ReeaTSoggettoRecord> childPath, InverseForeignKey<O, ReeaTSoggettoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaTSoggettoPath(Name alias, Table<ReeaTSoggettoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaTSoggettoPath as(String alias) {
            return new ReeaTSoggettoPath(DSL.name(alias), this);
        }

        @Override
        public ReeaTSoggettoPath as(Name alias) {
            return new ReeaTSoggettoPath(alias, this);
        }

        @Override
        public ReeaTSoggettoPath as(Table<?> alias) {
            return new ReeaTSoggettoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_T_SOGGETTO_1, Indexes.IDX_REEA_T_SOGGETTO_2, Indexes.IDX_REEA_T_SOGGETTO_3, Indexes.IDX_REEA_T_SOGGETTO_4, Indexes.IDX_REEA_T_SOGGETTO_ASSISTENZA_ASL, Indexes.IDX_REEA_T_SOGGETTO_FONTE_ID, Indexes.IDX_REEA_T_SOGGETTO_NASCITA_DATA, Indexes.IDX_SOGGETTO_COGNOME_HASH, Indexes.IDX_SOGGETTO_COGNOME_HASH_1CHAR, Indexes.IDX_SOGGETTO_COGNOME_HASH_2CHAR, Indexes.IDX_SOGGETTO_NOME_HASH, Indexes.IDX_SOGGETTO_NOME_HASH_1CHAR, Indexes.IDX_SOGGETTO_NOME_HASH_2CHAR);
    }

    @Override
    public Identity<ReeaTSoggettoRecord, Integer> getIdentity() {
        return (Identity<ReeaTSoggettoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaTSoggettoRecord> getPrimaryKey() {
        return Keys.REEA_T_SOGGETTO_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaTSoggettoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_DOMICILIO_DOMICILIO, Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_RESIDENZA_RESIDENZA, Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO33, Keys.REEA_T_SOGGETTO__REEA_D_INSERIMENTO_TIPO_REEA_T_SOGGETTO, Keys.REEA_T_SOGGETTO__REEA_D_FONTE_REEA_T_SOGGETTO, Keys.REEA_T_SOGGETTO__REEA_D_SOGGETTO_STATO_REEA_T_SOGGETTO);
    }

    private transient ReeaDAslPath _reeaDAslReeaTSoggettoDomicilioDomicilio;

    /**
     * Get the implicit join path to the <code>reea.reea_d_asl</code> table, via
     * the <code>reea_d_asl_reea_t_soggetto_domicilio_domicilio</code> key.
     */
    public ReeaDAslPath reeaDAslReeaTSoggettoDomicilioDomicilio() {
        if (_reeaDAslReeaTSoggettoDomicilioDomicilio == null)
            _reeaDAslReeaTSoggettoDomicilioDomicilio = new ReeaDAslPath(this, Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_DOMICILIO_DOMICILIO, null);

        return _reeaDAslReeaTSoggettoDomicilioDomicilio;
    }

    private transient ReeaDAslPath _reeaDAslReeaTSoggettoResidenzaResidenza;

    /**
     * Get the implicit join path to the <code>reea.reea_d_asl</code> table, via
     * the <code>reea_d_asl_reea_t_soggetto_residenza_residenza</code> key.
     */
    public ReeaDAslPath reeaDAslReeaTSoggettoResidenzaResidenza() {
        if (_reeaDAslReeaTSoggettoResidenzaResidenza == null)
            _reeaDAslReeaTSoggettoResidenzaResidenza = new ReeaDAslPath(this, Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO_RESIDENZA_RESIDENZA, null);

        return _reeaDAslReeaTSoggettoResidenzaResidenza;
    }

    private transient ReeaDAslPath _reeaDAslReeaTSoggetto33;

    /**
     * Get the implicit join path to the <code>reea.reea_d_asl</code> table, via
     * the <code>reea_d_asl_reea_t_soggetto33</code> key.
     */
    public ReeaDAslPath reeaDAslReeaTSoggetto33() {
        if (_reeaDAslReeaTSoggetto33 == null)
            _reeaDAslReeaTSoggetto33 = new ReeaDAslPath(this, Keys.REEA_T_SOGGETTO__REEA_D_ASL_REEA_T_SOGGETTO33, null);

        return _reeaDAslReeaTSoggetto33;
    }

    private transient ReeaDInserimentoTipoPath _reeaDInserimentoTipo;

    /**
     * Get the implicit join path to the
     * <code>reea.reea_d_inserimento_tipo</code> table.
     */
    public ReeaDInserimentoTipoPath reeaDInserimentoTipo() {
        if (_reeaDInserimentoTipo == null)
            _reeaDInserimentoTipo = new ReeaDInserimentoTipoPath(this, Keys.REEA_T_SOGGETTO__REEA_D_INSERIMENTO_TIPO_REEA_T_SOGGETTO, null);

        return _reeaDInserimentoTipo;
    }

    private transient ReeaDFontePath _reeaDFonte;

    /**
     * Get the implicit join path to the <code>reea.reea_d_fonte</code> table.
     */
    public ReeaDFontePath reeaDFonte() {
        if (_reeaDFonte == null)
            _reeaDFonte = new ReeaDFontePath(this, Keys.REEA_T_SOGGETTO__REEA_D_FONTE_REEA_T_SOGGETTO, null);

        return _reeaDFonte;
    }

    private transient ReeaDSoggettoStatoPath _reeaDSoggettoStato;

    /**
     * Get the implicit join path to the <code>reea.reea_d_soggetto_stato</code>
     * table.
     */
    public ReeaDSoggettoStatoPath reeaDSoggettoStato() {
        if (_reeaDSoggettoStato == null)
            _reeaDSoggettoStato = new ReeaDSoggettoStatoPath(this, Keys.REEA_T_SOGGETTO__REEA_D_SOGGETTO_STATO_REEA_T_SOGGETTO, null);

        return _reeaDSoggettoStato;
    }

    private transient ReeaSSoggettoPath _reeaSSoggetto;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_s_soggetto</code> table
     */
    public ReeaSSoggettoPath reeaSSoggetto() {
        if (_reeaSSoggetto == null)
            _reeaSSoggetto = new ReeaSSoggettoPath(this, null, Keys.REEA_S_SOGGETTO__REEA_T_SOGGETTO_REEA_S_SOGGETTO.getInverseKey());

        return _reeaSSoggetto;
    }

    private transient ReeaTAdesionePath _reeaTAdesione;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_t_adesione</code> table
     */
    public ReeaTAdesionePath reeaTAdesione() {
        if (_reeaTAdesione == null)
            _reeaTAdesione = new ReeaTAdesionePath(this, null, Keys.REEA_T_ADESIONE__REEA_T_SOGGETTO_REEA_T_ADESIONE.getInverseKey());

        return _reeaTAdesione;
    }

    @Override
    public ReeaTSoggetto as(String alias) {
        return new ReeaTSoggetto(DSL.name(alias), this);
    }

    @Override
    public ReeaTSoggetto as(Name alias) {
        return new ReeaTSoggetto(alias, this);
    }

    @Override
    public ReeaTSoggetto as(Table<?> alias) {
        return new ReeaTSoggetto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTSoggetto rename(String name) {
        return new ReeaTSoggetto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTSoggetto rename(Name name) {
        return new ReeaTSoggetto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTSoggetto rename(Table<?> name) {
        return new ReeaTSoggetto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto where(Condition condition) {
        return new ReeaTSoggetto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTSoggetto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTSoggetto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTSoggetto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTSoggetto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTSoggetto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
