/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.records.ReeaDAttestazioneSanitariaStatoRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * può valere SI/NO/IN CORSO
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDAttestazioneSanitariaStato extends TableImpl<ReeaDAttestazioneSanitariaStatoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>reea.reea_d_attestazione_sanitaria_stato</code>
     */
    public static final ReeaDAttestazioneSanitariaStato REEA_D_ATTESTAZIONE_SANITARIA_STATO = new ReeaDAttestazioneSanitariaStato();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDAttestazioneSanitariaStatoRecord> getRecordType() {
        return ReeaDAttestazioneSanitariaStatoRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.att_sanitaria_stato_id</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, Integer> ATT_SANITARIA_STATO_ID = createField(DSL.name("att_sanitaria_stato_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.att_sanitaria_stato_cod</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, String> ATT_SANITARIA_STATO_COD = createField(DSL.name("att_sanitaria_stato_cod"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.att_sanitaria_stato_desc</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, String> ATT_SANITARIA_STATO_DESC = createField(DSL.name("att_sanitaria_stato_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.validita_inizio</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.validita_fine</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.data_creazione</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.data_modifica</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.data_cancellazione</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.utente_creazione</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.utente_modifica</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_d_attestazione_sanitaria_stato.utente_cancellazione</code>.
     */
    public final TableField<ReeaDAttestazioneSanitariaStatoRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaDAttestazioneSanitariaStato(Name alias, Table<ReeaDAttestazioneSanitariaStatoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDAttestazioneSanitariaStato(Name alias, Table<ReeaDAttestazioneSanitariaStatoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("può valere SI/NO/IN CORSO"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_attestazione_sanitaria_stato</code>
     * table reference
     */
    public ReeaDAttestazioneSanitariaStato(String alias) {
        this(DSL.name(alias), REEA_D_ATTESTAZIONE_SANITARIA_STATO);
    }

    /**
     * Create an aliased <code>reea.reea_d_attestazione_sanitaria_stato</code>
     * table reference
     */
    public ReeaDAttestazioneSanitariaStato(Name alias) {
        this(alias, REEA_D_ATTESTAZIONE_SANITARIA_STATO);
    }

    /**
     * Create a <code>reea.reea_d_attestazione_sanitaria_stato</code> table
     * reference
     */
    public ReeaDAttestazioneSanitariaStato() {
        this(DSL.name("reea_d_attestazione_sanitaria_stato"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public Identity<ReeaDAttestazioneSanitariaStatoRecord, Integer> getIdentity() {
        return (Identity<ReeaDAttestazioneSanitariaStatoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDAttestazioneSanitariaStatoRecord> getPrimaryKey() {
        return Keys.REEA_D_ATTESTAZIONE_SANITARIA_STATO_PKEY;
    }

    @Override
    public ReeaDAttestazioneSanitariaStato as(String alias) {
        return new ReeaDAttestazioneSanitariaStato(DSL.name(alias), this);
    }

    @Override
    public ReeaDAttestazioneSanitariaStato as(Name alias) {
        return new ReeaDAttestazioneSanitariaStato(alias, this);
    }

    @Override
    public ReeaDAttestazioneSanitariaStato as(Table<?> alias) {
        return new ReeaDAttestazioneSanitariaStato(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato rename(String name) {
        return new ReeaDAttestazioneSanitariaStato(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato rename(Name name) {
        return new ReeaDAttestazioneSanitariaStato(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato rename(Table<?> name) {
        return new ReeaDAttestazioneSanitariaStato(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato where(Condition condition) {
        return new ReeaDAttestazioneSanitariaStato(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDAttestazioneSanitariaStato where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDAttestazioneSanitariaStato where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDAttestazioneSanitariaStato where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDAttestazioneSanitariaStato where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDAttestazioneSanitariaStato whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
