/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.records.ReeaDRegistroSpresalAnamnesiMansioneRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * valorizza di default
 * reea_d_registro_spresal_anamnesi.occupazione_mansione_crpt
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRegistroSpresalAnamnesiMansione extends TableImpl<ReeaDRegistroSpresalAnamnesiMansioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione</code>
     */
    public static final ReeaDRegistroSpresalAnamnesiMansione REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE = new ReeaDRegistroSpresalAnamnesiMansione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDRegistroSpresalAnamnesiMansioneRecord> getRecordType() {
        return ReeaDRegistroSpresalAnamnesiMansioneRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.mansione_id</code>.
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, Integer> MANSIONE_ID = createField(DSL.name("mansione_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.mansione_cod</code>.
     * codice
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, String> MANSIONE_COD = createField(DSL.name("mansione_cod"), SQLDataType.CLOB.nullable(false), this, "codice");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.mansione_desc</code>.
     * descrizione
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, String> MANSIONE_DESC = createField(DSL.name("mansione_desc"), SQLDataType.CLOB, this, "descrizione");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.validita_inizio</code>.
     * inizio validità record
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "inizio validità record");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.validita_fine</code>.
     * fine validità record
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "fine validità record");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.data_creazione</code>.
     * data creazione record
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "data creazione record");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.data_modifica</code>.
     * data modifica record
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "data modifica record");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.data_cancellazione</code>.
     * data cancellazione record
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "data cancellazione record");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.utente_creazione</code>.
     * utente creazione
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB.nullable(false), this, "utente creazione");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.utente_modifica</code>.
     * utente modifica
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB.nullable(false), this, "utente modifica");

    /**
     * The column
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione.utente_cancellazione</code>.
     * utente cancellazione
     */
    public final TableField<ReeaDRegistroSpresalAnamnesiMansioneRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "utente cancellazione");

    private ReeaDRegistroSpresalAnamnesiMansione(Name alias, Table<ReeaDRegistroSpresalAnamnesiMansioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDRegistroSpresalAnamnesiMansione(Name alias, Table<ReeaDRegistroSpresalAnamnesiMansioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("valorizza di default reea_d_registro_spresal_anamnesi.occupazione_mansione_crpt"), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione</code> table
     * reference
     */
    public ReeaDRegistroSpresalAnamnesiMansione(String alias) {
        this(DSL.name(alias), REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE);
    }

    /**
     * Create an aliased
     * <code>reea.reea_d_registro_spresal_anamnesi_mansione</code> table
     * reference
     */
    public ReeaDRegistroSpresalAnamnesiMansione(Name alias) {
        this(alias, REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE);
    }

    /**
     * Create a <code>reea.reea_d_registro_spresal_anamnesi_mansione</code>
     * table reference
     */
    public ReeaDRegistroSpresalAnamnesiMansione() {
        this(DSL.name("reea_d_registro_spresal_anamnesi_mansione"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE_1);
    }

    @Override
    public Identity<ReeaDRegistroSpresalAnamnesiMansioneRecord, Integer> getIdentity() {
        return (Identity<ReeaDRegistroSpresalAnamnesiMansioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDRegistroSpresalAnamnesiMansioneRecord> getPrimaryKey() {
        return Keys.REEA_D_REGISTRO_SPRESAL_ANAMNESI_MANSIONE_PKEY;
    }

    @Override
    public ReeaDRegistroSpresalAnamnesiMansione as(String alias) {
        return new ReeaDRegistroSpresalAnamnesiMansione(DSL.name(alias), this);
    }

    @Override
    public ReeaDRegistroSpresalAnamnesiMansione as(Name alias) {
        return new ReeaDRegistroSpresalAnamnesiMansione(alias, this);
    }

    @Override
    public ReeaDRegistroSpresalAnamnesiMansione as(Table<?> alias) {
        return new ReeaDRegistroSpresalAnamnesiMansione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione rename(String name) {
        return new ReeaDRegistroSpresalAnamnesiMansione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione rename(Name name) {
        return new ReeaDRegistroSpresalAnamnesiMansione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione rename(Table<?> name) {
        return new ReeaDRegistroSpresalAnamnesiMansione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione where(Condition condition) {
        return new ReeaDRegistroSpresalAnamnesiMansione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegistroSpresalAnamnesiMansione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegistroSpresalAnamnesiMansione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegistroSpresalAnamnesiMansione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegistroSpresalAnamnesiMansione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegistroSpresalAnamnesiMansione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
