/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaTFileImpatto.ReeaTFileImpattoPath;
import it.csi.registry.jooq.tables.records.ReeaDFileOperazioneTipoRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * INSERT, UPDATE, DELETE (LOGICA)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDFileOperazioneTipo extends TableImpl<ReeaDFileOperazioneTipoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_d_file_operazione_tipo</code>
     */
    public static final ReeaDFileOperazioneTipo REEA_D_FILE_OPERAZIONE_TIPO = new ReeaDFileOperazioneTipo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDFileOperazioneTipoRecord> getRecordType() {
        return ReeaDFileOperazioneTipoRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.operazione_tipo_id</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, Integer> OPERAZIONE_TIPO_ID = createField(DSL.name("operazione_tipo_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.operazione_tipo_cod</code>. Codice
     * del tipo di operazione
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, String> OPERAZIONE_TIPO_COD = createField(DSL.name("operazione_tipo_cod"), SQLDataType.CLOB.nullable(false), this, "Codice del tipo di operazione");

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.operazione_tipo_desc</code>.
     * Descrizione tipo operazione
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, String> OPERAZIONE_TIPO_DESC = createField(DSL.name("operazione_tipo_desc"), SQLDataType.CLOB, this, "Descrizione tipo operazione");

    /**
     * The column <code>reea.reea_d_file_operazione_tipo.validita_inizio</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_file_operazione_tipo.validita_fine</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_file_operazione_tipo.data_creazione</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_file_operazione_tipo.data_modifica</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.data_cancellazione</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.utente_creazione</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_file_operazione_tipo.utente_modifica</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_d_file_operazione_tipo.utente_cancellazione</code>.
     */
    public final TableField<ReeaDFileOperazioneTipoRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaDFileOperazioneTipo(Name alias, Table<ReeaDFileOperazioneTipoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDFileOperazioneTipo(Name alias, Table<ReeaDFileOperazioneTipoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("INSERT, UPDATE, DELETE (LOGICA)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_file_operazione_tipo</code> table
     * reference
     */
    public ReeaDFileOperazioneTipo(String alias) {
        this(DSL.name(alias), REEA_D_FILE_OPERAZIONE_TIPO);
    }

    /**
     * Create an aliased <code>reea.reea_d_file_operazione_tipo</code> table
     * reference
     */
    public ReeaDFileOperazioneTipo(Name alias) {
        this(alias, REEA_D_FILE_OPERAZIONE_TIPO);
    }

    /**
     * Create a <code>reea.reea_d_file_operazione_tipo</code> table reference
     */
    public ReeaDFileOperazioneTipo() {
        this(DSL.name("reea_d_file_operazione_tipo"), null);
    }

    public <O extends Record> ReeaDFileOperazioneTipo(Table<O> path, ForeignKey<O, ReeaDFileOperazioneTipoRecord> childPath, InverseForeignKey<O, ReeaDFileOperazioneTipoRecord> parentPath) {
        super(path, childPath, parentPath, REEA_D_FILE_OPERAZIONE_TIPO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaDFileOperazioneTipoPath extends ReeaDFileOperazioneTipo implements Path<ReeaDFileOperazioneTipoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaDFileOperazioneTipoPath(Table<O> path, ForeignKey<O, ReeaDFileOperazioneTipoRecord> childPath, InverseForeignKey<O, ReeaDFileOperazioneTipoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaDFileOperazioneTipoPath(Name alias, Table<ReeaDFileOperazioneTipoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaDFileOperazioneTipoPath as(String alias) {
            return new ReeaDFileOperazioneTipoPath(DSL.name(alias), this);
        }

        @Override
        public ReeaDFileOperazioneTipoPath as(Name alias) {
            return new ReeaDFileOperazioneTipoPath(alias, this);
        }

        @Override
        public ReeaDFileOperazioneTipoPath as(Table<?> alias) {
            return new ReeaDFileOperazioneTipoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public Identity<ReeaDFileOperazioneTipoRecord, Integer> getIdentity() {
        return (Identity<ReeaDFileOperazioneTipoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDFileOperazioneTipoRecord> getPrimaryKey() {
        return Keys.REEA_D_FILE_OPERAZIONE_TIPO_PKEY;
    }

    private transient ReeaTFileImpattoPath _reeaTFileImpatto;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_t_file_impatto</code> table
     */
    public ReeaTFileImpattoPath reeaTFileImpatto() {
        if (_reeaTFileImpatto == null)
            _reeaTFileImpatto = new ReeaTFileImpattoPath(this, null, Keys.REEA_T_FILE_IMPATTO__FK_REEA_T_FILE_IMPATTO_TIPO.getInverseKey());

        return _reeaTFileImpatto;
    }

    @Override
    public ReeaDFileOperazioneTipo as(String alias) {
        return new ReeaDFileOperazioneTipo(DSL.name(alias), this);
    }

    @Override
    public ReeaDFileOperazioneTipo as(Name alias) {
        return new ReeaDFileOperazioneTipo(alias, this);
    }

    @Override
    public ReeaDFileOperazioneTipo as(Table<?> alias) {
        return new ReeaDFileOperazioneTipo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFileOperazioneTipo rename(String name) {
        return new ReeaDFileOperazioneTipo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFileOperazioneTipo rename(Name name) {
        return new ReeaDFileOperazioneTipo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFileOperazioneTipo rename(Table<?> name) {
        return new ReeaDFileOperazioneTipo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo where(Condition condition) {
        return new ReeaDFileOperazioneTipo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFileOperazioneTipo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFileOperazioneTipo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFileOperazioneTipo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFileOperazioneTipo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFileOperazioneTipo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
