/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaLFileElaborazione.ReeaLFileElaborazionePath;
import it.csi.registry.jooq.tables.records.ReeaLFileElaborazioneErroreRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaLFileElaborazioneErrore extends TableImpl<ReeaLFileElaborazioneErroreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>reea.reea_l_file_elaborazione_errore</code>
     */
    public static final ReeaLFileElaborazioneErrore REEA_L_FILE_ELABORAZIONE_ERRORE = new ReeaLFileElaborazioneErrore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaLFileElaborazioneErroreRecord> getRecordType() {
        return ReeaLFileElaborazioneErroreRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.elaborazione_errore_id</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, Integer> ELABORAZIONE_ERRORE_ID = createField(DSL.name("elaborazione_errore_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.elaborazione_id</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, Integer> ELABORAZIONE_ID = createField(DSL.name("elaborazione_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.codice_errore</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> CODICE_ERRORE = createField(DSL.name("codice_errore"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.descrizione_errore</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> DESCRIZIONE_ERRORE = createField(DSL.name("descrizione_errore"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.contenuto_riga_raw</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, byte[]> CONTENUTO_RIGA_RAW = createField(DSL.name("contenuto_riga_raw"), SQLDataType.BLOB, this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.validita_inizio</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.validita_fine</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.data_creazione</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.data_modifica</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.data_cancellazione</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.utente_creazione</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.utente_modifica</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.utente_cancellazione</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_l_file_elaborazione_errore.cognome</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> COGNOME = createField(DSL.name("cognome"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>reea.reea_l_file_elaborazione_errore.nome</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> NOME = createField(DSL.name("nome"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.data_nascita</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, LocalDate> DATA_NASCITA = createField(DSL.name("data_nascita"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>reea.reea_l_file_elaborazione_errore.sesso</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> SESSO = createField(DSL.name("sesso"), SQLDataType.CHAR(1), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.codice_fiscale</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> CODICE_FISCALE = createField(DSL.name("codice_fiscale"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.target_tabella_nome</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, String> TARGET_TABELLA_NOME = createField(DSL.name("target_tabella_nome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_l_file_elaborazione_errore.target_record_id</code>.
     */
    public final TableField<ReeaLFileElaborazioneErroreRecord, Integer> TARGET_RECORD_ID = createField(DSL.name("target_record_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ReeaLFileElaborazioneErrore(Name alias, Table<ReeaLFileElaborazioneErroreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaLFileElaborazioneErrore(Name alias, Table<ReeaLFileElaborazioneErroreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_l_file_elaborazione_errore</code> table
     * reference
     */
    public ReeaLFileElaborazioneErrore(String alias) {
        this(DSL.name(alias), REEA_L_FILE_ELABORAZIONE_ERRORE);
    }

    /**
     * Create an aliased <code>reea.reea_l_file_elaborazione_errore</code> table
     * reference
     */
    public ReeaLFileElaborazioneErrore(Name alias) {
        this(alias, REEA_L_FILE_ELABORAZIONE_ERRORE);
    }

    /**
     * Create a <code>reea.reea_l_file_elaborazione_errore</code> table
     * reference
     */
    public ReeaLFileElaborazioneErrore() {
        this(DSL.name("reea_l_file_elaborazione_errore"), null);
    }

    public <O extends Record> ReeaLFileElaborazioneErrore(Table<O> path, ForeignKey<O, ReeaLFileElaborazioneErroreRecord> childPath, InverseForeignKey<O, ReeaLFileElaborazioneErroreRecord> parentPath) {
        super(path, childPath, parentPath, REEA_L_FILE_ELABORAZIONE_ERRORE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaLFileElaborazioneErrorePath extends ReeaLFileElaborazioneErrore implements Path<ReeaLFileElaborazioneErroreRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaLFileElaborazioneErrorePath(Table<O> path, ForeignKey<O, ReeaLFileElaborazioneErroreRecord> childPath, InverseForeignKey<O, ReeaLFileElaborazioneErroreRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaLFileElaborazioneErrorePath(Name alias, Table<ReeaLFileElaborazioneErroreRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaLFileElaborazioneErrorePath as(String alias) {
            return new ReeaLFileElaborazioneErrorePath(DSL.name(alias), this);
        }

        @Override
        public ReeaLFileElaborazioneErrorePath as(Name alias) {
            return new ReeaLFileElaborazioneErrorePath(alias, this);
        }

        @Override
        public ReeaLFileElaborazioneErrorePath as(Table<?> alias) {
            return new ReeaLFileElaborazioneErrorePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_L_FILE_ELABORAZIONE_ERRORE_1);
    }

    @Override
    public Identity<ReeaLFileElaborazioneErroreRecord, Integer> getIdentity() {
        return (Identity<ReeaLFileElaborazioneErroreRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaLFileElaborazioneErroreRecord> getPrimaryKey() {
        return Keys.REEA_L_FILE_ELABORAZIONE_ERRORE_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaLFileElaborazioneErroreRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_L_FILE_ELABORAZIONE_ERRORE__FK_REEA_L_IMPORT_ERRORE_ELAB);
    }

    private transient ReeaLFileElaborazionePath _reeaLFileElaborazione;

    /**
     * Get the implicit join path to the
     * <code>reea.reea_l_file_elaborazione</code> table.
     */
    public ReeaLFileElaborazionePath reeaLFileElaborazione() {
        if (_reeaLFileElaborazione == null)
            _reeaLFileElaborazione = new ReeaLFileElaborazionePath(this, Keys.REEA_L_FILE_ELABORAZIONE_ERRORE__FK_REEA_L_IMPORT_ERRORE_ELAB, null);

        return _reeaLFileElaborazione;
    }

    @Override
    public ReeaLFileElaborazioneErrore as(String alias) {
        return new ReeaLFileElaborazioneErrore(DSL.name(alias), this);
    }

    @Override
    public ReeaLFileElaborazioneErrore as(Name alias) {
        return new ReeaLFileElaborazioneErrore(alias, this);
    }

    @Override
    public ReeaLFileElaborazioneErrore as(Table<?> alias) {
        return new ReeaLFileElaborazioneErrore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaLFileElaborazioneErrore rename(String name) {
        return new ReeaLFileElaborazioneErrore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaLFileElaborazioneErrore rename(Name name) {
        return new ReeaLFileElaborazioneErrore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaLFileElaborazioneErrore rename(Table<?> name) {
        return new ReeaLFileElaborazioneErrore(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore where(Condition condition) {
        return new ReeaLFileElaborazioneErrore(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaLFileElaborazioneErrore where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaLFileElaborazioneErrore where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaLFileElaborazioneErrore where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaLFileElaborazioneErrore where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaLFileElaborazioneErrore whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
