/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaDRuolo.ReeaDRuoloPath;
import it.csi.registry.jooq.tables.ReeaTUtente.ReeaTUtentePath;
import it.csi.registry.jooq.tables.records.ReeaRUtenteRuoloRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica
 * Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaRUtenteRuolo extends TableImpl<ReeaRUtenteRuoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_r_utente_ruolo</code>
     */
    public static final ReeaRUtenteRuolo REEA_R_UTENTE_RUOLO = new ReeaRUtenteRuolo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaRUtenteRuoloRecord> getRecordType() {
        return ReeaRUtenteRuoloRecord.class;
    }

    /**
     * The column <code>reea.reea_r_utente_ruolo.utente_ruolo_id</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, Integer> UTENTE_RUOLO_ID = createField(DSL.name("utente_ruolo_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.utente_id</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, Integer> UTENTE_ID = createField(DSL.name("utente_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.ruolo_id</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, Integer> RUOLO_ID = createField(DSL.name("ruolo_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.validita_inizio</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.validita_fine</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.data_creazione</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.data_modifica</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.data_cancellazione</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.utente_creazione</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.utente_modifica</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_r_utente_ruolo.utente_cancellazione</code>.
     */
    public final TableField<ReeaRUtenteRuoloRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaRUtenteRuolo(Name alias, Table<ReeaRUtenteRuoloRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaRUtenteRuolo(Name alias, Table<ReeaRUtenteRuoloRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_r_utente_ruolo</code> table reference
     */
    public ReeaRUtenteRuolo(String alias) {
        this(DSL.name(alias), REEA_R_UTENTE_RUOLO);
    }

    /**
     * Create an aliased <code>reea.reea_r_utente_ruolo</code> table reference
     */
    public ReeaRUtenteRuolo(Name alias) {
        this(alias, REEA_R_UTENTE_RUOLO);
    }

    /**
     * Create a <code>reea.reea_r_utente_ruolo</code> table reference
     */
    public ReeaRUtenteRuolo() {
        this(DSL.name("reea_r_utente_ruolo"), null);
    }

    public <O extends Record> ReeaRUtenteRuolo(Table<O> path, ForeignKey<O, ReeaRUtenteRuoloRecord> childPath, InverseForeignKey<O, ReeaRUtenteRuoloRecord> parentPath) {
        super(path, childPath, parentPath, REEA_R_UTENTE_RUOLO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaRUtenteRuoloPath extends ReeaRUtenteRuolo implements Path<ReeaRUtenteRuoloRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaRUtenteRuoloPath(Table<O> path, ForeignKey<O, ReeaRUtenteRuoloRecord> childPath, InverseForeignKey<O, ReeaRUtenteRuoloRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaRUtenteRuoloPath(Name alias, Table<ReeaRUtenteRuoloRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaRUtenteRuoloPath as(String alias) {
            return new ReeaRUtenteRuoloPath(DSL.name(alias), this);
        }

        @Override
        public ReeaRUtenteRuoloPath as(Name alias) {
            return new ReeaRUtenteRuoloPath(alias, this);
        }

        @Override
        public ReeaRUtenteRuoloPath as(Table<?> alias) {
            return new ReeaRUtenteRuoloPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_R_UTENTE_RUOLO_1, Indexes.IDX_REEA_R_UTENTE_RUOLO_2);
    }

    @Override
    public Identity<ReeaRUtenteRuoloRecord, Integer> getIdentity() {
        return (Identity<ReeaRUtenteRuoloRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaRUtenteRuoloRecord> getPrimaryKey() {
        return Keys.REEA_R_UTENTE_RUOLO_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaRUtenteRuoloRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_T_UTENTE_ID_FKEY, Keys.REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_D_RUOLO_ID_FKEY);
    }

    private transient ReeaTUtentePath _reeaTUtente;

    /**
     * Get the implicit join path to the <code>reea.reea_t_utente</code> table.
     */
    public ReeaTUtentePath reeaTUtente() {
        if (_reeaTUtente == null)
            _reeaTUtente = new ReeaTUtentePath(this, Keys.REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_T_UTENTE_ID_FKEY, null);

        return _reeaTUtente;
    }

    private transient ReeaDRuoloPath _reeaDRuolo;

    /**
     * Get the implicit join path to the <code>reea.reea_d_ruolo</code> table.
     */
    public ReeaDRuoloPath reeaDRuolo() {
        if (_reeaDRuolo == null)
            _reeaDRuolo = new ReeaDRuoloPath(this, Keys.REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_D_RUOLO_ID_FKEY, null);

        return _reeaDRuolo;
    }

    @Override
    public ReeaRUtenteRuolo as(String alias) {
        return new ReeaRUtenteRuolo(DSL.name(alias), this);
    }

    @Override
    public ReeaRUtenteRuolo as(Name alias) {
        return new ReeaRUtenteRuolo(alias, this);
    }

    @Override
    public ReeaRUtenteRuolo as(Table<?> alias) {
        return new ReeaRUtenteRuolo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteRuolo rename(String name) {
        return new ReeaRUtenteRuolo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteRuolo rename(Name name) {
        return new ReeaRUtenteRuolo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteRuolo rename(Table<?> name) {
        return new ReeaRUtenteRuolo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo where(Condition condition) {
        return new ReeaRUtenteRuolo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteRuolo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteRuolo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteRuolo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteRuolo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteRuolo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
