/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaDProfiloTipo.ReeaDProfiloTipoPath;
import it.csi.registry.jooq.tables.ReeaRProfiloCampoMascherato.ReeaRProfiloCampoMascheratoPath;
import it.csi.registry.jooq.tables.ReeaRProfiloFunzionalita.ReeaRProfiloFunzionalitaPath;
import it.csi.registry.jooq.tables.ReeaRRuoloProfilo.ReeaRRuoloProfiloPath;
import it.csi.registry.jooq.tables.ReeaRUtenteProfilo.ReeaRUtenteProfiloPath;
import it.csi.registry.jooq.tables.records.ReeaDProfiloRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Profili funzionali (raggruppamenti logici di permessi).  Fonte: PDF Specifica
 * Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_PROFILO.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDProfilo extends TableImpl<ReeaDProfiloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_d_profilo</code>
     */
    public static final ReeaDProfilo REEA_D_PROFILO = new ReeaDProfilo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDProfiloRecord> getRecordType() {
        return ReeaDProfiloRecord.class;
    }

    /**
     * The column <code>reea.reea_d_profilo.profilo_id</code>.
     */
    public final TableField<ReeaDProfiloRecord, Integer> PROFILO_ID = createField(DSL.name("profilo_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_d_profilo.profilo_cod</code>.
     */
    public final TableField<ReeaDProfiloRecord, String> PROFILO_COD = createField(DSL.name("profilo_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_profilo.profilo_desc</code>.
     */
    public final TableField<ReeaDProfiloRecord, String> PROFILO_DESC = createField(DSL.name("profilo_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_profilo.validita_inizio</code>.
     */
    public final TableField<ReeaDProfiloRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_profilo.validita_fine</code>.
     */
    public final TableField<ReeaDProfiloRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_profilo.data_creazione</code>.
     */
    public final TableField<ReeaDProfiloRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_profilo.data_modifica</code>.
     */
    public final TableField<ReeaDProfiloRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_profilo.data_cancellazione</code>.
     */
    public final TableField<ReeaDProfiloRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_profilo.utente_creazione</code>.
     */
    public final TableField<ReeaDProfiloRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_profilo.utente_modifica</code>.
     */
    public final TableField<ReeaDProfiloRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_profilo.utente_cancellazione</code>.
     */
    public final TableField<ReeaDProfiloRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_profilo.profilo_tipo_id</code>.
     */
    public final TableField<ReeaDProfiloRecord, Integer> PROFILO_TIPO_ID = createField(DSL.name("profilo_tipo_id"), SQLDataType.INTEGER, this, "");

    private ReeaDProfilo(Name alias, Table<ReeaDProfiloRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDProfilo(Name alias, Table<ReeaDProfiloRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Profili funzionali (raggruppamenti logici di permessi).  Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_PROFILO."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_profilo</code> table reference
     */
    public ReeaDProfilo(String alias) {
        this(DSL.name(alias), REEA_D_PROFILO);
    }

    /**
     * Create an aliased <code>reea.reea_d_profilo</code> table reference
     */
    public ReeaDProfilo(Name alias) {
        this(alias, REEA_D_PROFILO);
    }

    /**
     * Create a <code>reea.reea_d_profilo</code> table reference
     */
    public ReeaDProfilo() {
        this(DSL.name("reea_d_profilo"), null);
    }

    public <O extends Record> ReeaDProfilo(Table<O> path, ForeignKey<O, ReeaDProfiloRecord> childPath, InverseForeignKey<O, ReeaDProfiloRecord> parentPath) {
        super(path, childPath, parentPath, REEA_D_PROFILO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaDProfiloPath extends ReeaDProfilo implements Path<ReeaDProfiloRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaDProfiloPath(Table<O> path, ForeignKey<O, ReeaDProfiloRecord> childPath, InverseForeignKey<O, ReeaDProfiloRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaDProfiloPath(Name alias, Table<ReeaDProfiloRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaDProfiloPath as(String alias) {
            return new ReeaDProfiloPath(DSL.name(alias), this);
        }

        @Override
        public ReeaDProfiloPath as(Name alias) {
            return new ReeaDProfiloPath(alias, this);
        }

        @Override
        public ReeaDProfiloPath as(Table<?> alias) {
            return new ReeaDProfiloPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public Identity<ReeaDProfiloRecord, Integer> getIdentity() {
        return (Identity<ReeaDProfiloRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDProfiloRecord> getPrimaryKey() {
        return Keys.REEA_D_PROFILO_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaDProfiloRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_D_PROFILO__REEA_D_PROFILO_TIPO_REEA_C_PARAMETRO);
    }

    private transient ReeaDProfiloTipoPath _reeaDProfiloTipo;

    /**
     * Get the implicit join path to the <code>reea.reea_d_profilo_tipo</code>
     * table.
     */
    public ReeaDProfiloTipoPath reeaDProfiloTipo() {
        if (_reeaDProfiloTipo == null)
            _reeaDProfiloTipo = new ReeaDProfiloTipoPath(this, Keys.REEA_D_PROFILO__REEA_D_PROFILO_TIPO_REEA_C_PARAMETRO, null);

        return _reeaDProfiloTipo;
    }

    private transient ReeaRProfiloCampoMascheratoPath _reeaRProfiloCampoMascherato;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_profilo_campo_mascherato</code> table
     */
    public ReeaRProfiloCampoMascheratoPath reeaRProfiloCampoMascherato() {
        if (_reeaRProfiloCampoMascherato == null)
            _reeaRProfiloCampoMascherato = new ReeaRProfiloCampoMascheratoPath(this, null, Keys.REEA_R_PROFILO_CAMPO_MASCHERATO__REEA_R_PROFILO_CAMPO_MASCHERATO_REEA_D_PROFILO_ID_FKEY.getInverseKey());

        return _reeaRProfiloCampoMascherato;
    }

    private transient ReeaRProfiloFunzionalitaPath _reeaRProfiloFunzionalita;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_profilo_funzionalita</code> table
     */
    public ReeaRProfiloFunzionalitaPath reeaRProfiloFunzionalita() {
        if (_reeaRProfiloFunzionalita == null)
            _reeaRProfiloFunzionalita = new ReeaRProfiloFunzionalitaPath(this, null, Keys.REEA_R_PROFILO_FUNZIONALITA__REEA_R_PROFILO_FUNZIONE_REEA_D_PROFILO_ID_FKEY.getInverseKey());

        return _reeaRProfiloFunzionalita;
    }

    private transient ReeaRRuoloProfiloPath _reeaRRuoloProfilo;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_ruolo_profilo</code> table
     */
    public ReeaRRuoloProfiloPath reeaRRuoloProfilo() {
        if (_reeaRRuoloProfilo == null)
            _reeaRRuoloProfilo = new ReeaRRuoloProfiloPath(this, null, Keys.REEA_R_RUOLO_PROFILO__REEA_R_RUOLO_PROFILO_REEA_D_PROFILO_ID_FKEY.getInverseKey());

        return _reeaRRuoloProfilo;
    }

    private transient ReeaRUtenteProfiloPath _reeaRUtenteProfilo;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_utente_profilo</code> table
     */
    public ReeaRUtenteProfiloPath reeaRUtenteProfilo() {
        if (_reeaRUtenteProfilo == null)
            _reeaRUtenteProfilo = new ReeaRUtenteProfiloPath(this, null, Keys.REEA_R_UTENTE_PROFILO__REEA_R_UTENTE_PROFILO_REEA_D_PROFILO_ID_FKEY.getInverseKey());

        return _reeaRUtenteProfilo;
    }

    @Override
    public ReeaDProfilo as(String alias) {
        return new ReeaDProfilo(DSL.name(alias), this);
    }

    @Override
    public ReeaDProfilo as(Name alias) {
        return new ReeaDProfilo(alias, this);
    }

    @Override
    public ReeaDProfilo as(Table<?> alias) {
        return new ReeaDProfilo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDProfilo rename(String name) {
        return new ReeaDProfilo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDProfilo rename(Name name) {
        return new ReeaDProfilo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDProfilo rename(Table<?> name) {
        return new ReeaDProfilo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo where(Condition condition) {
        return new ReeaDProfilo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDProfilo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDProfilo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDProfilo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDProfilo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDProfilo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
