/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaTCollocazione.ReeaTCollocazionePath;
import it.csi.registry.jooq.tables.ReeaTUtente.ReeaTUtentePath;
import it.csi.registry.jooq.tables.records.ReeaRUtenteCollocazioneRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica
 * Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaRUtenteCollocazione extends TableImpl<ReeaRUtenteCollocazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_r_utente_collocazione</code>
     */
    public static final ReeaRUtenteCollocazione REEA_R_UTENTE_COLLOCAZIONE = new ReeaRUtenteCollocazione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaRUtenteCollocazioneRecord> getRecordType() {
        return ReeaRUtenteCollocazioneRecord.class;
    }

    /**
     * The column <code>reea.reea_r_utente_collocazione.utente_ruolo_id</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, Integer> UTENTE_RUOLO_ID = createField(DSL.name("utente_ruolo_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.utente_id</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, Integer> UTENTE_ID = createField(DSL.name("utente_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.collocazione_id</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, Integer> COLLOCAZIONE_ID = createField(DSL.name("collocazione_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.validita_inizio</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.validita_fine</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.data_creazione</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.data_modifica</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_r_utente_collocazione.data_cancellazione</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.utente_creazione</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_r_utente_collocazione.utente_modifica</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_r_utente_collocazione.utente_cancellazione</code>.
     */
    public final TableField<ReeaRUtenteCollocazioneRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaRUtenteCollocazione(Name alias, Table<ReeaRUtenteCollocazioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaRUtenteCollocazione(Name alias, Table<ReeaRUtenteCollocazioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Associazione N:M che lega un Utente ai suoi Ruoli.  Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_R_RUOLO_UTENTE."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_r_utente_collocazione</code> table
     * reference
     */
    public ReeaRUtenteCollocazione(String alias) {
        this(DSL.name(alias), REEA_R_UTENTE_COLLOCAZIONE);
    }

    /**
     * Create an aliased <code>reea.reea_r_utente_collocazione</code> table
     * reference
     */
    public ReeaRUtenteCollocazione(Name alias) {
        this(alias, REEA_R_UTENTE_COLLOCAZIONE);
    }

    /**
     * Create a <code>reea.reea_r_utente_collocazione</code> table reference
     */
    public ReeaRUtenteCollocazione() {
        this(DSL.name("reea_r_utente_collocazione"), null);
    }

    public <O extends Record> ReeaRUtenteCollocazione(Table<O> path, ForeignKey<O, ReeaRUtenteCollocazioneRecord> childPath, InverseForeignKey<O, ReeaRUtenteCollocazioneRecord> parentPath) {
        super(path, childPath, parentPath, REEA_R_UTENTE_COLLOCAZIONE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaRUtenteCollocazionePath extends ReeaRUtenteCollocazione implements Path<ReeaRUtenteCollocazioneRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaRUtenteCollocazionePath(Table<O> path, ForeignKey<O, ReeaRUtenteCollocazioneRecord> childPath, InverseForeignKey<O, ReeaRUtenteCollocazioneRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaRUtenteCollocazionePath(Name alias, Table<ReeaRUtenteCollocazioneRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaRUtenteCollocazionePath as(String alias) {
            return new ReeaRUtenteCollocazionePath(DSL.name(alias), this);
        }

        @Override
        public ReeaRUtenteCollocazionePath as(Name alias) {
            return new ReeaRUtenteCollocazionePath(alias, this);
        }

        @Override
        public ReeaRUtenteCollocazionePath as(Table<?> alias) {
            return new ReeaRUtenteCollocazionePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_R_UTENTE_COLLOCAZIONE_1, Indexes.IDX_REEA_R_UTENTE_COLLOCAZIONE_2);
    }

    @Override
    public Identity<ReeaRUtenteCollocazioneRecord, Integer> getIdentity() {
        return (Identity<ReeaRUtenteCollocazioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaRUtenteCollocazioneRecord> getPrimaryKey() {
        return Keys.REEA_R_UTENTE_COLLOCAZIONE_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaRUtenteCollocazioneRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_R_UTENTE_COLLOCAZIONE__REEA_T_UTENTE_REEA_R_UTENTE_COLLOCAZIONE, Keys.REEA_R_UTENTE_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_R_UTENTE_COLLOCAZIONE);
    }

    private transient ReeaTUtentePath _reeaTUtente;

    /**
     * Get the implicit join path to the <code>reea.reea_t_utente</code> table.
     */
    public ReeaTUtentePath reeaTUtente() {
        if (_reeaTUtente == null)
            _reeaTUtente = new ReeaTUtentePath(this, Keys.REEA_R_UTENTE_COLLOCAZIONE__REEA_T_UTENTE_REEA_R_UTENTE_COLLOCAZIONE, null);

        return _reeaTUtente;
    }

    private transient ReeaTCollocazionePath _reeaTCollocazione;

    /**
     * Get the implicit join path to the <code>reea.reea_t_collocazione</code>
     * table.
     */
    public ReeaTCollocazionePath reeaTCollocazione() {
        if (_reeaTCollocazione == null)
            _reeaTCollocazione = new ReeaTCollocazionePath(this, Keys.REEA_R_UTENTE_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_R_UTENTE_COLLOCAZIONE, null);

        return _reeaTCollocazione;
    }

    @Override
    public ReeaRUtenteCollocazione as(String alias) {
        return new ReeaRUtenteCollocazione(DSL.name(alias), this);
    }

    @Override
    public ReeaRUtenteCollocazione as(Name alias) {
        return new ReeaRUtenteCollocazione(alias, this);
    }

    @Override
    public ReeaRUtenteCollocazione as(Table<?> alias) {
        return new ReeaRUtenteCollocazione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteCollocazione rename(String name) {
        return new ReeaRUtenteCollocazione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteCollocazione rename(Name name) {
        return new ReeaRUtenteCollocazione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRUtenteCollocazione rename(Table<?> name) {
        return new ReeaRUtenteCollocazione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione where(Condition condition) {
        return new ReeaRUtenteCollocazione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteCollocazione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteCollocazione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteCollocazione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRUtenteCollocazione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRUtenteCollocazione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
