/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaDAsl.ReeaDAslPath;
import it.csi.registry.jooq.tables.ReeaRUtenteCollocazione.ReeaRUtenteCollocazionePath;
import it.csi.registry.jooq.tables.records.ReeaTCollocazioneRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Sedi operative (ospedali, distretti) associate alle aziende.  Fonte: PDF
 * Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_T_COLLOCAZIONE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTCollocazione extends TableImpl<ReeaTCollocazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_t_collocazione</code>
     */
    public static final ReeaTCollocazione REEA_T_COLLOCAZIONE = new ReeaTCollocazione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaTCollocazioneRecord> getRecordType() {
        return ReeaTCollocazioneRecord.class;
    }

    /**
     * The column <code>reea.reea_t_collocazione.collocazione_id</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, Integer> COLLOCAZIONE_ID = createField(DSL.name("collocazione_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.collocazione_cod</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, String> COLLOCAZIONE_COD = createField(DSL.name("collocazione_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_collocazione.collocazione_desc</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, String> COLLOCAZIONE_DESC = createField(DSL.name("collocazione_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_collocazione.azienda_id</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, Integer> AZIENDA_ID = createField(DSL.name("azienda_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_t_collocazione.validita_inizio</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.validita_fine</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.data_creazione</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.data_modifica</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.data_cancellazione</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_collocazione.utente_creazione</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_collocazione.utente_modifica</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_collocazione.utente_cancellazione</code>.
     */
    public final TableField<ReeaTCollocazioneRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaTCollocazione(Name alias, Table<ReeaTCollocazioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaTCollocazione(Name alias, Table<ReeaTCollocazioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Sedi operative (ospedali, distretti) associate alle aziende.  Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_T_COLLOCAZIONE."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_t_collocazione</code> table reference
     */
    public ReeaTCollocazione(String alias) {
        this(DSL.name(alias), REEA_T_COLLOCAZIONE);
    }

    /**
     * Create an aliased <code>reea.reea_t_collocazione</code> table reference
     */
    public ReeaTCollocazione(Name alias) {
        this(alias, REEA_T_COLLOCAZIONE);
    }

    /**
     * Create a <code>reea.reea_t_collocazione</code> table reference
     */
    public ReeaTCollocazione() {
        this(DSL.name("reea_t_collocazione"), null);
    }

    public <O extends Record> ReeaTCollocazione(Table<O> path, ForeignKey<O, ReeaTCollocazioneRecord> childPath, InverseForeignKey<O, ReeaTCollocazioneRecord> parentPath) {
        super(path, childPath, parentPath, REEA_T_COLLOCAZIONE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaTCollocazionePath extends ReeaTCollocazione implements Path<ReeaTCollocazioneRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaTCollocazionePath(Table<O> path, ForeignKey<O, ReeaTCollocazioneRecord> childPath, InverseForeignKey<O, ReeaTCollocazioneRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaTCollocazionePath(Name alias, Table<ReeaTCollocazioneRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaTCollocazionePath as(String alias) {
            return new ReeaTCollocazionePath(DSL.name(alias), this);
        }

        @Override
        public ReeaTCollocazionePath as(Name alias) {
            return new ReeaTCollocazionePath(alias, this);
        }

        @Override
        public ReeaTCollocazionePath as(Table<?> alias) {
            return new ReeaTCollocazionePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_T_COLLOCAZIONE_1);
    }

    @Override
    public Identity<ReeaTCollocazioneRecord, Integer> getIdentity() {
        return (Identity<ReeaTCollocazioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaTCollocazioneRecord> getPrimaryKey() {
        return Keys.REEA_T_COLLOCAZIONE_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaTCollocazioneRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_T_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_D_ASL_ID_FKEY);
    }

    private transient ReeaDAslPath _reeaDAsl;

    /**
     * Get the implicit join path to the <code>reea.reea_d_asl</code> table.
     */
    public ReeaDAslPath reeaDAsl() {
        if (_reeaDAsl == null)
            _reeaDAsl = new ReeaDAslPath(this, Keys.REEA_T_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_D_ASL_ID_FKEY, null);

        return _reeaDAsl;
    }

    private transient ReeaRUtenteCollocazionePath _reeaRUtenteCollocazione;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_utente_collocazione</code> table
     */
    public ReeaRUtenteCollocazionePath reeaRUtenteCollocazione() {
        if (_reeaRUtenteCollocazione == null)
            _reeaRUtenteCollocazione = new ReeaRUtenteCollocazionePath(this, null, Keys.REEA_R_UTENTE_COLLOCAZIONE__REEA_T_COLLOCAZIONE_REEA_R_UTENTE_COLLOCAZIONE.getInverseKey());

        return _reeaRUtenteCollocazione;
    }

    @Override
    public ReeaTCollocazione as(String alias) {
        return new ReeaTCollocazione(DSL.name(alias), this);
    }

    @Override
    public ReeaTCollocazione as(Name alias) {
        return new ReeaTCollocazione(alias, this);
    }

    @Override
    public ReeaTCollocazione as(Table<?> alias) {
        return new ReeaTCollocazione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTCollocazione rename(String name) {
        return new ReeaTCollocazione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTCollocazione rename(Name name) {
        return new ReeaTCollocazione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTCollocazione rename(Table<?> name) {
        return new ReeaTCollocazione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione where(Condition condition) {
        return new ReeaTCollocazione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTCollocazione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTCollocazione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTCollocazione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTCollocazione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTCollocazione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
