/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaRRuoloProfilo.ReeaRRuoloProfiloPath;
import it.csi.registry.jooq.tables.ReeaRUtenteRuolo.ReeaRUtenteRuoloPath;
import it.csi.registry.jooq.tables.records.ReeaDRuoloRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Ruoli assegnabili agli utenti (es. Medico competente, Amministrativo). 
 * Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_RUOLO.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRuolo extends TableImpl<ReeaDRuoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_d_ruolo</code>
     */
    public static final ReeaDRuolo REEA_D_RUOLO = new ReeaDRuolo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDRuoloRecord> getRecordType() {
        return ReeaDRuoloRecord.class;
    }

    /**
     * The column <code>reea.reea_d_ruolo.ruolo_id</code>.
     */
    public final TableField<ReeaDRuoloRecord, Integer> RUOLO_ID = createField(DSL.name("ruolo_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.ruolo_cod</code>.
     */
    public final TableField<ReeaDRuoloRecord, String> RUOLO_COD = createField(DSL.name("ruolo_cod"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_ruolo.ruolo_desc</code>.
     */
    public final TableField<ReeaDRuoloRecord, String> RUOLO_DESC = createField(DSL.name("ruolo_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_ruolo.validita_inizio</code>.
     */
    public final TableField<ReeaDRuoloRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.validita_fine</code>.
     */
    public final TableField<ReeaDRuoloRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.data_creazione</code>.
     */
    public final TableField<ReeaDRuoloRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.data_modifica</code>.
     */
    public final TableField<ReeaDRuoloRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.data_cancellazione</code>.
     */
    public final TableField<ReeaDRuoloRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_ruolo.utente_creazione</code>.
     */
    public final TableField<ReeaDRuoloRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_ruolo.utente_modifica</code>.
     */
    public final TableField<ReeaDRuoloRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_ruolo.utente_cancellazione</code>.
     */
    public final TableField<ReeaDRuoloRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaDRuolo(Name alias, Table<ReeaDRuoloRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDRuolo(Name alias, Table<ReeaDRuoloRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Ruoli assegnabili agli utenti (es. Medico competente, Amministrativo).  Fonte: PDF Specifica Database, Sezione 2.1 (Pag. 4), Tabella REEA_D_RUOLO."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_ruolo</code> table reference
     */
    public ReeaDRuolo(String alias) {
        this(DSL.name(alias), REEA_D_RUOLO);
    }

    /**
     * Create an aliased <code>reea.reea_d_ruolo</code> table reference
     */
    public ReeaDRuolo(Name alias) {
        this(alias, REEA_D_RUOLO);
    }

    /**
     * Create a <code>reea.reea_d_ruolo</code> table reference
     */
    public ReeaDRuolo() {
        this(DSL.name("reea_d_ruolo"), null);
    }

    public <O extends Record> ReeaDRuolo(Table<O> path, ForeignKey<O, ReeaDRuoloRecord> childPath, InverseForeignKey<O, ReeaDRuoloRecord> parentPath) {
        super(path, childPath, parentPath, REEA_D_RUOLO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaDRuoloPath extends ReeaDRuolo implements Path<ReeaDRuoloRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaDRuoloPath(Table<O> path, ForeignKey<O, ReeaDRuoloRecord> childPath, InverseForeignKey<O, ReeaDRuoloRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaDRuoloPath(Name alias, Table<ReeaDRuoloRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaDRuoloPath as(String alias) {
            return new ReeaDRuoloPath(DSL.name(alias), this);
        }

        @Override
        public ReeaDRuoloPath as(Name alias) {
            return new ReeaDRuoloPath(alias, this);
        }

        @Override
        public ReeaDRuoloPath as(Table<?> alias) {
            return new ReeaDRuoloPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public Identity<ReeaDRuoloRecord, Integer> getIdentity() {
        return (Identity<ReeaDRuoloRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDRuoloRecord> getPrimaryKey() {
        return Keys.REEA_D_RUOLO_PKEY;
    }

    private transient ReeaRRuoloProfiloPath _reeaRRuoloProfilo;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_ruolo_profilo</code> table
     */
    public ReeaRRuoloProfiloPath reeaRRuoloProfilo() {
        if (_reeaRRuoloProfilo == null)
            _reeaRRuoloProfilo = new ReeaRRuoloProfiloPath(this, null, Keys.REEA_R_RUOLO_PROFILO__REEA_R_RUOLO_PROFILO_REEA_D_RUOLO_ID_FKEY.getInverseKey());

        return _reeaRRuoloProfilo;
    }

    private transient ReeaRUtenteRuoloPath _reeaRUtenteRuolo;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_r_utente_ruolo</code> table
     */
    public ReeaRUtenteRuoloPath reeaRUtenteRuolo() {
        if (_reeaRUtenteRuolo == null)
            _reeaRUtenteRuolo = new ReeaRUtenteRuoloPath(this, null, Keys.REEA_R_UTENTE_RUOLO__REEA_R_UTENTE_RUOLO_REEA_D_RUOLO_ID_FKEY.getInverseKey());

        return _reeaRUtenteRuolo;
    }

    @Override
    public ReeaDRuolo as(String alias) {
        return new ReeaDRuolo(DSL.name(alias), this);
    }

    @Override
    public ReeaDRuolo as(Name alias) {
        return new ReeaDRuolo(alias, this);
    }

    @Override
    public ReeaDRuolo as(Table<?> alias) {
        return new ReeaDRuolo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRuolo rename(String name) {
        return new ReeaDRuolo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRuolo rename(Name name) {
        return new ReeaDRuolo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRuolo rename(Table<?> name) {
        return new ReeaDRuolo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo where(Condition condition) {
        return new ReeaDRuolo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRuolo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRuolo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRuolo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRuolo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRuolo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
