/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaTRegistro.ReeaTRegistroPath;
import it.csi.registry.jooq.tables.records.ReeaTRegistroSnapshotRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
 * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
 * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica Database,
 * Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaTRegistroSnapshot extends TableImpl<ReeaTRegistroSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_t_registro_snapshot</code>
     */
    public static final ReeaTRegistroSnapshot REEA_T_REGISTRO_SNAPSHOT = new ReeaTRegistroSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaTRegistroSnapshotRecord> getRecordType() {
        return ReeaTRegistroSnapshotRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_t_registro_snapshot.registro_snapshot_id</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, Integer> REGISTRO_SNAPSHOT_ID = createField(DSL.name("registro_snapshot_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.registro_id</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.dati_jsonb</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, JSONB> DATI_JSONB = createField(DSL.name("dati_jsonb"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.versione_numero</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, Integer> VERSIONE_NUMERO = createField(DSL.name("versione_numero"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.validita_inizio</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.validita_fine</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.data_creazione</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.data_modifica</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.data_cancellazione</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.utente_creazione</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_t_registro_snapshot.utente_modifica</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_t_registro_snapshot.utente_cancellazione</code>.
     */
    public final TableField<ReeaTRegistroSnapshotRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaTRegistroSnapshot(Name alias, Table<ReeaTRegistroSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaTRegistroSnapshot(Name alias, Table<ReeaTRegistroSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Tabella Master del registro clinico. Anonima e scollegata fisicamente dal soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica Database, Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro)."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_t_registro_snapshot</code> table
     * reference
     */
    public ReeaTRegistroSnapshot(String alias) {
        this(DSL.name(alias), REEA_T_REGISTRO_SNAPSHOT);
    }

    /**
     * Create an aliased <code>reea.reea_t_registro_snapshot</code> table
     * reference
     */
    public ReeaTRegistroSnapshot(Name alias) {
        this(alias, REEA_T_REGISTRO_SNAPSHOT);
    }

    /**
     * Create a <code>reea.reea_t_registro_snapshot</code> table reference
     */
    public ReeaTRegistroSnapshot() {
        this(DSL.name("reea_t_registro_snapshot"), null);
    }

    public <O extends Record> ReeaTRegistroSnapshot(Table<O> path, ForeignKey<O, ReeaTRegistroSnapshotRecord> childPath, InverseForeignKey<O, ReeaTRegistroSnapshotRecord> parentPath) {
        super(path, childPath, parentPath, REEA_T_REGISTRO_SNAPSHOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaTRegistroSnapshotPath extends ReeaTRegistroSnapshot implements Path<ReeaTRegistroSnapshotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaTRegistroSnapshotPath(Table<O> path, ForeignKey<O, ReeaTRegistroSnapshotRecord> childPath, InverseForeignKey<O, ReeaTRegistroSnapshotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaTRegistroSnapshotPath(Name alias, Table<ReeaTRegistroSnapshotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaTRegistroSnapshotPath as(String alias) {
            return new ReeaTRegistroSnapshotPath(DSL.name(alias), this);
        }

        @Override
        public ReeaTRegistroSnapshotPath as(Name alias) {
            return new ReeaTRegistroSnapshotPath(alias, this);
        }

        @Override
        public ReeaTRegistroSnapshotPath as(Table<?> alias) {
            return new ReeaTRegistroSnapshotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_T_REGISTRO_SNAPSHOT_1, Indexes.IDX_REEA_T_REGISTRO_SNAPSHOT_2, Indexes.IDX_REEA_T_REGISTRO_SNAPSHOT_3);
    }

    @Override
    public Identity<ReeaTRegistroSnapshotRecord, Integer> getIdentity() {
        return (Identity<ReeaTRegistroSnapshotRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaTRegistroSnapshotRecord> getPrimaryKey() {
        return Keys.REEA_T_REGISTRO_SNAPSHOT_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaTRegistroSnapshotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_T_REGISTRO_SNAPSHOT__REEA_T_REGISTRO_REEA_T_REGISTRO_SNAPSHOT);
    }

    private transient ReeaTRegistroPath _reeaTRegistro;

    /**
     * Get the implicit join path to the <code>reea.reea_t_registro</code>
     * table.
     */
    public ReeaTRegistroPath reeaTRegistro() {
        if (_reeaTRegistro == null)
            _reeaTRegistro = new ReeaTRegistroPath(this, Keys.REEA_T_REGISTRO_SNAPSHOT__REEA_T_REGISTRO_REEA_T_REGISTRO_SNAPSHOT, null);

        return _reeaTRegistro;
    }

    @Override
    public ReeaTRegistroSnapshot as(String alias) {
        return new ReeaTRegistroSnapshot(DSL.name(alias), this);
    }

    @Override
    public ReeaTRegistroSnapshot as(Name alias) {
        return new ReeaTRegistroSnapshot(alias, this);
    }

    @Override
    public ReeaTRegistroSnapshot as(Table<?> alias) {
        return new ReeaTRegistroSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTRegistroSnapshot rename(String name) {
        return new ReeaTRegistroSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTRegistroSnapshot rename(Name name) {
        return new ReeaTRegistroSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaTRegistroSnapshot rename(Table<?> name) {
        return new ReeaTRegistroSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot where(Condition condition) {
        return new ReeaTRegistroSnapshot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTRegistroSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTRegistroSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTRegistroSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaTRegistroSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaTRegistroSnapshot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
