/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaCParametroTipo.ReeaCParametroTipoPath;
import it.csi.registry.jooq.tables.records.ReeaCParametroRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * parametri di configurazione
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaCParametro extends TableImpl<ReeaCParametroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_c_parametro</code>
     */
    public static final ReeaCParametro REEA_C_PARAMETRO = new ReeaCParametro();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaCParametroRecord> getRecordType() {
        return ReeaCParametroRecord.class;
    }

    /**
     * The column <code>reea.reea_c_parametro.parametro_id</code>.
     */
    public final TableField<ReeaCParametroRecord, Integer> PARAMETRO_ID = createField(DSL.name("parametro_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_c_parametro.parametro_cod</code>. codice
     */
    public final TableField<ReeaCParametroRecord, String> PARAMETRO_COD = createField(DSL.name("parametro_cod"), SQLDataType.CLOB.nullable(false), this, "codice");

    /**
     * The column <code>reea.reea_c_parametro.parametro_desc</code>. descrizione
     */
    public final TableField<ReeaCParametroRecord, String> PARAMETRO_DESC = createField(DSL.name("parametro_desc"), SQLDataType.CLOB, this, "descrizione");

    /**
     * The column <code>reea.reea_c_parametro.parametro_valore</code>.
     */
    public final TableField<ReeaCParametroRecord, String> PARAMETRO_VALORE = createField(DSL.name("parametro_valore"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_c_parametro.parametro_tipo_id</code>.
     */
    public final TableField<ReeaCParametroRecord, Integer> PARAMETRO_TIPO_ID = createField(DSL.name("parametro_tipo_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_c_parametro.validita_inizio</code>. inizio
     * validità record
     */
    public final TableField<ReeaCParametroRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "inizio validità record");

    /**
     * The column <code>reea.reea_c_parametro.validita_fine</code>. fine
     * validità record
     */
    public final TableField<ReeaCParametroRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "fine validità record");

    /**
     * The column <code>reea.reea_c_parametro.data_creazione</code>. data
     * creazione record
     */
    public final TableField<ReeaCParametroRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "data creazione record");

    /**
     * The column <code>reea.reea_c_parametro.data_modifica</code>. data
     * modifica record
     */
    public final TableField<ReeaCParametroRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "data modifica record");

    /**
     * The column <code>reea.reea_c_parametro.data_cancellazione</code>. data
     * cancellazione record
     */
    public final TableField<ReeaCParametroRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "data cancellazione record");

    /**
     * The column <code>reea.reea_c_parametro.utente_creazione</code>. utente
     * creazione
     */
    public final TableField<ReeaCParametroRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB.nullable(false), this, "utente creazione");

    /**
     * The column <code>reea.reea_c_parametro.utente_modifica</code>. utente
     * modifica
     */
    public final TableField<ReeaCParametroRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB.nullable(false), this, "utente modifica");

    /**
     * The column <code>reea.reea_c_parametro.utente_cancellazione</code>.
     * utente cancellazione
     */
    public final TableField<ReeaCParametroRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "utente cancellazione");

    private ReeaCParametro(Name alias, Table<ReeaCParametroRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaCParametro(Name alias, Table<ReeaCParametroRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("parametri di configurazione"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_c_parametro</code> table reference
     */
    public ReeaCParametro(String alias) {
        this(DSL.name(alias), REEA_C_PARAMETRO);
    }

    /**
     * Create an aliased <code>reea.reea_c_parametro</code> table reference
     */
    public ReeaCParametro(Name alias) {
        this(alias, REEA_C_PARAMETRO);
    }

    /**
     * Create a <code>reea.reea_c_parametro</code> table reference
     */
    public ReeaCParametro() {
        this(DSL.name("reea_c_parametro"), null);
    }

    public <O extends Record> ReeaCParametro(Table<O> path, ForeignKey<O, ReeaCParametroRecord> childPath, InverseForeignKey<O, ReeaCParametroRecord> parentPath) {
        super(path, childPath, parentPath, REEA_C_PARAMETRO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaCParametroPath extends ReeaCParametro implements Path<ReeaCParametroRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaCParametroPath(Table<O> path, ForeignKey<O, ReeaCParametroRecord> childPath, InverseForeignKey<O, ReeaCParametroRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaCParametroPath(Name alias, Table<ReeaCParametroRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaCParametroPath as(String alias) {
            return new ReeaCParametroPath(DSL.name(alias), this);
        }

        @Override
        public ReeaCParametroPath as(Name alias) {
            return new ReeaCParametroPath(alias, this);
        }

        @Override
        public ReeaCParametroPath as(Table<?> alias) {
            return new ReeaCParametroPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_C_PARAMETRO_1);
    }

    @Override
    public Identity<ReeaCParametroRecord, Integer> getIdentity() {
        return (Identity<ReeaCParametroRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaCParametroRecord> getPrimaryKey() {
        return Keys.REEA_C_PARAMETRO_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaCParametroRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_C_PARAMETRO__REEA_C_PARAMETRO_TIPO_REEA_C_PARAMETRO);
    }

    private transient ReeaCParametroTipoPath _reeaCParametroTipo;

    /**
     * Get the implicit join path to the <code>reea.reea_c_parametro_tipo</code>
     * table.
     */
    public ReeaCParametroTipoPath reeaCParametroTipo() {
        if (_reeaCParametroTipo == null)
            _reeaCParametroTipo = new ReeaCParametroTipoPath(this, Keys.REEA_C_PARAMETRO__REEA_C_PARAMETRO_TIPO_REEA_C_PARAMETRO, null);

        return _reeaCParametroTipo;
    }

    @Override
    public ReeaCParametro as(String alias) {
        return new ReeaCParametro(DSL.name(alias), this);
    }

    @Override
    public ReeaCParametro as(Name alias) {
        return new ReeaCParametro(alias, this);
    }

    @Override
    public ReeaCParametro as(Table<?> alias) {
        return new ReeaCParametro(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaCParametro rename(String name) {
        return new ReeaCParametro(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaCParametro rename(Name name) {
        return new ReeaCParametro(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaCParametro rename(Table<?> name) {
        return new ReeaCParametro(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro where(Condition condition) {
        return new ReeaCParametro(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaCParametro where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaCParametro where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaCParametro where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaCParametro where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaCParametro whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
