/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaSSoggetto.ReeaSSoggettoPath;
import it.csi.registry.jooq.tables.ReeaTEsposizione.ReeaTEsposizionePath;
import it.csi.registry.jooq.tables.ReeaTSoggetto.ReeaTSoggettoPath;
import it.csi.registry.jooq.tables.records.ReeaDFonteRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Segnalazione MMG, altro Pre-adesione INAIL SPRESAL PIANI DI LAVORO AMIANTO  
 * --ex valori PREADESIONE INAIL SPRESAL-ANMNESI SPRESAL-ESITI PIANI DI LAVORO
 * AMIANTO REGISTRO CANCEROGENI MANUALE(MMG)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDFonte extends TableImpl<ReeaDFonteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_d_fonte</code>
     */
    public static final ReeaDFonte REEA_D_FONTE = new ReeaDFonte();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDFonteRecord> getRecordType() {
        return ReeaDFonteRecord.class;
    }

    /**
     * The column <code>reea.reea_d_fonte.fonte_id</code>.
     */
    public final TableField<ReeaDFonteRecord, Integer> FONTE_ID = createField(DSL.name("fonte_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_d_fonte.fonte_cod</code>.
     */
    public final TableField<ReeaDFonteRecord, String> FONTE_COD = createField(DSL.name("fonte_cod"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_fonte.fonte_desc</code>.
     */
    public final TableField<ReeaDFonteRecord, String> FONTE_DESC = createField(DSL.name("fonte_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_fonte.validita_inizio</code>.
     */
    public final TableField<ReeaDFonteRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_fonte.validita_fine</code>.
     */
    public final TableField<ReeaDFonteRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_fonte.data_creazione</code>.
     */
    public final TableField<ReeaDFonteRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_fonte.data_modifica</code>.
     */
    public final TableField<ReeaDFonteRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_fonte.data_cancellazione</code>.
     */
    public final TableField<ReeaDFonteRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_fonte.utente_creazione</code>.
     */
    public final TableField<ReeaDFonteRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_fonte.utente_modifica</code>.
     */
    public final TableField<ReeaDFonteRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_d_fonte.utente_cancellazione</code>.
     */
    public final TableField<ReeaDFonteRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaDFonte(Name alias, Table<ReeaDFonteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDFonte(Name alias, Table<ReeaDFonteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Segnalazione MMG, altro Pre-adesione INAIL SPRESAL PIANI DI LAVORO AMIANTO   --ex valori PREADESIONE INAIL SPRESAL-ANMNESI SPRESAL-ESITI PIANI DI LAVORO AMIANTO REGISTRO CANCEROGENI MANUALE(MMG)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_fonte</code> table reference
     */
    public ReeaDFonte(String alias) {
        this(DSL.name(alias), REEA_D_FONTE);
    }

    /**
     * Create an aliased <code>reea.reea_d_fonte</code> table reference
     */
    public ReeaDFonte(Name alias) {
        this(alias, REEA_D_FONTE);
    }

    /**
     * Create a <code>reea.reea_d_fonte</code> table reference
     */
    public ReeaDFonte() {
        this(DSL.name("reea_d_fonte"), null);
    }

    public <O extends Record> ReeaDFonte(Table<O> path, ForeignKey<O, ReeaDFonteRecord> childPath, InverseForeignKey<O, ReeaDFonteRecord> parentPath) {
        super(path, childPath, parentPath, REEA_D_FONTE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaDFontePath extends ReeaDFonte implements Path<ReeaDFonteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaDFontePath(Table<O> path, ForeignKey<O, ReeaDFonteRecord> childPath, InverseForeignKey<O, ReeaDFonteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaDFontePath(Name alias, Table<ReeaDFonteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaDFontePath as(String alias) {
            return new ReeaDFontePath(DSL.name(alias), this);
        }

        @Override
        public ReeaDFontePath as(Name alias) {
            return new ReeaDFontePath(alias, this);
        }

        @Override
        public ReeaDFontePath as(Table<?> alias) {
            return new ReeaDFontePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public Identity<ReeaDFonteRecord, Integer> getIdentity() {
        return (Identity<ReeaDFonteRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDFonteRecord> getPrimaryKey() {
        return Keys.REEA_D_FONTE_PKEY;
    }

    private transient ReeaSSoggettoPath _reeaSSoggetto;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_s_soggetto</code> table
     */
    public ReeaSSoggettoPath reeaSSoggetto() {
        if (_reeaSSoggetto == null)
            _reeaSSoggetto = new ReeaSSoggettoPath(this, null, Keys.REEA_S_SOGGETTO__REEA_D_FONTE_REEA_S_SOGGETTO.getInverseKey());

        return _reeaSSoggetto;
    }

    private transient ReeaTEsposizionePath _reeaTEsposizione;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_t_esposizione</code> table
     */
    public ReeaTEsposizionePath reeaTEsposizione() {
        if (_reeaTEsposizione == null)
            _reeaTEsposizione = new ReeaTEsposizionePath(this, null, Keys.REEA_T_ESPOSIZIONE__REEA_D_FONTE_REEA_T_ESPOSIZIONE.getInverseKey());

        return _reeaTEsposizione;
    }

    private transient ReeaTSoggettoPath _reeaTSoggetto;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_t_soggetto</code> table
     */
    public ReeaTSoggettoPath reeaTSoggetto() {
        if (_reeaTSoggetto == null)
            _reeaTSoggetto = new ReeaTSoggettoPath(this, null, Keys.REEA_T_SOGGETTO__REEA_D_FONTE_REEA_T_SOGGETTO.getInverseKey());

        return _reeaTSoggetto;
    }

    @Override
    public ReeaDFonte as(String alias) {
        return new ReeaDFonte(DSL.name(alias), this);
    }

    @Override
    public ReeaDFonte as(Name alias) {
        return new ReeaDFonte(alias, this);
    }

    @Override
    public ReeaDFonte as(Table<?> alias) {
        return new ReeaDFonte(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFonte rename(String name) {
        return new ReeaDFonte(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFonte rename(Name name) {
        return new ReeaDFonte(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDFonte rename(Table<?> name) {
        return new ReeaDFonte(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte where(Condition condition) {
        return new ReeaDFonte(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFonte where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFonte where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFonte where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDFonte where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDFonte whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
