/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.ReeaDNazione.ReeaDNazionePath;
import it.csi.registry.jooq.tables.ReeaDProvincia.ReeaDProvinciaPath;
import it.csi.registry.jooq.tables.records.ReeaDRegioneRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * REGIONE PIEMONTE FUORI REGIONE PIEMONTE SASN AIRE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaDRegione extends TableImpl<ReeaDRegioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_d_regione</code>
     */
    public static final ReeaDRegione REEA_D_REGIONE = new ReeaDRegione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaDRegioneRecord> getRecordType() {
        return ReeaDRegioneRecord.class;
    }

    /**
     * The column <code>reea.reea_d_regione.regione_id</code>.
     */
    public final TableField<ReeaDRegioneRecord, Integer> REGIONE_ID = createField(DSL.name("regione_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_d_regione.regione_cod</code>.
     */
    public final TableField<ReeaDRegioneRecord, String> REGIONE_COD = createField(DSL.name("regione_cod"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_regione.regione_desc</code>.
     */
    public final TableField<ReeaDRegioneRecord, String> REGIONE_DESC = createField(DSL.name("regione_desc"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_regione.nazione_id</code>.
     */
    public final TableField<ReeaDRegioneRecord, Integer> NAZIONE_ID = createField(DSL.name("nazione_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>reea.reea_d_regione.validita_inizio</code>.
     */
    public final TableField<ReeaDRegioneRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_regione.validita_fine</code>.
     */
    public final TableField<ReeaDRegioneRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_regione.data_creazione</code>.
     */
    public final TableField<ReeaDRegioneRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_regione.data_modifica</code>.
     */
    public final TableField<ReeaDRegioneRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_d_regione.data_cancellazione</code>.
     */
    public final TableField<ReeaDRegioneRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_d_regione.utente_creazione</code>.
     */
    public final TableField<ReeaDRegioneRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_regione.utente_modifica</code>.
     */
    public final TableField<ReeaDRegioneRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_d_regione.utente_cancellazione</code>.
     */
    public final TableField<ReeaDRegioneRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaDRegione(Name alias, Table<ReeaDRegioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaDRegione(Name alias, Table<ReeaDRegioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("REGIONE PIEMONTE FUORI REGIONE PIEMONTE SASN AIRE"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_d_regione</code> table reference
     */
    public ReeaDRegione(String alias) {
        this(DSL.name(alias), REEA_D_REGIONE);
    }

    /**
     * Create an aliased <code>reea.reea_d_regione</code> table reference
     */
    public ReeaDRegione(Name alias) {
        this(alias, REEA_D_REGIONE);
    }

    /**
     * Create a <code>reea.reea_d_regione</code> table reference
     */
    public ReeaDRegione() {
        this(DSL.name("reea_d_regione"), null);
    }

    public <O extends Record> ReeaDRegione(Table<O> path, ForeignKey<O, ReeaDRegioneRecord> childPath, InverseForeignKey<O, ReeaDRegioneRecord> parentPath) {
        super(path, childPath, parentPath, REEA_D_REGIONE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReeaDRegionePath extends ReeaDRegione implements Path<ReeaDRegioneRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReeaDRegionePath(Table<O> path, ForeignKey<O, ReeaDRegioneRecord> childPath, InverseForeignKey<O, ReeaDRegioneRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReeaDRegionePath(Name alias, Table<ReeaDRegioneRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReeaDRegionePath as(String alias) {
            return new ReeaDRegionePath(DSL.name(alias), this);
        }

        @Override
        public ReeaDRegionePath as(Name alias) {
            return new ReeaDRegionePath(alias, this);
        }

        @Override
        public ReeaDRegionePath as(Table<?> alias) {
            return new ReeaDRegionePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_D_REGIONE_1);
    }

    @Override
    public Identity<ReeaDRegioneRecord, Integer> getIdentity() {
        return (Identity<ReeaDRegioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaDRegioneRecord> getPrimaryKey() {
        return Keys.REEA_D_REGIONE_PKEY;
    }

    @Override
    public List<ForeignKey<ReeaDRegioneRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REEA_D_REGIONE__REEA_D_NAZIONE_REEA_D_REGIONE);
    }

    private transient ReeaDNazionePath _reeaDNazione;

    /**
     * Get the implicit join path to the <code>reea.reea_d_nazione</code> table.
     */
    public ReeaDNazionePath reeaDNazione() {
        if (_reeaDNazione == null)
            _reeaDNazione = new ReeaDNazionePath(this, Keys.REEA_D_REGIONE__REEA_D_NAZIONE_REEA_D_REGIONE, null);

        return _reeaDNazione;
    }

    private transient ReeaDProvinciaPath _reeaDProvincia;

    /**
     * Get the implicit to-many join path to the
     * <code>reea.reea_d_provincia</code> table
     */
    public ReeaDProvinciaPath reeaDProvincia() {
        if (_reeaDProvincia == null)
            _reeaDProvincia = new ReeaDProvinciaPath(this, null, Keys.REEA_D_PROVINCIA__REEA_D_REGIONE_REEA_D_PROVINCIA.getInverseKey());

        return _reeaDProvincia;
    }

    @Override
    public ReeaDRegione as(String alias) {
        return new ReeaDRegione(DSL.name(alias), this);
    }

    @Override
    public ReeaDRegione as(Name alias) {
        return new ReeaDRegione(alias, this);
    }

    @Override
    public ReeaDRegione as(Table<?> alias) {
        return new ReeaDRegione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegione rename(String name) {
        return new ReeaDRegione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegione rename(Name name) {
        return new ReeaDRegione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaDRegione rename(Table<?> name) {
        return new ReeaDRegione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione where(Condition condition) {
        return new ReeaDRegione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaDRegione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaDRegione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
