/*
 * This file is generated by jOOQ.
 */
package it.csi.registry.jooq.tables;


import it.csi.registry.jooq.Indexes;
import it.csi.registry.jooq.Keys;
import it.csi.registry.jooq.Reea;
import it.csi.registry.jooq.tables.records.ReeaRSoggettoEsenzioneRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Tabella Master del registro clinico. Anonima e scollegata fisicamente dal
 * soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per
 * recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica Database,
 * Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro).
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReeaRSoggettoEsenzione extends TableImpl<ReeaRSoggettoEsenzioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reea.reea_r_soggetto_esenzione</code>
     */
    public static final ReeaRSoggettoEsenzione REEA_R_SOGGETTO_ESENZIONE = new ReeaRSoggettoEsenzione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReeaRSoggettoEsenzioneRecord> getRecordType() {
        return ReeaRSoggettoEsenzioneRecord.class;
    }

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.soggetto_esenzione_id</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, Integer> SOGGETTO_ESENZIONE_ID = createField(DSL.name("soggetto_esenzione_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.soggetto_id_hmac</code>.
     * COLLATE "C"
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, String> SOGGETTO_ID_HMAC = createField(DSL.name("soggetto_id_hmac"), SQLDataType.CLOB.nullable(false), this, "COLLATE \"C\"");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.soggetto_id_cifrato</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, byte[]> SOGGETTO_ID_CIFRATO = createField(DSL.name("soggetto_id_cifrato"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.esenzione_id_hmac</code>.
     * COLLATE "C"
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, String> ESENZIONE_ID_HMAC = createField(DSL.name("esenzione_id_hmac"), SQLDataType.CLOB.nullable(false), this, "COLLATE \"C\"");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.esenzione_id_cifrato</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, byte[]> ESENZIONE_ID_CIFRATO = createField(DSL.name("esenzione_id_cifrato"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.esenzione_data_emissione</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDate> ESENZIONE_DATA_EMISSIONE = createField(DSL.name("esenzione_data_emissione"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.esenzione_data_scadenza</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDate> ESENZIONE_DATA_SCADENZA = createField(DSL.name("esenzione_data_scadenza"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.validita_inizio</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDateTime> VALIDITA_INIZIO = createField(DSL.name("validita_inizio"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.validita_fine</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDateTime> VALIDITA_FINE = createField(DSL.name("validita_fine"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.data_creazione</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDateTime> DATA_CREAZIONE = createField(DSL.name("data_creazione"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.data_modifica</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDateTime> DATA_MODIFICA = createField(DSL.name("data_modifica"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.data_cancellazione</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, LocalDateTime> DATA_CANCELLAZIONE = createField(DSL.name("data_cancellazione"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.utente_creazione</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, String> UTENTE_CREAZIONE = createField(DSL.name("utente_creazione"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>reea.reea_r_soggetto_esenzione.utente_modifica</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, String> UTENTE_MODIFICA = createField(DSL.name("utente_modifica"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>reea.reea_r_soggetto_esenzione.utente_cancellazione</code>.
     */
    public final TableField<ReeaRSoggettoEsenzioneRecord, String> UTENTE_CANCELLAZIONE = createField(DSL.name("utente_cancellazione"), SQLDataType.CLOB, this, "");

    private ReeaRSoggettoEsenzione(Name alias, Table<ReeaRSoggettoEsenzioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReeaRSoggettoEsenzione(Name alias, Table<ReeaRSoggettoEsenzioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Tabella Master del registro clinico. Anonima e scollegata fisicamente dal soggetto. Contiene i token di sicurezza (HMAC per ricerca, Cifrato per recupero) e i dati di screening base (Pag. 9). Fonte: PDF Specifica Database, Sezione 2.3.5 (Pag. 10) e Pagina 9 (Dati Registro)."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reea.reea_r_soggetto_esenzione</code> table
     * reference
     */
    public ReeaRSoggettoEsenzione(String alias) {
        this(DSL.name(alias), REEA_R_SOGGETTO_ESENZIONE);
    }

    /**
     * Create an aliased <code>reea.reea_r_soggetto_esenzione</code> table
     * reference
     */
    public ReeaRSoggettoEsenzione(Name alias) {
        this(alias, REEA_R_SOGGETTO_ESENZIONE);
    }

    /**
     * Create a <code>reea.reea_r_soggetto_esenzione</code> table reference
     */
    public ReeaRSoggettoEsenzione() {
        this(DSL.name("reea_r_soggetto_esenzione"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Reea.REEA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REEA_R_SOGGETTO_ESENZIONE_1, Indexes.IDX_REEA_R_SOGGETTO_ESENZIONE_2);
    }

    @Override
    public Identity<ReeaRSoggettoEsenzioneRecord, Integer> getIdentity() {
        return (Identity<ReeaRSoggettoEsenzioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReeaRSoggettoEsenzioneRecord> getPrimaryKey() {
        return Keys.REEA_R_SOGGETTO_ESENZIONE_PKEY;
    }

    @Override
    public ReeaRSoggettoEsenzione as(String alias) {
        return new ReeaRSoggettoEsenzione(DSL.name(alias), this);
    }

    @Override
    public ReeaRSoggettoEsenzione as(Name alias) {
        return new ReeaRSoggettoEsenzione(alias, this);
    }

    @Override
    public ReeaRSoggettoEsenzione as(Table<?> alias) {
        return new ReeaRSoggettoEsenzione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRSoggettoEsenzione rename(String name) {
        return new ReeaRSoggettoEsenzione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRSoggettoEsenzione rename(Name name) {
        return new ReeaRSoggettoEsenzione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReeaRSoggettoEsenzione rename(Table<?> name) {
        return new ReeaRSoggettoEsenzione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione where(Condition condition) {
        return new ReeaRSoggettoEsenzione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRSoggettoEsenzione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRSoggettoEsenzione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRSoggettoEsenzione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReeaRSoggettoEsenzione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReeaRSoggettoEsenzione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
