sonar.projectKey=reea_reeafe
sonar.projectName=reea - reeafe
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

